<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../../../../../../../Disco%20D/veinti4online/Proyecto%20Cash/Concentrador%20de%20pagos/DOCUMENTACIONMAPEO/Project4/otc-nopolicy.wsdl"/>
      <rootElement name="entradaConsultarDeuda" namespace="http://www.bolivariano.com/mensaje/MensajeOTC"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../../../../../../../Disco%20D/veinti4online/Proyecto%20Cash/Concentrador%20de%20pagos/DOCUMENTACIONMAPEO/Project4/xsd/RecaudacionAgua_1.wsdl"/>
      <rootElement name="MensajeEntradaObtenerSaldoPendiente" namespace="http://www.bolivariano.com/CashManagement/MensajesRecaudacionAgua"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 130301.0647.0008) AT [TUE JUN 05 15:04:37 COT 2018]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:ns11="http://www.bolivariano.com/CashManagement/ws/RecaudacionAgua"
                xmlns:ns12="http://www.bolivariano.com/FormaPago"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:ns15="http://www.bolivariano.com/Enumerados"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:ns1="http://www.bolivariano.com/dominio/DatoAdicional"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:ns14="http://www.bolivariano.com/CoreBB"
                xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:ns5="http://www.bolivariano.com/dominio/Convenio"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns6="http://www.bolivariano.com/dominio/Recibo"
                xmlns:ns10="http://www.bolivariano.com/dominio/ListaSeleccion"
                xmlns:ns9="http://www.bolivariano.com/dominio/RegionalArea"
                xmlns:mc="http://www.bolivariano.com/CashManagement/MensajesRecaudacionAgua"
                xmlns:ns0="http://www.bolivariano.com/dominio/Servicio"
                xmlns:ns13="http://www.bolivariano.com/MensajeBolivariano"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ns2="http://www.bolivariano.com/dominio/TipoMatriculacion"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:ns3="http://www.bolivariano.com/dominio/FormaPago"
                xmlns:ns17="http://www.bolivariano.com/Restricciones"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns4="http://www.bolivariano.com/dominio/TipoIdentificador"
                xmlns:tns="http://www.bolivariano.com/mensaje/MensajeOTC"
                xmlns:http="http://schemas.xmlsoap.org/wsdl/http/"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:ns7="http://www.bolivariano.com/dominio/Empresa"
                xmlns:ns16="http://www.bolivariano.com/Comision"
                xmlns:ns8="http://www.bolivariano.com/mensaje/MensajeOTC"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl ns1 soap wsdl ns5 ns6 ns10 ns9 ns0 ns2 ns3 ns4 tns xsd ns7 ns8 ns11 ns12 ns15 ns14 mime mc ns13 plnk ns17 http ns16 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap">
  <xsl:template match="/">
    <mc:MensajeEntradaObtenerSaldoPendiente>
      <canal>
        <xsl:value-of select="/ns8:entradaConsultarDeuda/ns8:canal"/>
      </canal>
      <depuracion>
        <xsl:text disable-output-escaping="no">N</xsl:text>
      </depuracion>
      <fecha>
        <xsl:value-of select='/ns8:entradaConsultarDeuda/ns8:servicio/datosAdicionales/datoAdicional[codigo = "s_date"]/valor'/>
      </fecha>
      <oficina>
        <xsl:value-of select='/ns8:entradaConsultarDeuda/ns8:servicio/datosAdicionales/datoAdicional[codigo = "s_ofi"]/valor'/>
      </oficina>
      <terminal>
        <xsl:text disable-output-escaping="no">ATM00010</xsl:text>
      </terminal>
      <xsl:choose>
        <xsl:when test="/ns8:entradaConsultarDeuda/ns8:servicio/codigoEmpresa=6">
          <transaccion>
            <xsl:text disable-output-escaping="no">62668</xsl:text>
            <!--62668 Amagua en línea para el resto 3137 en base-->
          </transaccion>
        </xsl:when>
        <xsl:when test="/ns8:entradaConsultarDeuda/ns8:servicio/codigoEmpresa!=6">
          <transaccion>
            <xsl:text disable-output-escaping="no">3137</xsl:text>
          </transaccion>
        </xsl:when>
      </xsl:choose>
      <usuario>
        <xsl:value-of select='/ns8:entradaConsultarDeuda/ns8:servicio/datosAdicionales/datoAdicional[codigo = "s_user"]/valor'/>
      </usuario>
      <codigoEmpresa>
        <xsl:value-of select="/ns8:entradaConsultarDeuda/ns8:servicio/codigoEmpresa"/>
      </codigoEmpresa>
      <suministro>
        <xsl:value-of select="/ns8:entradaConsultarDeuda/ns8:servicio/identificador"/>
      </suministro>
	  <xsl:choose>
		<xsl:when test='/ns8:entradaConsultarDeuda/ns8:canal = "CNB" and /ns8:entradaConsultarDeuda/ns8:servicio/codigoEmpresa = "4"'>
			<rubro>
				<xsl:text disable-output-escaping="no">CCAP</xsl:text>
			</rubro>
			<servicioPerson>
				<xsl:text disable-output-escaping="no">CSBA</xsl:text>
			</servicioPerson>
		</xsl:when>
		<xsl:when test='/ns8:entradaConsultarDeuda/ns8:canal = "CNB" and /ns8:entradaConsultarDeuda/ns8:servicio/codigoEmpresa = "6"'>
			<rubro>
				<xsl:text disable-output-escaping="no">CCAM</xsl:text>
			</rubro>
			<servicioPerson>
				<xsl:text disable-output-escaping="no">CSBA</xsl:text>
			</servicioPerson>
		</xsl:when>
		<xsl:when test='/ns8:entradaConsultarDeuda/ns8:canal = "CNB" and /ns8:entradaConsultarDeuda/ns8:servicio/codigoEmpresa = "360"'>
			<rubro>
				<xsl:text disable-output-escaping="no">CCAQ</xsl:text>
			</rubro>
			<servicioPerson>
				<xsl:text disable-output-escaping="no">CSBA</xsl:text>
			</servicioPerson>
		</xsl:when>
	  </xsl:choose>		
    </mc:MensajeEntradaObtenerSaldoPendiente>
  </xsl:template>
</xsl:stylesheet>
