<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../otc-nopolicy.wsdl"/>
      <rootElement name="entradaConsultarDeuda" namespace="http://www.bolivariano.com/ws/OTCService"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../xsd/ATM/EMT_1.wsdl"/>
      <rootElement name="MensajeEntradaConsultar" namespace="http://www.bolivariano.com/MensajeEMT"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 130301.0647.0008) AT [FRI MAY 18 21:10:18 COT 2018]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:ns11="http://www.bolivariano.com/ws/EMT/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:ns1="http://www.bolivariano.com/dominio/DatoAdicional"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:ns14="http://www.bolivariano.com/CoreBB"
                xmlns:ns16="http://www.bolivariano.com/Cuenta"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns5="http://www.bolivariano.com/dominio/Convenio"
                xmlns:ns6="http://www.bolivariano.com/dominio/Recibo"
                xmlns:ns10="http://www.bolivariano.com/dominio/ListaSeleccion"
                xmlns:ns9="http://www.bolivariano.com/dominio/RegionalArea"
                xmlns:ns0="http://www.bolivariano.com/dominio/Servicio"
                xmlns:ns12="http://www.bolivariano.com/MensajeBolivariano"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:ns17="http://www.bolivariano.com/Recaudo"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:xsd1="http://www.bolivariano.com/MensajeEMT"
                xmlns:ns2="http://www.bolivariano.com/dominio/TipoMatriculacion"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:ns3="http://www.bolivariano.com/dominio/FormaPago"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns4="http://www.bolivariano.com/dominio/TipoIdentificador"
                xmlns:tns="http://www.bolivariano.com/ws/OTCService"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:ns13="http://www.bolivariano.com/EMT"
                xmlns:ns15="http://www.bolivariano.com/Producto"
                xmlns:ns18="http://www.bolivariano.com/Cliente"
                xmlns:ns7="http://www.bolivariano.com/dominio/Empresa"
                xmlns:ns8="http://www.bolivariano.com/mensaje/MensajeOTC"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl ns1 soap wsdl ns5 ns6 ns10 ns9 ns0 ns2 ns3 ns4 tns xsd ns7 ns8 ns11 ns14 ns16 ns12 ns17 xsd1 ns13 ns15 ns18 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap">
  <xsl:template match="/">
    <xsd1:MensajeEntradaConsultar>
      <canal>
        <xsl:value-of select="/ns8:entradaConsultarDeuda/ns8:canal"/>
      </canal>
      <depuracion>
        <xsl:text disable-output-escaping="no">N</xsl:text>
      </depuracion>
      <oficina>
        <xsl:value-of select='/ns8:entradaConsultarDeuda/ns8:servicio/datosAdicionales/datoAdicional[codigo = "s_ofi"]/valor'/>
      </oficina>
      <terminal>
        <!-- TODO quemado  -->
        <xsl:value-of select='/ns8:entradaConsultarDeuda/ns8:servicio/datosAdicionales/datoAdicional[codigo = "s_term"]/valor'/>
      </terminal>
      <transaccion>
        <xsl:text disable-output-escaping="no">62332</xsl:text>
      </transaccion>
      <usuario>
        <xsl:value-of select='/ns8:entradaConsultarDeuda/ns8:servicio/datosAdicionales/datoAdicional[codigo = "s_user"]/valor'/>
      </usuario>
      <emt>
        <empresa>
          <xsl:value-of select="/ns8:entradaConsultarDeuda/ns8:servicio/codigoEmpresa"/>
        </empresa>
        <cuenta>
          <xsl:choose>
            <xsl:when test='/ns8:entradaConsultarDeuda/ns8:servicio/codigoConvenio = "SOL"'>
              <idSolicitud>
                <xsl:value-of select="/ns8:entradaConsultarDeuda/ns8:servicio/identificador"/>
              </idSolicitud>
            </xsl:when>
            <xsl:when test='/ns8:entradaConsultarDeuda/ns8:servicio/codigoConvenio != "SOL"'>
              <idSolicitud>
                <xsl:text disable-output-escaping="no">0</xsl:text>
              </idSolicitud>
            </xsl:when>
          </xsl:choose>
          <serviPerson>
            <xsl:value-of select="/ns8:entradaConsultarDeuda/ns8:servicio/codigoConvenio"/>
          </serviPerson>
        </cuenta>
        <banco>
          <!-- TODO quemado  -->
          <xsl:text disable-output-escaping="no">BBO</xsl:text>
        </banco>
        <xsl:if test='/ns8:entradaConsultarDeuda/ns8:servicio/codigoTipoIdentificador = "PLACA"'>
          <placa>
            <xsl:value-of select="/ns8:entradaConsultarDeuda/ns8:servicio/identificador"/>
          </placa>
        </xsl:if>
        <provincia>
          <!-- TODO quemado  -->
          <xsl:text disable-output-escaping="no">GUA</xsl:text>
        </provincia>
        <sucursal>
          <!-- TODO quemado  -->
          <xsl:text disable-output-escaping="no">200</xsl:text>
        </sucursal>
      </emt>
      <cliente>
        <identificaciones>
          <xsl:if test='/ns8:entradaConsultarDeuda/ns8:servicio/codigoConvenio != "SOL"'>
            <xsl:if test='/ns8:entradaConsultarDeuda/ns8:servicio/codigoTipoIdentificador != "PLACA"'>
              <identificacion>
                <xsl:value-of select="/ns8:entradaConsultarDeuda/ns8:servicio/identificador"/>
              </identificacion>
              <tipoIdentificacion>
                <xsl:value-of select="/ns8:entradaConsultarDeuda/ns8:servicio/codigoTipoIdentificador"/>
              </tipoIdentificacion>
            </xsl:if>
          </xsl:if>
        </identificaciones>
      </cliente>
      <informacionCore>
        <!-- TODO enriquecer  parámetros cobis  -->
        <login>
          <xsl:text disable-output-escaping="no">26451</xsl:text>
        </login>
        <rolBPM>
          <xsl:value-of select='/ns8:entradaConsultarDeuda/ns8:servicio/datosAdicionales/datoAdicional[codigo = "s_rol"]/valor'/>
        </rolBPM>
        <secuencial>
          <xsl:value-of select='/ns8:entradaConsultarDeuda/ns8:servicio/datosAdicionales/datoAdicional[codigo = "s_ssn"]/valor'/>
        </secuencial>
        <servidor>
          <xsl:value-of select='/ns8:entradaConsultarDeuda/ns8:servicio/datosAdicionales/datoAdicional[codigo = "s_srv"]/valor'/>
        </servidor>
      </informacionCore>
      <xsl:if test="/ns8:entradaConsultarDeuda/ns8:canal = 'CNB'">
        <CNB>
          <empresa>
            <xsl:value-of select="/ns8:entradaConsultarDeuda/ns8:servicio/codigoEmpresa"/>
          </empresa>
	   <tipoTransaccion>C</tipoTransaccion>         
        </CNB>
      </xsl:if>
    </xsd1:MensajeEntradaConsultar>
  </xsl:template>
</xsl:stylesheet>
