<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../xsd/ATM/EMT_1.wsdl"/>
      <rootElement name="MensajeSalidaReverso" namespace="http://www.bolivariano.com/MensajeEMT"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../otc-nopolicy.wsdl"/>
      <rootElement name="salidaEjecutarPago" namespace="http://www.bolivariano.com/ws/OTCService"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 130301.0647.0008) AT [SUN MAY 20 15:50:55 COT 2018]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:tns="http://www.bolivariano.com/ws/EMT/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:ns7="http://www.bolivariano.com/dominio/DatoAdicional"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:ns2="http://www.bolivariano.com/CoreBB"
                xmlns:ns4="http://www.bolivariano.com/Cuenta"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:java="java"
                xmlns:ns13="http://www.bolivariano.com/dominio/Convenio"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns14="http://www.bolivariano.com/dominio/Recibo"
                xmlns:ns18="http://www.bolivariano.com/dominio/ListaSeleccion"
                xmlns:ns17="http://www.bolivariano.com/dominio/RegionalArea"
                xmlns:ns9="http://www.bolivariano.com/dominio/Servicio"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:ns0="http://www.bolivariano.com/MensajeBolivariano"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:ns5="http://www.bolivariano.com/Recaudo"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:ns10="http://www.bolivariano.com/dominio/TipoMatriculacion"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:xsd1="http://www.bolivariano.com/MensajeEMT"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:ns11="http://www.bolivariano.com/dominio/FormaPago"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns12="http://www.bolivariano.com/dominio/TipoIdentificador"
                xmlns:ns8="http://www.bolivariano.com/ws/OTCService"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:ns1="http://www.bolivariano.com/EMT"
                xmlns:ns3="http://www.bolivariano.com/Producto"
                xmlns:ns15="http://www.bolivariano.com/dominio/Empresa"
                xmlns:ns6="http://www.bolivariano.com/Cliente"
                xmlns:ns16="http://www.bolivariano.com/mensaje/MensajeOTC"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl tns soap ns2 ns4 wsdl ns0 ns5 xsd1 xsd ns1 ns3 ns6 ns7 ns13 ns14 ns18 ns17 ns9 ns10 ns11 ns12 ns8 ns15 ns16 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap">
  <xsl:template match="/">
    <ns16:salidaEjecutarPago>
      <xsl:if test='/xsd1:MensajeSalidaReverso/codigoErrorRemoto != "T0000"'>
        <ns16:codigoError>
          <xsl:value-of select="/xsd1:MensajeSalidaReverso/codigoError"/>
        </ns16:codigoError>
        <ns16:mensajeUsuario>
          <xsl:value-of select="/xsd1:MensajeSalidaReverso/mensajeUsuario"/>
        </ns16:mensajeUsuario>
      </xsl:if>
      <xsl:if test='/xsd1:MensajeSalidaReverso/codigoErrorRemoto = "T0000"'>
        <ns16:datosAdicionales>
          <ns16:datoAdicional>
            <codigo>
              <xsl:text disable-output-escaping="no">secuenciaRecibo</xsl:text>
            </codigo>
            <etiqueta>
              <xsl:text disable-output-escaping="no">Numero Autorizacion ATM:</xsl:text>
            </etiqueta>
            <editable>
              <xsl:text disable-output-escaping="no">false</xsl:text>
            </editable>
            <valor>
              <xsl:value-of select="/xsd1:MensajeSalidaReverso/emt/secuenciaRecibo"/>
            </valor>
            <visible>
              <xsl:text disable-output-escaping="no">false</xsl:text>
            </visible>
          </ns16:datoAdicional>
        </ns16:datosAdicionales>
        <ns16:codigoError>0</ns16:codigoError>
        <ns16:mensajeUsuario>
          <xsl:value-of select="/xsd1:MensajeSalidaReverso/mensajeUsuario"/>
        </ns16:mensajeUsuario>
        <ns16:fechaPago>
          <xsl:value-of select="/xsd1:MensajeSalidaReverso/emt/fechaContable"/>
        </ns16:fechaPago>
        <ns16:fechaDebito>
          <xsl:value-of select='java:format(java:text.SimpleDateFormat.new("yyyy-MM-dd&apos;T&apos;HH:mm:ss.SSS"), java:util.Date.new())'/>
        </ns16:fechaDebito>
        <ns16:referencia>
          <xsl:value-of select="/xsd1:MensajeSalidaReverso/informacionCore/secuencial"/>
        </ns16:referencia>
      </xsl:if>
    </ns16:salidaEjecutarPago>
  </xsl:template>
</xsl:stylesheet>
