<?oracle-xsl-mapper <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->

<mapSources>

   <source type="WSDL">

      <schema location="../otc-nopolicy.wsdl"/>

      <rootElement name="entradaEjecutarPago" namespace="http://www.bolivariano.com/ws/OTCService"/>

   </source>

</mapSources>

<mapTargets>

   <target type="WSDL">

      <schema location="../xsd/ATM/EMT_1.wsdl"/>

      <rootElement name="MensajeEntradaPago" namespace="http://www.bolivariano.com/MensajeEMT"/>

   </target>

</mapTargets>

<!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 130301.0647.0008) AT [SUN MAY 20 15:02:12 COT 2018]. -->?>
<xsl:stylesheet version="1.0" exclude-result-prefixes="xsi xsl ns1 soap wsdl ns5 ns6 ns10 ns9 ns0 ns2 ns3 ns4 tns xsd ns7 ns8 ns11 ns14 ns16 ns12 ns17 xsd1 ns13 ns15 ns18 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap"
   xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
   xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
   xmlns:ns11="http://www.bolivariano.com/ws/EMT/"
   xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
   xmlns:ns1="http://www.bolivariano.com/dominio/DatoAdicional"
   xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
   xmlns:ns14="http://www.bolivariano.com/CoreBB"
   xmlns:ns16="http://www.bolivariano.com/Cuenta"
   xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
   xmlns:ora="http://schemas.oracle.com/xpath/extension"
   xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
   xmlns:ns5="http://www.bolivariano.com/dominio/Convenio"
   xmlns:ns6="http://www.bolivariano.com/dominio/Recibo"
   xmlns:ns10="http://www.bolivariano.com/dominio/ListaSeleccion"
   xmlns:ns9="http://www.bolivariano.com/dominio/RegionalArea"
   xmlns:ns0="http://www.bolivariano.com/dominio/Servicio"
   xmlns:ns12="http://www.bolivariano.com/MensajeBolivariano"
   xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
   xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
   xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
   xmlns:ns17="http://www.bolivariano.com/Recaudo"
   xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
   xmlns:xsd1="http://www.bolivariano.com/MensajeEMT"
   xmlns:ns2="http://www.bolivariano.com/dominio/TipoMatriculacion"
   xmlns:med="http://schemas.oracle.com/mediator/xpath"
   xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
   xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
   xmlns:ns3="http://www.bolivariano.com/dominio/FormaPago"
   xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
   xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
   xmlns:ns4="http://www.bolivariano.com/dominio/TipoIdentificador"
   xmlns:tns="http://www.bolivariano.com/ws/OTCService"
   xmlns:xsd="http://www.w3.org/2001/XMLSchema"
   xmlns:ns13="http://www.bolivariano.com/EMT"
   xmlns:ns15="http://www.bolivariano.com/Producto"
   xmlns:ns18="http://www.bolivariano.com/Cliente"
   xmlns:ns7="http://www.bolivariano.com/dominio/Empresa"
   xmlns:ns8="http://www.bolivariano.com/mensaje/MensajeOTC"
   xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap">
   <xsl:template match="/">
      <xsd1:MensajeEntradaPago>
         <canal>
            <xsl:value-of select="/ns8:entradaEjecutarPago/ns8:canal"/>
         </canal>
         <oficina>
            <xsl:value-of select="/ns8:entradaEjecutarPago/ns8:datosAdicionales/ns8:datoAdicional[codigo = &quot;s_ofi&quot;]/valor"/>
         </oficina>
         <terminal>
            <xsl:value-of select="/ns8:entradaEjecutarPago/ns8:datosAdicionales/ns8:datoAdicional[codigo = &quot;s_term&quot;]/valor"/>
         </terminal>
         <transaccion>
            <xsl:text disable-output-escaping="no">62334</xsl:text>
         </transaccion>
         <usuario>
            <xsl:value-of select="/ns8:entradaEjecutarPago/ns8:datosAdicionales/ns8:datoAdicional[codigo = &quot;s_user&quot;]/valor"/>
         </usuario>
         <emt>
            <aplicativoCobis>
               <xsl:text disable-output-escaping="no">N</xsl:text>
            </aplicativoCobis>
            <autorizacion>
               <xsl:text disable-output-escaping="no">N</xsl:text>
            </autorizacion>
            <cantidadCheque>
               <xsl:text disable-output-escaping="no">0</xsl:text>
            </cantidadCheque>
            <chequeComision>
               <xsl:text disable-output-escaping="no">0</xsl:text>
            </chequeComision>
            <xsl:choose>
               <xsl:when test="/ns8:entradaEjecutarPago/ns8:canal = 'CNB'">
                  <xsl:if test="/ns8:entradaEjecutarPago/ns8:datosAdicionales/ns8:datoAdicional[codigo = &quot;p_forma_pago&quot;]/valor = 'EFE'">
                     <efectivo>
                        <xsl:value-of select="/ns8:entradaEjecutarPago/ns8:valorPago"/>
                     </efectivo>
                     <efectivoComision>
                        <xsl:value-of select="/ns8:entradaEjecutarPago/ns8:valorComision"/>
                     </efectivoComision>
                  </xsl:if>
                  <xsl:if test="/ns8:entradaEjecutarPago/ns8:datosAdicionales/ns8:datoAdicional[codigo = &quot;p_forma_pago&quot;]/valor = 'DEB'">
                     <debito>
                        <xsl:value-of select="/ns8:entradaEjecutarPago/ns8:valorPago"/>
                     </debito>
                     <debitoComision>
                        <xsl:value-of select="/ns8:entradaEjecutarPago/ns8:valorComision"/>
                     </debitoComision>
                  </xsl:if>
               </xsl:when>
               <xsl:otherwise>
                  <!-- PAGO TC -->
                  <xsl:choose>
                     <xsl:when test='/ns8:entradaEjecutarPago/ns8:datosAdicionales/ns8:datoAdicional[codigo = "MPA_TC"]'>
                        <debito>
                           <xsl:text disable-output-escaping="no">0.00</xsl:text>
                        </debito>
                        <debitoComision>
                           <xsl:value-of select="/ns8:entradaEjecutarPago/ns8:valorComision"/>
                        </debitoComision>
                        <efectivo>
                           <xsl:text disable-output-escaping="no">0.00</xsl:text>
                        </efectivo>
                        <efectivoComision>
                           <xsl:text disable-output-escaping="no">0.00</xsl:text>
                        </efectivoComision>
                     </xsl:when>
                     <xsl:otherwise>
                        <debito>
                           <xsl:value-of select="/ns8:entradaEjecutarPago/ns8:valorPago"/>
                        </debito>
                        <debitoComision>
                           <xsl:value-of select="/ns8:entradaEjecutarPago/ns8:valorComision"/>
                        </debitoComision>
                        <efectivo>0.00</efectivo>
                        <efectivoComision>0.00</efectivoComision>
                     </xsl:otherwise>
                  </xsl:choose>
                  <!-- PAGO TC -->
               </xsl:otherwise>

            </xsl:choose>
            <empresa>
               <xsl:choose>
                  <xsl:when test="/ns8:entradaEjecutarPago/ns8:canal = 'CNB'">
                     <xsl:value-of select="/ns8:entradaEjecutarPago/ns8:datosAdicionales/ns8:datoAdicional[codigo = &quot;p_codigoEmpresa&quot;]/valor"/>
                  </xsl:when>
                  <xsl:otherwise>
                     <xsl:value-of select="/ns8:entradaEjecutarPago/ns8:servicio/codigoEmpresa"/>
                  </xsl:otherwise>
               </xsl:choose>
            </empresa>
            <tipoMoneda>
               <xsl:text disable-output-escaping="no">1</xsl:text>
            </tipoMoneda>
            <xsl:choose>
               <xsl:when test="/ns8:entradaEjecutarPago/ns8:servicio/codigoConvenio = &quot;SOL&quot;">
                  <servicioPersona>
                     <xsl:text disable-output-escaping="no">TRAMITES</xsl:text>
                  </servicioPersona>
               </xsl:when>
               <xsl:when test="/ns8:entradaEjecutarPago/ns8:servicio/codigoConvenio = &quot;CIT&quot;">
                  <servicioPersona>
                     <xsl:text disable-output-escaping="no">CITACIONES</xsl:text>
                  </servicioPersona>
               </xsl:when>
               <xsl:when test="/ns8:entradaEjecutarPago/ns8:servicio/codigoConvenio = &quot;REN&quot;">
                  <servicioPersona>
                     <xsl:text disable-output-escaping="no">RENOVACION</xsl:text>
                  </servicioPersona>
               </xsl:when>
            </xsl:choose>
            <totalComision>
               <xsl:value-of select="/ns8:entradaEjecutarPago/ns8:valorComision"/>
            </totalComision>
            <ubicacion>
               <xsl:text disable-output-escaping="no">103</xsl:text>
            </ubicacion>
            <valorImpuesto>
               <xsl:text disable-output-escaping="no">N</xsl:text>
            </valorImpuesto>
            <valorTotalCancelar>
               <!--<xsl:choose>
      <xsl:when test='/ns8:entradaEjecutarPago/ns8:servicio/codigoConvenio = "SOL"'>
          <xsl:value-of select="/ns8:entradaEjecutarPago/ns8:valorPago"/>
       </xsl:when>
       <xsl:when test='/ns8:entradaEjecutarPago/ns8:servicio/codigoConvenio != "SOL"'>-->
               <!--<xsl:value-of select="/ns8:entradaEjecutarPago/ns8:valorPago * 100"/>-->
               <xsl:value-of select="format-number(/ns8:entradaEjecutarPago/ns8:valorPago * 100, '0')"/>
               <!--</xsl:when>
      </xsl:choose>-->
            </valorTotalCancelar>
            <cuenta>
               <cuenta>
                  <xsl:value-of select="/ns8:entradaEjecutarPago/ns8:cuenta"/>
               </cuenta>
               <idCliente>
                  <xsl:value-of select="/ns8:entradaEjecutarPago/ns8:servicio/identificador"/>
               </idCliente>
               <xsl:if test="/ns8:entradaEjecutarPago/ns8:servicio/codigoConvenio">
                  <idSolicitud>
                     <xsl:if test="/ns8:entradaEjecutarPago/ns8:servicio/codigoConvenio = &quot;SOL&quot;">
                        <xsl:value-of select="/ns8:entradaEjecutarPago/ns8:servicio/identificador"/>
                     </xsl:if>
                     <xsl:if test="/ns8:entradaEjecutarPago/ns8:servicio/codigoConvenio = &quot;REN&quot;">
                        <xsl:value-of select="/ns8:entradaEjecutarPago/ns8:datosAdicionales/ns8:datoAdicional[codigo = &quot;idSolicitud&quot;]/valor"/>
                     </xsl:if>
                     <xsl:if test="/ns8:entradaEjecutarPago/ns8:servicio/codigoConvenio != &quot;SOL&quot; and /ns8:entradaEjecutarPago/ns8:servicio/codigoConvenio != &quot;REN&quot;">
                        <xsl:text disable-output-escaping="no">0</xsl:text>
                     </xsl:if>
                  </idSolicitud>
               </xsl:if>
               <tipoCuenta>
                  <xsl:value-of select="/ns8:entradaEjecutarPago/ns8:tipoCuenta"/>
               </tipoCuenta>
               <xsl:choose>
                  <xsl:when test="/ns8:entradaEjecutarPago/ns8:servicio/codigoConvenio = &quot;SOL&quot;">
                     <servicio>
                        <xsl:text disable-output-escaping="no">1</xsl:text>
                     </servicio>
                  </xsl:when>
                  <xsl:when test="/ns8:entradaEjecutarPago/ns8:servicio/codigoConvenio = &quot;CIT&quot;">
                     <servicio>
                        <xsl:text disable-output-escaping="no">2</xsl:text>
                     </servicio>
                  </xsl:when>
                  <xsl:when test="/ns8:entradaEjecutarPago/ns8:servicio/codigoConvenio = &quot;REN&quot;">
                     <servicio>
                        <xsl:text disable-output-escaping="no">3</xsl:text>
                     </servicio>
                  </xsl:when>
               </xsl:choose>
               <serviPerson>
                  <xsl:value-of select="/ns8:entradaEjecutarPago/ns8:servicio/codigoConvenio"/>
               </serviPerson>
               <subtotal>
                  <xsl:value-of select="/ns8:entradaEjecutarPago/ns8:valorPago"/>
               </subtotal>
               <valorTotal>
                  <xsl:value-of select="/ns8:entradaEjecutarPago/ns8:valorPago+/ns8:entradaEjecutarPago/ns8:valorComision "/>
               </valorTotal>
            </cuenta>
            <banco>
               <xsl:text disable-output-escaping="no">BBO</xsl:text>
            </banco>
            <codigoReferencia>
               <xsl:value-of select="/ns8:entradaEjecutarPago/ns8:servicio/identificador"/>
            </codigoReferencia>
            <fechaHoraTransaccion>
               <xsl:value-of select="concat(substring(/ns8:entradaEjecutarPago/ns8:fecha, 9,2),'-',substring(/ns8:entradaEjecutarPago/ns8:fecha, 6, 2),'-',substring(           /ns8:entradaEjecutarPago/ns8:fecha, 1, 4),' ',substring(/ns8:entradaEjecutarPago/ns8:fecha, 12, 8))"/>
            </fechaHoraTransaccion>
            <xsl:if test="/ns8:entradaEjecutarPago/ns8:servicio/codigoTipoIdentificador = &quot;PLACA&quot;">
               <placa>
                  <xsl:value-of select="/ns8:entradaEjecutarPago/ns8:servicio/identificador"/>
               </placa>
            </xsl:if>
            <provincia>
               <xsl:text disable-output-escaping="no">GUA</xsl:text>
            </provincia>
            <regNacional>
               <xsl:text disable-output-escaping="no">0</xsl:text>
            </regNacional>
            <sucursal>
               <xsl:text disable-output-escaping="no">200</xsl:text>
            </sucursal>
         </emt>
         <cliente>
            <nombre>
               <xsl:value-of select="/ns8:entradaEjecutarPago/ns8:nombreCliente"/>
            </nombre>
            <representanteLegal/>
            <dependencias/>
            <representanteLegal2/>
            <malaReferencia/>
            <informacionFinanciera/>
            <garantiasPersonales/>
            <identificaciones>
               <xsl:choose>
                  <xsl:when test="/ns8:entradaEjecutarPago/ns8:servicio/codigoConvenio != &quot;SOLI&quot;">
                     <identificacion>
                        <xsl:for-each select="/ns8:entradaEjecutarPago/ns8:datosAdicionales/ns8:datoAdicional">
                           <xsl:if test="codigo = &quot;identificacion&quot;">
                              <xsl:value-of select="valor"/>
                           </xsl:if>
                        </xsl:for-each>
                     </identificacion>
                     <tipoIdentificacion>
                        <xsl:for-each select="/ns8:entradaEjecutarPago/ns8:datosAdicionales/ns8:datoAdicional">
                           <xsl:if test="codigo = &quot;tipoIdentificacion&quot;">
                              <xsl:value-of select="valor"/>
                           </xsl:if>
                        </xsl:for-each>
                     </tipoIdentificacion>
                  </xsl:when>
               </xsl:choose>
            </identificaciones>
            <tarjetas/>
            <nombramiento/>
         </cliente>
         <tipoPago>
            <xsl:text disable-output-escaping="no">M</xsl:text>
         </tipoPago>
         <informacionCore>
            <!--TODO enriquecer  parámetros cobis-->
            <fechaProcesoKernel>
               <xsl:value-of select="/ns8:entradaEjecutarPago/ns8:fecha"/>
            </fechaProcesoKernel>
            <modoCorreccion>
               <xsl:text disable-output-escaping="no">N</xsl:text>
            </modoCorreccion>
            <rolBPM>
               <xsl:value-of select="/ns8:entradaEjecutarPago/ns8:datosAdicionales/ns8:datoAdicional[codigo = &quot;s_rol&quot;]/valor"/>
            </rolBPM>
            <secuencial>
               <xsl:value-of select="/ns8:entradaEjecutarPago/ns8:datosAdicionales/ns8:datoAdicional[codigo = &quot;s_ssn&quot;]/valor"/>
            </secuencial>
            <servidor>
               <xsl:value-of select="/ns8:entradaEjecutarPago/ns8:datosAdicionales/ns8:datoAdicional[codigo = &quot;s_srv&quot;]/valor"/>
            </servidor>
         </informacionCore>
         <xsl:if test="/ns8:entradaEjecutarPago/ns8:canal = 'CNB'">
            <CNB>
               <autorizacion>
                  <xsl:value-of select="/ns8:entradaEjecutarPago/ns8:datosAdicionales/ns8:datoAdicional[codigo = 'p_autorizacionCNB']/valor"/>
               </autorizacion>
               <comercio>
                  <xsl:value-of select="/ns8:entradaEjecutarPago/ns8:datosAdicionales/ns8:datoAdicional[codigo = 'p_comercio']/valor"/>
               </comercio>
               <terminalID>
                  <xsl:value-of select="/ns8:entradaEjecutarPago/ns8:datosAdicionales/ns8:datoAdicional[codigo = 'p_terminalID']/valor"/>
               </terminalID>
               <agencia>
                  <xsl:value-of select="/ns8:entradaEjecutarPago/ns8:datosAdicionales/ns8:datoAdicional[codigo = 'p_agencia']/valor"/>
               </agencia>
               <red>
                  <xsl:value-of select="/ns8:entradaEjecutarPago/ns8:datosAdicionales/ns8:datoAdicional[codigo = 'p_red']/valor"/>
               </red>
               <secuencial>
                  <xsl:value-of select="/ns8:entradaEjecutarPago/ns8:datosAdicionales/ns8:datoAdicional[codigo = 's_ssn']/valor"/>
               </secuencial>
               <valor>
                  <xsl:value-of select="/ns8:entradaEjecutarPago/ns8:valorPago"/>
               </valor>
               <nombreCliente>
                  <xsl:value-of select='/ns8:entradaEjecutarPago/ns8:datosAdicionales/ns8:datoAdicional[codigo = "p_nombreCliente"]/valor'/>
               </nombreCliente>
               <identificacionCliente>
                  <xsl:value-of select='/ns8:entradaEjecutarPago/ns8:datosAdicionales/ns8:datoAdicional[codigo = "p_identificacionCliente"]/valor'/>
               </identificacionCliente>
               <modoCorreccion>
                  <xsl:text disable-output-escaping="no">N</xsl:text>
               </modoCorreccion>
               <tipoTransaccion>P</tipoTransaccion>
               <formaPago>
                  <xsl:value-of select='/ns8:entradaEjecutarPago/ns8:datosAdicionales/ns8:datoAdicional[codigo = "p_forma_pago"]/valor'/>
               </formaPago>
            </CNB>
         </xsl:if>
         <!-- PAGO TC -->
         <xsl:if test='/ns8:entradaEjecutarPago/ns8:datosAdicionales/ns8:datoAdicional[codigo = "MPA_TC"]'>
            <formaPago>
               <tarjeta>
                  <tarjeta>
                     <xsl:value-of select='/ns8:entradaEjecutarPago/ns8:datosAdicionales/ns8:datoAdicional[codigo = "MPA_TC"]/valor'/>
                  </tarjeta>
                  <valor>
                     <xsl:value-of select="/ns8:entradaEjecutarPago/ns8:valorPago"/>
                  </valor>
                  <valorComision>
                     <xsl:value-of select="/ns8:entradaEjecutarPago/ns8:valorComision"/>
                  </valorComision>
                  <mesesDiferido>
                     <xsl:value-of select='/ns8:entradaEjecutarPago/ns8:datosAdicionales/ns8:datoAdicional[codigo = "FPA_TC"]/valor'/>
                  </mesesDiferido>
               </tarjeta>
            </formaPago>
         </xsl:if>

         <codigoComercio>
            <xsl:choose>
               <xsl:when test="/ns8:entradaEjecutarPago/ns8:canal = 'VEN'">
                  <xsl:text disable-output-escaping="no">2006593</xsl:text>
               </xsl:when>
               <xsl:when test="/ns8:entradaEjecutarPago/ns8:canal = 'IBK'">
                  <xsl:text disable-output-escaping="no">2006590</xsl:text>
               </xsl:when>
               <xsl:when test="/ns8:entradaEjecutarPago/ns8:canal = 'WAP'">
                  <xsl:text disable-output-escaping="no">2006591</xsl:text>
               </xsl:when>
               <xsl:when test="/ns8:entradaEjecutarPago/ns8:canal = 'SAT'">
                  <xsl:text disable-output-escaping="no">2006594</xsl:text>
               </xsl:when>
               <xsl:otherwise>
                  <xsl:text disable-output-escaping="no">2006594</xsl:text>
               </xsl:otherwise>
            </xsl:choose>
         </codigoComercio>
         <!-- PAGO TC -->
      </xsd1:MensajeEntradaPago>
   </xsl:template>
</xsl:stylesheet>
