<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:tns="http://www.bolivariano.com/mensaje/MensajeOTC" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:ns0="http://www.bolivariano.com/MensajeCredimatic" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction"
                xmlns:ns2="http://www.bolivariano.com/CoreBB" xmlns:mbl="http://www.bolivariano.com/MensajeBolivariano"                xmlns:ns3="http://www.bolivariano.com/Recaudo" xmlns:ns4="http://www.bolivariano.com/Cuenta"
                xmlns:ns1="http://www.bolivariano.com/Producto"
                xmlns:pre="http://www.bolivariano.com/PagoRapidoEfectivo"
                xmlns:ns5="http://www.bolivariano.com/Cliente"
                xmlns:ns8="http://www.bolivariano.com/dominio/RegionalArea"
                xmlns:ns11="http://www.bolivariano.com/dominio/Recibo"
                xmlns:ns6="http://www.bolivariano.com/dominio/DatoAdicional"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:ns15="http://www.bolivariano.com/mensaje/MensajeOTC"
                xmlns:ns7="http://www.bolivariano.com/dominio/ListaSeleccion"
                xmlns:ns9="http://www.bolivariano.com/dominio/Servicio"
                xmlns:ns10="http://www.bolivariano.com/dominio/TipoIdentificador"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns12="http://www.bolivariano.com/dominio/Empresa"
                xmlns:ns13="http://www.bolivariano.com/dominio/TipoMatriculacion"
                xmlns:ns14="http://www.bolivariano.com/dominio/Convenio"
                xmlns:ns16="http://www.bolivariano.com/dominio/FormaPago"
                xmlns:ns17="http://www.bolivariano.com/MensajeCredimatic"> <xsl:output indent="yes"/>
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../MensajesCanonicos/MensajeCredimatic.xsd"/>
            <oracle-xsl-mapper:rootElement name="MensajeSalidaPagarAvanceEfectivo" namespace="http://www.bolivariano.com/MensajeCredimatic"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../otc.wsdl"/>
            <oracle-xsl-mapper:rootElement name="salidaEjecutarPago" namespace="http://www.bolivariano.com/mensaje/MensajeOTC"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [WED DEC 08 12:14:55 COT 2021].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:variable name="valor"/>
   <xsl:template match="/">
      <tns:salidaEjecutarPago>
         <ns15:codigoError>
            <xsl:value-of select="/ns17:MensajeSalidaPagarAvanceEfectivo/codigoError"/>
         </ns15:codigoError>
         <ns15:datosAdicionales>
            <!-- <ns16:datoAdicional>
               <codigo>autorizacion</codigo>
               <valor>
                  <xsl:value-of select="/ns0:MensajeSalidaPagarAvanceEfectivo/informacionAvanceEfectivo/autorizacion"/>
               </valor>
            </ns16:datoAdicional> -->
    		<ns15:datoAdicional>
               <codigo>tipoAvance</codigo>
               <valor>
                  <xsl:value-of select="/ns0:MensajeSalidaPagarAvanceEfectivo/informacionAvanceEfectivo/tipoAvance"/>
               </valor>
            </ns15:datoAdicional>
			<ns15:datoAdicional>
               <codigo>mesesDiferido</codigo>
               <valor>
                  <xsl:value-of select="/ns0:MensajeSalidaPagarAvanceEfectivo/informacionAvanceEfectivo/mesesDiferido"/>
               </valor>
            </ns15:datoAdicional>
			<ns15:datoAdicional>
               <codigo>fechaContable</codigo>
               <valor>
                  <!-- <xsl:value-of select="/ns0:MensajeSalidaPagarAvanceEfectivo/informacionAvanceEfectivo/Recaudo/fechaContable"/> -->
                  <xsl:value-of select="concat(substring(/ns0:MensajeSalidaPagarAvanceEfectivo/informacionAvanceEfectivo/Recaudo/fechaContable, 9,2),'/',substring(/ns0:MensajeSalidaPagarAvanceEfectivo/informacionAvanceEfectivo/Recaudo/fechaContable, 6, 2),'/',substring(/ns0:MensajeSalidaPagarAvanceEfectivo/informacionAvanceEfectivo/Recaudo/fechaContable, 1, 4))"/>
               </valor>
            </ns15:datoAdicional>
			<ns15:datoAdicional>
               <codigo>fechaEfectiva</codigo>
               <valor>
                  <xsl:value-of select="/ns0:MensajeSalidaPagarAvanceEfectivo/informacionAvanceEfectivo/Recaudo/fechaEfectiva"/>
               </valor>
            </ns15:datoAdicional>
						<ns15:datoAdicional>
               <codigo>horario</codigo>
               <valor>
                  <xsl:value-of select="/ns0:MensajeSalidaPagarAvanceEfectivo/informacionAvanceEfectivo/Recaudo/horario"/>
               </valor>
            </ns15:datoAdicional>
			<ns15:datoAdicional>
               <codigo>numeroTarjeta</codigo>
               <valor>
                  <xsl:value-of select="/ns0:MensajeSalidaPagarAvanceEfectivo/informacionAvanceEfectivo/Recaudo/numeroTarjeta"/>
               </valor>
            </ns15:datoAdicional>
			<ns15:datoAdicional>
               <codigo>valorTotalCancelar</codigo>
               <valor>
                  <xsl:value-of select="/ns0:MensajeSalidaPagarAvanceEfectivo/informacionAvanceEfectivo/Recaudo/valorTotalCancelar"/>
               </valor>
            </ns15:datoAdicional>
			<ns15:datoAdicional>
               <codigo>nombreCuenta</codigo>
               <valor>
                  <xsl:value-of select="/ns0:MensajeSalidaPagarAvanceEfectivo/informacionAvanceEfectivo/Recaudo/cuenta/nombreCuenta"/>
               </valor>
            </ns15:datoAdicional>
			<ns15:datoAdicional>
               <codigo>identificacion</codigo>
               <valor>
                  <xsl:value-of select="/ns0:MensajeSalidaPagarAvanceEfectivo/informacionAvanceEfectivo/Recaudo/cuenta/identificaciones/identificacion"/>
               </valor>
            </ns15:datoAdicional>
			<ns15:datoAdicional>
               <codigo>tipoIdentificacion</codigo>
               <valor>
                  <xsl:value-of select="/ns0:MensajeSalidaPagarAvanceEfectivo/informacionAvanceEfectivo/Recaudo/cuenta/identificaciones/tipoIdentificacion"/>
               </valor>
            </ns15:datoAdicional>
			<ns15:datoAdicional>
               <codigo>secuencial</codigo>
               <valor>
                  <xsl:value-of select="/ns0:MensajeSalidaPagarAvanceEfectivo/informacionAvanceEfectivo/CoreBB/secuencial"/>
               </valor>
            </ns15:datoAdicional>
            <ns15:datoAdicional>
               <codigo>numeroCuenta</codigo>
               <valor>
                  <xsl:value-of select="/ns0:MensajeSalidaPagarAvanceEfectivo/informacionAvanceEfectivo/Recaudo/cuenta/cuenta"/>
               </valor>
            </ns15:datoAdicional>
            <ns15:datoAdicional>
            <codigo>tipoTarjeta</codigo>
               <valor>
                  <xsl:value-of select="/ns0:MensajeSalidaPagarAvanceEfectivo/informacionAvanceEfectivo/Recaudo/cuenta/tipoTarjeta"/>
               </valor>
            </ns15:datoAdicional>
         </ns15:datosAdicionales>
         <ns15:mensajeUsuario>
            <xsl:value-of select="/ns0:MensajeSalidaPagarAvanceEfectivo/mensajeUsuario"/>
         </ns15:mensajeUsuario>
         <!-- ajmc
         <ns16:referencia>
            <xsl:value-of select="/ns0:MensajeSalidaPagarAvanceEfectivo/secuencialBPM"/>
         </ns16:referencia> -->
      </tns:salidaEjecutarPago>
   </xsl:template>
</xsl:stylesheet>