<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:tns="http://www.bolivariano.com/MensajeCredimatic" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:ns0="http://www.bolivariano.com/mensaje/MensajeOTC" xmlns:ns4="http://www.bolivariano.com/dominio/RegionalArea" xmlns:ns7="http://www.bolivariano.com/dominio/Recibo" xmlns:ns2="http://www.bolivariano.com/dominio/DatoAdicional" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns3="http://www.bolivariano.com/dominio/ListaSeleccion" xmlns:ns5="http://www.bolivariano.com/dominio/Servicio" xmlns:ns6="http://www.bolivariano.com/dominio/TipoIdentificador" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns8="http://www.bolivariano.com/dominio/Empresa" xmlns:ns9="http://www.bolivariano.com/dominio/TipoMatriculacion" xmlns:ns10="http://www.bolivariano.com/dominio/Convenio" xmlns:ns11="http://www.bolivariano.com/dominio/FormaPago" xmlns:cbb="http://www.bolivariano.com/CoreBB" xmlns:ns12="http://www.bolivariano.com/Pais" xmlns:fp="http://www.bolivariano.com/FormaPago" xmlns:ns13="http://www.bolivariano.com/Recaudo" xmlns:s1="http://www.bolivariano.com/Credimatic" xmlns:pre="http://www.bolivariano.com/Premio" xmlns:mbl="http://www.bolivariano.com/MensajeBolivariano" xmlns:ns14="http://www.bolivariano.com/Cuenta" xmlns:trjc="http://www.bolivariano.com/TarjetaCredito" xmlns:ns15="http://www.bolivariano.com/Producto" xmlns:ns16="http://www.bolivariano.com/KeyServer" xmlns:en="http://www.bolivariano.com/Enumerados" xmlns:bnc="http://www.bolivariano.com/Banco" xmlns:pref="http://www.bolivariano.com/Paginacion" xmlns:ns17="http://www.bolivariano.com/Cliente" xmlns:Q1="http://www.bolivariano.com/CNB">
   <xsl:output indent="yes"/>
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../otc.wsdl"/>
            <oracle-xsl-mapper:rootElement name="entradaEjecutarPago" namespace="http://www.bolivariano.com/ws/OTCService"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../MensajesCanonicos/MensajeCredimatic.xsd"/>
            <oracle-xsl-mapper:rootElement name="MensajeEntradaPagarAvanceEfectivo" namespace="http://www.bolivariano.com/MensajeCredimatic"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [WED DEC 08 12:13:30 COT 2021].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:MensajeEntradaPagarAvanceEfectivo>
         <canal>
            <xsl:value-of select="/ns0:entradaEjecutarPago/ns0:canal"/>
         </canal>
         <!--amaquilc adiciona campo depuracion-->
         <depuracion>
            <xsl:value-of select="/ns0:entradaEjecutarPago/ns0:depuracion"/>
         </depuracion>
         <oficina>
            <xsl:value-of select="/ns0:entradaEjecutarPago/ns0:oficina"/>
         </oficina>
         <terminal>
            <xsl:value-of select="/ns0:entradaEjecutarPago/ns0:datosAdicionales/ns0:datoAdicional[codigo = &quot;s_term&quot;]/valor"/>
         </terminal>
         <transaccion>
            <xsl:value-of select="/ns0:entradaEjecutarPago/ns0:transaccion"/>
         </transaccion>
         <usuario>
            <xsl:value-of select="/ns0:entradaEjecutarPago/ns0:datosAdicionales/ns0:datoAdicional[codigo = &quot;p_usuario&quot;]/valor"/>
         </usuario>
         <informacionAvanceEfectivo>
            <codigoTarjeta>
               <xsl:value-of select="/ns0:entradaEjecutarPago/ns0:datosAdicionales/ns0:datoAdicional[codigo = &quot;p_codigoTarjeta&quot;]/valor"/>
            </codigoTarjeta>
            <codigoTerminal>
               <xsl:value-of select="/ns0:entradaEjecutarPago/ns0:datosAdicionales/ns0:datoAdicional[codigo = &quot;s_term&quot;]/valor"/>
            </codigoTerminal>
            <!--amaquilc
              <codigoTerminal>
               <xsl:value-of select="/ns0:entradaEjecutarPago/ns0:datosAdicionales/ns0:datoAdicional[codigo = &quot;s_term&quot;]/valor"/>
            </codigoTerminal>-->
            <!--amaquilc 
            <pin>
               <xsl:value-of select="/ns0:entradaEjecutarPago/ns0:datosAdicionales/ns0:datoAdicional[codigo = &quot;p_pin&quot;]/valor"/>
            </pin>
 
            <infoBanda>
               <xsl:value-of select="/ns0:entradaEjecutarPago/ns0:datosAdicionales/ns0:datoAdicional[codigo = &quot;p_infoBanda&quot;]/valor"/>
            </infoBanda>
 
            <infoChip>
               <xsl:value-of select="/ns0:entradaEjecutarPago/ns0:datosAdicionales/ns0:datoAdicional[codigo = &quot;p_infoChip&quot;]/valor"/>
            </infoChip>-->
            <tipoMonedaCred>
               <xsl:value-of select="/ns0:entradaEjecutarPago/ns0:datosAdicionales/ns0:datoAdicional[codigo = &quot;p_tipoMonedaCred&quot;]/valor"/>
            </tipoMonedaCred>
            <tipoAvance>
               <xsl:value-of select="/ns0:entradaEjecutarPago/ns0:datosAdicionales/ns0:datoAdicional[codigo = &quot;p_tipoAvance&quot;]/valor"/>
            </tipoAvance>
            <mesesDiferido>
               <xsl:value-of select="/ns0:entradaEjecutarPago/ns0:datosAdicionales/ns0:datoAdicional[codigo = &quot;p_mesesDiferido&quot;]/valor"/>
            </mesesDiferido>
            <Recaudo>
               <autorizacion>
                  <xsl:value-of select="/ns0:entradaEjecutarPago/ns0:datosAdicionales/ns0:datoAdicional[codigo = &quot;p_autorizacion&quot;]/valor"/>
               </autorizacion>
               <codigoComercio>
                  <xsl:value-of select="/ns0:entradaEjecutarPago/ns0:datosAdicionales/ns0:datoAdicional[codigo = &quot;p_codigoComercio&quot;]/valor"/>
               </codigoComercio>
               <debito>
                  <xsl:value-of select="/ns0:entradaEjecutarPago/ns0:datosAdicionales/ns0:datoAdicional[codigo = &quot;p_debito&quot;]/valor"/>
               </debito>
               <efectivo>
                  <xsl:value-of select="/ns0:entradaEjecutarPago/ns0:datosAdicionales/ns0:datoAdicional[codigo = &quot;p_efectivo&quot;]/valor"/>
               </efectivo>
               <empresa>
                  <xsl:value-of select="/ns0:entradaEjecutarPago/ns0:datosAdicionales/ns0:datoAdicional[codigo = &quot;p_empresa&quot;]/valor"/>
               </empresa>
               <identificacion>
                  <xsl:value-of select="/ns0:entradaEjecutarPago/ns0:datosAdicionales/ns0:datoAdicional[codigo = &quot;p_identificacion&quot;]/valor"/>
               </identificacion>
               <suministro>
                  <xsl:value-of select="/ns0:entradaEjecutarPago/ns0:datosAdicionales/ns0:datoAdicional[codigo = &quot;p_cvv&quot;]/valor"/>
               </suministro>
               <tipoMoneda>
                  <xsl:value-of select="/ns0:entradaEjecutarPago/ns0:datosAdicionales/ns0:datoAdicional[codigo = &quot;p_tipoMoneda&quot;]/valor"/>
               </tipoMoneda>
               <tipoPago>
                  <xsl:value-of select="/ns0:entradaEjecutarPago/ns0:datosAdicionales/ns0:datoAdicional[codigo = &quot;p_tipoCuenta&quot;]/valor"/>
               </tipoPago>
               <ubicacion>
                  <xsl:value-of select="/ns0:entradaEjecutarPago/ns0:datosAdicionales/ns0:datoAdicional[codigo = &quot;p_ubicacion&quot;]/valor"/>
               </ubicacion>
               <valorTotalCancelar>
                  <xsl:value-of select="/ns0:entradaEjecutarPago/ns0:datosAdicionales/ns0:datoAdicional[codigo = &quot;p_valorTotalCancelar&quot;]/valor"/>
               </valorTotalCancelar>
               <!--<valorTotalCancelar>
                  <xsl:value-of select="/ns0:entradaEjecutarPago/ns0:valorPago"/>
               </valorTotalCancelar>-->
            </Recaudo>
            <CoreBB>
               <!--<modoCorreccion>
                  <xsl:value-of select="/ns0:entradaEjecutarPago/ns0:datosAdicionales/ns0:datoAdicional[codigo = &quot;p_modoCorreccion&quot;]/valor"/>
               </modoCorreccion>
               <origenTransaccion>
                  <xsl:value-of select="/ns0:entradaEjecutarPago/ns0:datosAdicionales/ns0:datoAdicional[codigo = &quot;p_origenTransaccion&quot;]/valor"/>
               </origenTransaccion>
               <rolBPM>
                  <xsl:value-of select="/ns0:entradaEjecutarPago/ns0:datosAdicionales/ns0:datoAdicional[codigo = &quot;s_rol&quot;]/valor"/>
               </rolBPM>-->
               <!--ajmc-->
               <secuencial>
                  <xsl:value-of select="/ns0:entradaEjecutarPago/ns0:datosAdicionales/ns0:datoAdicional[codigo = &quot;p_secuencialRequerimiento&quot;]/valor"/>
               </secuencial>
               <!--<servidor>
                  <xsl:value-of select="/ns0:entradaEjecutarPago/ns0:datosAdicionales/ns0:datoAdicional[codigo = &quot;s_srv&quot;]/valor"/>
               </servidor>
               <servidorLocal>
                  <xsl:value-of select="/ns0:entradaEjecutarPago/ns0:datosAdicionales/ns0:datoAdicional[codigo = &quot;s_lsrv&quot;]/valor"/>
               </servidorLocal>
               <sesion>
                  <xsl:value-of select="/ns0:entradaEjecutarPago/ns0:datosAdicionales/ns0:datoAdicional[codigo = &quot;p_sesion&quot;]/valor"/>
               </sesion>-->
            </CoreBB>
         </informacionAvanceEfectivo>
         <!--<informacionKeyserver>
            <ns16:command>
               <xsl:value-of select="/ns0:entradaEjecutarPago/ns0:datosAdicionales/ns0:datoAdicional[codigo = &quot;p_command&quot;]/valor"/>
            </ns16:command>
            <ns16:panType>
               <xsl:value-of select="/ns0:entradaEjecutarPago/ns0:datosAdicionales/ns0:datoAdicional[codigo = &quot;p_panType&quot;]/valor"/>
            </ns16:panType>
            <ns16:format>
               <xsl:value-of select="/ns0:entradaEjecutarPago/ns0:datosAdicionales/ns0:datoAdicional[codigo = &quot;p_format&quot;]/valor"/>
            </ns16:format>
            <ns16:ePin>
               <xsl:value-of select="/ns0:entradaEjecutarPago/ns0:datosAdicionales/ns0:datoAdicional[codigo = &quot;p_ePin&quot;]/valor"/>
            </ns16:ePin>
            <ns16:terminal>
               <xsl:value-of select="/ns0:entradaEjecutarPago/ns0:datosAdicionales/ns0:datoAdicional[codigo = &quot;p_keyserTerminal&quot;]/valor"/>
            </ns16:terminal>
            <ns16:type>
               <xsl:value-of select="/ns0:entradaEjecutarPago/ns0:datosAdicionales/ns0:datoAdicional[codigo = &quot;p_type&quot;]/valor"/>
            </ns16:type>
            <ns16:offset>
               <xsl:value-of select="/ns0:entradaEjecutarPago/ns0:datosAdicionales/ns0:datoAdicional[codigo = &quot;p_offset&quot;]/valor"/>
            </ns16:offset>
            <ns16:padChar>
               <xsl:value-of select="/ns0:entradaEjecutarPago/ns0:datosAdicionales/ns0:datoAdicional[codigo = &quot;p_padChar&quot;]/valor"/>
            </ns16:padChar>
            <ns16:pinLength>
               <xsl:value-of select="/ns0:entradaEjecutarPago/ns0:datosAdicionales/ns0:datoAdicional[codigo = &quot;p_pinLength&quot;]/valor"/>
            </ns16:pinLength>
            <ns16:masterKey>
               <xsl:value-of select="/ns0:entradaEjecutarPago/ns0:datosAdicionales/ns0:datoAdicional[codigo = &quot;p_masterKey&quot;]/valor"/>
            </ns16:masterKey>
 
         </informacionKeyserver>-->
         <CNB>
            <autorizacion>
               <xsl:value-of select="/ns0:entradaEjecutarPago/ns0:datosAdicionales/ns0:datoAdicional[codigo = &quot;p_autorizacionCNB&quot;]/valor"/>
            </autorizacion>
            <comercio>
               <xsl:value-of select="/ns0:entradaEjecutarPago/ns0:datosAdicionales/ns0:datoAdicional[codigo = &quot;p_comercio&quot;]/valor"/>
            </comercio>
            <terminalID>
               <xsl:value-of select="/ns0:entradaEjecutarPago/ns0:datosAdicionales/ns0:datoAdicional[codigo = &quot;p_terminalID&quot;]/valor"/>
            </terminalID>
            <agencia>
               <xsl:value-of select="/ns0:entradaEjecutarPago/ns0:datosAdicionales/ns0:datoAdicional[codigo = &quot;p_agencia&quot;]/valor"/>
            </agencia>
            <red>
               <xsl:value-of select="/ns0:entradaEjecutarPago/ns0:datosAdicionales/ns0:datoAdicional[codigo = &quot;p_red&quot;]/valor"/>
            </red>
         </CNB>
      </tns:MensajeEntradaPagarAvanceEfectivo>
   </xsl:template>
</xsl:stylesheet>