<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../xsd/Belcorp.wsdl"/>
      <rootElement name="MensajeSalidaConsultar" namespace="http://www.bolivariano.com/MensajeBelcorp"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../otc-nopolicy.wsdl"/>
      <rootElement name="salidaConsultarDeuda" namespace="http://www.bolivariano.com/ws/OTCService"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 130301.0647.0008) AT [MON JUN 04 18:04:51 COT 2018]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:tns="http://www.bolivariano.com/Belcorp/"
                xmlns:ns8="http://www.bolivariano.com/dominio/DatoAdicional"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:ns2="http://www.bolivariano.com/CoreBB"
                xmlns:ns4="http://www.bolivariano.com/Cuenta"
                xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:xsd1="http://www.bolivariano.com/MensajeBelcorp"
                xmlns:ns12="http://www.bolivariano.com/dominio/Convenio"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns14="http://www.bolivariano.com/dominio/Recibo"
                xmlns:ns19="http://www.bolivariano.com/dominio/RegionalArea"
                xmlns:ns18="http://www.bolivariano.com/dominio/ListaSeleccion"
                xmlns:ns11="http://www.bolivariano.com/dominio/Servicio"
                xmlns:ns0="http://www.bolivariano.com/Belcorp"
                xmlns:ns1="http://www.bolivariano.com/MensajeBolivariano"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:ns5="http://www.bolivariano.com/Recaudo"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:ns16="http://www.bolivariano.com/dominio/TipoMatriculacion"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:ns17="http://www.bolivariano.com/dominio/FormaPago"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns10="http://www.bolivariano.com/dominio/TipoIdentificador"
                xmlns:ns9="http://www.bolivariano.com/ws/OTCService"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:http="http://schemas.xmlsoap.org/wsdl/http/"
                xmlns:ns3="http://www.bolivariano.com/Producto"
                xmlns:ns13="http://www.bolivariano.com/dominio/Empresa"
                xmlns:ns6="http://www.bolivariano.com/Cliente"
                xmlns:ns15="http://www.bolivariano.com/mensaje/MensajeOTC"
                xmlns:ns7="http://www.bolivariano.com/Comision"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl tns soap ns2 ns4 mime wsdl xsd1 ns0 ns1 ns5 xsd http ns3 ns6 ns7 ns8 ns12 ns14 ns19 ns18 ns11 ns16 ns17 ns10 ns9 ns13 ns15 bpws xp20 bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap">
	<xsl:template match="/">
		<ns15:salidaConsultarDeuda>
			<xsl:choose>
				<xsl:when test="/xsd1:MensajeSalidaConsultar/codigoError">
					<xsl:call-template name="RespuestaError"/>
				</xsl:when>
				<xsl:otherwise>
					<xsl:call-template name="RespuestaOK"/>
				</xsl:otherwise>
			</xsl:choose>
		</ns15:salidaConsultarDeuda>
	</xsl:template>
	<xsl:template name="RespuestaError">
		<ns15:codigoError>
			<xsl:value-of select="/xsd1:MensajeSalidaConsultar/codigoError"/>
		</ns15:codigoError>
		<ns15:mensajeUsuario>
			<xsl:value-of select="/xsd1:MensajeSalidaConsultar/mensajeUsuario"/>
		</ns15:mensajeUsuario>
		<ns15:mensajeSistema>
			<xsl:value-of select="/xsd1:MensajeSalidaConsultar/mensajeSistema"/>
		</ns15:mensajeSistema>
	</xsl:template>
	<xsl:template name="RespuestaOK">
		<ns15:codigoError>
			<xsl:text disable-output-escaping="no">0</xsl:text>
		</ns15:codigoError>
		<xsl:variable name="fechaV" select="/xsd1:MensajeSalidaConsultar/informacionBelcorp/fechaLimitePago"/>
		<ns15:fechaVencimiento>
			<xsl:value-of select="concat(substring($fechaV,1,4),'-',substring($fechaV,5,2),'-',substring($fechaV,7,2) )"/> 
		</ns15:fechaVencimiento>
		<ns15:formaPago>
			<xsl:text disable-output-escaping="no">ABONO</xsl:text>
		</ns15:formaPago>

		<ns15:identificadorDeuda>
			<xsl:value-of select="/xsd1:MensajeSalidaConsultar/informacionBelcorp/codigoProcesamiento"/>
		</ns15:identificadorDeuda>
		<ns15:mensajeUsuario>TRANSACCION OK</ns15:mensajeUsuario>
		<ns15:mensajeSistema>TRANSACCION OK</ns15:mensajeSistema>
		<ns15:montoMinimo>
			<xsl:value-of select="/xsd1:MensajeSalidaConsultar/informacionBelcorp/montoMinimo div 100.0"/>
		</ns15:montoMinimo>
		<ns15:montoTotal>
			<xsl:value-of select="/xsd1:MensajeSalidaConsultar/informacionBelcorp/montoTransaccion div 100.0"/>
		</ns15:montoTotal>
		<ns15:nombreCliente>
			<xsl:value-of select="/xsd1:MensajeSalidaConsultar/informacionBelcorp/nombreRazonSocial"/>
		</ns15:nombreCliente>
		<ns15:datosAdicionales>
            <ns15:datoAdicional>
              <codigo>costoComision</codigo>
            <valor>
              <xsl:value-of select="/xsd1:MensajeSalidaConsultar/comision/costoComision"/>
            </valor>
            </ns15:datoAdicional>
        </ns15:datosAdicionales>
	</xsl:template>
</xsl:stylesheet>
