<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../otc-nopolicy.wsdl"/>
      <rootElement name="entradaConsultarDeuda" namespace="http://www.bolivariano.com/ws/OTCService"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../xsd/Belcorp.wsdl"/>
      <rootElement name="MensajeEntradaConsultar" namespace="http://www.bolivariano.com/MensajeBelcorp"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 130301.0647.0008) AT [MON JUN 04 17:52:12 COT 2018]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:ns11="http://www.bolivariano.com/Belcorp/"
                xmlns:ns1="http://www.bolivariano.com/dominio/DatoAdicional"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:ns14="http://www.bolivariano.com/CoreBB"
                xmlns:ns16="http://www.bolivariano.com/Cuenta"
                xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:xsd1="http://www.bolivariano.com/MensajeBelcorp"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:ns3="http://www.bolivariano.com/dominio/Convenio"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns5="http://www.bolivariano.com/dominio/Recibo"
                xmlns:ns10="http://www.bolivariano.com/dominio/RegionalArea"
                xmlns:ns9="http://www.bolivariano.com/dominio/ListaSeleccion"
                xmlns:ns12="http://www.bolivariano.com/Belcorp"
                xmlns:ns2="http://www.bolivariano.com/dominio/Servicio"
                xmlns:ns13="http://www.bolivariano.com/MensajeBolivariano"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:ns17="http://www.bolivariano.com/Recaudo"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:ns7="http://www.bolivariano.com/dominio/TipoMatriculacion"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:ns8="http://www.bolivariano.com/dominio/FormaPago"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns0="http://www.bolivariano.com/dominio/TipoIdentificador"
                xmlns:tns="http://www.bolivariano.com/ws/OTCService"
                xmlns:http="http://schemas.xmlsoap.org/wsdl/http/"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:ns15="http://www.bolivariano.com/Producto"
                xmlns:ns18="http://www.bolivariano.com/Cliente"
                xmlns:ns4="http://www.bolivariano.com/dominio/Empresa"
                xmlns:ns19="http://www.bolivariano.com/Comision"
                xmlns:ns6="http://www.bolivariano.com/mensaje/MensajeOTC"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl ns1 soap wsdl ns3 ns5 ns10 ns9 ns2 ns7 ns8 ns0 tns xsd ns4 ns6 ns11 ns14 ns16 mime xsd1 ns12 ns13 ns17 http ns15 ns18 ns19 bpws xp20 bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap">
  <xsl:template match="/">
    <xsd1:MensajeEntradaConsultar>
      <canal>
        <xsl:value-of select="/ns6:entradaConsultarDeuda/ns6:canal"/>
      </canal>
      <fecha>
        <xsl:value-of select='/ns6:entradaConsultarDeuda/ns6:servicio/datosAdicionales/datoAdicional[codigo = "s_date"]/valor'/>
      </fecha>
      <oficina>
        <xsl:value-of select='/ns6:entradaConsultarDeuda/ns6:servicio/datosAdicionales/datoAdicional[codigo = "s_ofi"]/valor'/>
      </oficina>
      <terminal>
        <xsl:value-of select='/ns6:entradaConsultarDeuda/ns6:servicio/datosAdicionales/datoAdicional[codigo = "s_term"]/valor'/>
      </terminal>
      <transaccion>62031</transaccion>
      <usuario>
	 <xsl:value-of select='/ns6:entradaConsultarDeuda/ns6:servicio/datosAdicionales/datoAdicional[codigo = "s_user"]/valor'/>
        <!--<xsl:value-of select="/ns6:entradaConsultarDeuda/ns6:usuario"/>-->
      </usuario>
      <informacionBelcorp>
        <aplicativoCobis>
          <xsl:text disable-output-escaping="no">N</xsl:text>
        </aplicativoCobis>
        <autorizacion>
          <xsl:text disable-output-escaping="no">N</xsl:text>
        </autorizacion>
        <empresa>
          <xsl:value-of select="/ns6:entradaConsultarDeuda/ns6:servicio/codigoEmpresa"/>
        </empresa>
        <opcion>
          <xsl:text disable-output-escaping="no">C</xsl:text>
        </opcion>
        <rubroPersona>
          <xsl:text disable-output-escaping="no">BELC</xsl:text>
        </rubroPersona>
        <servicio>
          <xsl:text disable-output-escaping="no">9</xsl:text>
        </servicio>
        <servicioPersona>
          <xsl:text disable-output-escaping="no">CSPR</xsl:text>
        </servicioPersona>
        <suministro>
          <xsl:value-of select="/ns6:entradaConsultarDeuda/ns6:servicio/identificador"/>
        </suministro>
        <tipoMoneda>
          <xsl:text disable-output-escaping="no">1</xsl:text>
        </tipoMoneda>
        <ubicacion>
          <xsl:text disable-output-escaping="no">0</xsl:text>
        </ubicacion>
        <modoInicioCanalPago>
          <xsl:text disable-output-escaping="no">010</xsl:text>
        </modoInicioCanalPago>
        <codigoCanalPago>
          <xsl:text disable-output-escaping="no">10</xsl:text>
        </codigoCanalPago>
        <codigoBanco>
          <xsl:text disable-output-escaping="no">14100001</xsl:text>
        </codigoBanco>
        <codigoInstitucion>
          <xsl:text disable-output-escaping="no">20004003</xsl:text>
        </codigoInstitucion>
        <codigoMoneda>
          <xsl:text disable-output-escaping="no">840</xsl:text>
        </codigoMoneda>
        <codigoISOPais>
          <xsl:text disable-output-escaping="no">ECU</xsl:text>
        </codigoISOPais>
      </informacionBelcorp>
      <informacionCore>
        <rol>
          <xsl:value-of select='/ns6:entradaConsultarDeuda/ns6:servicio/datosAdicionales/datoAdicional[codigo = "s_rol"]/valor'/>
        </rol>
        <secuencial>
 	  <xsl:value-of select='/ns6:entradaConsultarDeuda/ns6:servicio/datosAdicionales/datoAdicional[codigo = "s_ssn"]/valor'/>
<!--<xsl:value-of select="/ns6:entradaConsultarDeuda/ns6:secuencial"/>-->
        </secuencial>
        <servidor>
          <xsl:value-of select='/ns6:entradaConsultarDeuda/ns6:servicio/datosAdicionales/datoAdicional[codigo = "s_srv"]/valor'/>
        </servidor>
        <servidorLocal>
          <xsl:value-of select='/ns6:entradaConsultarDeuda/ns6:servicio/datosAdicionales/datoAdicional[codigo = "s_lsrv"]/valor'/>
        </servidorLocal>
      </informacionCore>
      <xsl:if test="/ns6:entradaConsultarDeuda/ns6:canal = 'CNB' ">
        <CNB>
          <tipoTransaccion>C</tipoTransaccion>
        </CNB>
      </xsl:if>
    </xsd1:MensajeEntradaConsultar>
  </xsl:template>
</xsl:stylesheet>
