<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../otc-nopolicy.wsdl"/>
      <rootElement name="entradaEjecutarReverso" namespace="http://www.bolivariano.com/ws/OTCService"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../xsd/BroadnetRecarga.wsdl"/>
      <rootElement name="MensajeEntradaReversarBroadnet" namespace="http://www.bolivariano.com/ws/BroadnetRecarga"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 130301.0647.0008) AT [THU MAY 31 11:55:00 COT 2018]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                xmlns:ns1="http://www.bolivariano.com/dominio/DatoAdicional"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:ns13="http://www.bolivariano.com/CoreBB"
                xmlns:ns15="http://www.bolivariano.com/Cuenta"
                xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:ns3="http://www.bolivariano.com/dominio/Convenio"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns5="http://www.bolivariano.com/dominio/Recibo"
                xmlns:ns19="movr:Movistar/types"
                xmlns:ns11="http://www.bolivariano.com/ws/BroadnetRecarga"
                xmlns:ns10="http://www.bolivariano.com/dominio/RegionalArea"
                xmlns:ns9="http://www.bolivariano.com/dominio/ListaSeleccion"
                xmlns:ns2="http://www.bolivariano.com/dominio/Servicio"
                xmlns:ns12="http://www.bolivariano.com/MensajeBolivariano"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:ns16="http://www.bolivariano.com/Recaudo"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:ns7="http://www.bolivariano.com/dominio/TipoMatriculacion"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:ns8="http://www.bolivariano.com/dominio/FormaPago"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns0="http://www.bolivariano.com/dominio/TipoIdentificador"
                xmlns:tns="http://www.bolivariano.com/ws/OTCService"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:ns14="http://www.bolivariano.com/Producto"
                xmlns:ns17="http://www.bolivariano.com/Cliente"
                xmlns:ns4="http://www.bolivariano.com/dominio/Empresa"
                xmlns:ns18="http://www.bolivariano.com/Broadnet"
                xmlns:ns6="http://www.bolivariano.com/mensaje/MensajeOTC"
                xmlns:wbcm="http://www.bolivariano.com/MensajeBroadnet"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl ns1 soap wsdl ns3 ns5 ns10 ns9 ns2 ns7 ns8 ns0 tns xsd ns4 ns6 soap12 ns13 ns15 mime ns19 ns11 ns12 ns16 ns14 ns17 ns18 wbcm bpws xp20 bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap">
  <xsl:template match="/">
    <wbcm:MensajeEntradaReversarBroadnet>
      <canal>
        <xsl:value-of select="/ns6:entradaEjecutarReverso/ns6:canal"/>
      </canal>
      <fecha>
        <xsl:value-of select="/ns6:entradaEjecutarReverso/ns6:fechaPago"/>
      </fecha>
      <oficina>
        <xsl:value-of select="/ns6:entradaEjecutarReverso/ns6:oficina"/>
      </oficina>
      <terminal>
        <xsl:value-of select='/ns6:entradaEjecutarReverso/ns6:datosAdicionales/ns6:datoAdicional[codigo = "s_term"]/valor'/>
      </terminal>
      <transaccion>
        <xsl:text disable-output-escaping="no">62675</xsl:text>
      </transaccion>
      <usuario>
        <xsl:value-of select="/ns6:entradaEjecutarReverso/ns6:usuario"/>
      </usuario>
      <informacionBroadnet>
        <aplicativoCobis>
          <xsl:text disable-output-escaping="no">S</xsl:text>
        </aplicativoCobis>
        <autorizacion>
          <xsl:text disable-output-escaping="no">N</xsl:text>
        </autorizacion>
        <cantidadCheque>
          <xsl:text disable-output-escaping="no">0</xsl:text>
        </cantidadCheque>
        <debito>
          <xsl:value-of select="/ns6:entradaEjecutarReverso/ns6:valorPago"/>
        </debito>
        <debitoComision>
          <xsl:value-of select="/ns6:entradaEjecutarReverso/ns6:valorComision"/>
        </debitoComision>
        <efectivo>
          <xsl:text disable-output-escaping="no">0</xsl:text>
        </efectivo>
        <empresa>
		  <xsl:value-of select="/ns6:entradaEjecutarReverso/ns6:servicio/codigoEmpresa"/>
		</empresa>
        <fechaContable>
          <xsl:value-of select="substring(/ns6:entradaEjecutarReverso/ns6:fechaPago,1,10)"/>
        </fechaContable>
        <fechaEfectiva>
          <xsl:value-of select="/ns6:entradaEjecutarReverso/ns6:fecha"/>
        </fechaEfectiva>
        <fechaEmision>
          <xsl:value-of select="/ns6:entradaEjecutarReverso/ns6:fecha"/>
        </fechaEmision>
        <nombre>
          <xsl:text disable-output-escaping="no">CONSUMIDOR FINAL</xsl:text>
        </nombre>
        <opcion>
          <xsl:text disable-output-escaping="no">P</xsl:text>
        </opcion>
        <tipoMoneda>
          <xsl:value-of select="/ns6:entradaEjecutarReverso/ns6:moneda"/>
        </tipoMoneda>
        <valorCheque>
          <xsl:text disable-output-escaping="no">0</xsl:text>
        </valorCheque>
        <valorTotalCancelar>
          <xsl:value-of select="/ns6:entradaEjecutarReverso/ns6:valorPago"/>
        </valorTotalCancelar>
        <cuenta>
          <cuenta>
            <xsl:value-of select="/ns6:entradaEjecutarReverso/ns6:cuenta"/>
          </cuenta>
          <tipoCuenta>
            <xsl:value-of select="/ns6:entradaEjecutarReverso/ns6:tipoCuenta"/>
          </tipoCuenta>
          <identificaciones>
            <identificacion>
              <xsl:value-of select="/ns6:entradaEjecutarReverso/ns6:servicio/identificador"/>
            </identificacion>
            <tipoIdentificacion>
              <xsl:value-of select="/ns6:entradaEjecutarReverso/ns6:servicio/codigoTipoIdentificador"/>
            </tipoIdentificacion>
          </identificaciones>
        </cuenta>
		<codigoProducto>
          <xsl:text disable-output-escaping="no">02</xsl:text>
        </codigoProducto>
		<numeroTelefono>
          <xsl:value-of select="/ns6:entradaEjecutarReverso/ns6:servicio/identificador"/>
        </numeroTelefono>
      </informacionBroadnet>
      <informacionCore>
        <modoCorreccion>
          <xsl:text disable-output-escaping="no">S</xsl:text>
        </modoCorreccion>
        <rolBPM>
          <xsl:value-of select='/ns6:entradaEjecutarReverso/ns6:datosAdicionales/ns6:datoAdicional[codigo = "s_rol"]/valor'/>
        </rolBPM>
        <secuencial>
          <xsl:value-of select='/ns6:entradaEjecutarReverso/ns6:datosAdicionales/ns6:datoAdicional[codigo = "s_ssn"]/valor'/>
        </secuencial>
        <secuencialRemoto>
          <xsl:value-of select="/ns6:entradaEjecutarReverso/ns6:secuencial"/>
        </secuencialRemoto>
        <servidor>
          <xsl:value-of select='/ns6:entradaEjecutarReverso/ns6:datosAdicionales/ns6:datoAdicional[codigo = "s_srv"]/valor'/>
        </servidor>
        <servidorLocal>
          <xsl:value-of select='/ns6:entradaEjecutarReverso/ns6:datosAdicionales/ns6:datoAdicional[codigo = "s_lsrv"]/valor'/>
        </servidorLocal>
      </informacionCore>
    </wbcm:MensajeEntradaReversarBroadnet>
  </xsl:template>
</xsl:stylesheet>
