<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../xsd/ServicioBroadnet.wsdl"/>
      <rootElement name="MensajeSalidaPagarBroadnet" namespace="http://www.bolivariano.com/MensajeBroadnet"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../otc-nopolicy.wsdl"/>
      <rootElement name="salidaEjecutarConsulta" namespace="http://www.bolivariano.com/ws/OTCService"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 130301.0647.0008) AT [THU MAY 31 10:13:40 COT 2018]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                xmlns:ns8="http://www.bolivariano.com/dominio/DatoAdicional"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:ns1="http://www.bolivariano.com/CoreBB"
                xmlns:ns3="http://www.bolivariano.com/Cuenta"
                xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:ns12="http://www.bolivariano.com/dominio/Convenio"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns14="http://www.bolivariano.com/dominio/Recibo"
                xmlns:ns7="movr:Broadnet/types"
                xmlns:tns="http://www.bolivariano.com/ws/BroadnetRecarga"
                xmlns:ns19="http://www.bolivariano.com/dominio/RegionalArea"
                xmlns:ns18="http://www.bolivariano.com/dominio/ListaSeleccion"
                xmlns:ns11="http://www.bolivariano.com/dominio/Servicio"
                xmlns:ns0="http://www.bolivariano.com/MensajeBolivariano"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:ns4="http://www.bolivariano.com/Recaudo"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:ns16="http://www.bolivariano.com/dominio/TipoMatriculacion"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:ns17="http://www.bolivariano.com/dominio/FormaPago"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns10="http://www.bolivariano.com/dominio/TipoIdentificador"
                xmlns:ns9="http://www.bolivariano.com/ws/OTCService"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:ns2="http://www.bolivariano.com/Producto"
                xmlns:ns13="http://www.bolivariano.com/dominio/Empresa"
                xmlns:ns5="http://www.bolivariano.com/Cliente"
                xmlns:ns15="http://www.bolivariano.com/mensaje/MensajeOTC"
                xmlns:ns6="http://www.bolivariano.com/Broadnet"
                xmlns:wbcm="http://www.bolivariano.com/MensajeBroadnet"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl soap12 soap ns1 ns3 mime wsdl ns7 tns ns0 ns4 xsd ns2 ns5 ns6 wbcm ns8 ns12 ns14 ns19 ns18 ns11 ns16 ns17 ns10 ns9 ns13 ns15 bpws xp20 bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap">
   <xsl:output indent="yes"/>
  <xsl:template match="/">
    <ns15:salidaEjecutarConsulta>
      <xsl:choose>
        <xsl:when test="/wbcm:MensajeSalidaConsultar/codigoError='0'">
          <xsl:call-template name="RespuestaOK"/>
        </xsl:when>
        <xsl:when test="/wbcm:MensajeSalidaConsultar/codigoError!='0'">
          <xsl:call-template name="RespuestaError"/>
        </xsl:when>
        <xsl:otherwise>
          <xsl:call-template name="RespuestaError"/>
        </xsl:otherwise>
      </xsl:choose>
    </ns15:salidaEjecutarConsulta>
  </xsl:template>
  <xsl:template name="RespuestaError">
      <ns15:codigoError>
        <xsl:value-of select="/wbcm:MensajeSalidaConsultar/codigoError"/>
      </ns15:codigoError>
      <ns15:mensajeUsuario>
        <xsl:value-of select="/wbcm:MensajeSalidaConsultar/mensajeUsuario"/>
      </ns15:mensajeUsuario>
       <ns15:mensajeSistema>
        <xsl:value-of select="/wbcm:MensajeSalidaConsultar/mensajeSistema"/>
      </ns15:mensajeSistema>
  </xsl:template>
  <xsl:template name="RespuestaOK">
      <ns15:codigoError>
        <xsl:value-of select="/wbcm:MensajeSalidaConsultar/codigoError"/>
      </ns15:codigoError>
      <ns15:fechaDebito>
        <xsl:value-of select="/wbcm:MensajeSalidaConsultar/informacionBroadnet/fechaEmision"/>
      </ns15:fechaDebito>
      <ns15:fechaPago>
        <xsl:value-of select="/wbcm:MensajeSalidaConsultar/informacionBroadnet/fechaContable"/>
      </ns15:fechaPago>
  
      <ns15:recibos>
        <xsl:for-each select="/wbcm:MensajeSalidaConsultar/informacionBroadnet/desgloses/desglose">
          <ns15:recibo>
            <concepto>
              <xsl:value-of select="concepto"/>
              <xsl:text disable-output-escaping="no"> </xsl:text>
            </concepto>
            <datosAdicionales>
              <datoAdicional>
                <codigo>
                  <!--xsl:text disable-output-escaping="no">codigoReferencia</xsl:text-->
                  <xsl:value-of select="codigoReferencia"/>
                </codigo>
                <valor>
                  <xsl:value-of select="valor"/>
                </valor>
              </datoAdicional>
              <datoAdicional>
                <codigo>
                  <xsl:text disable-output-escaping="no">fecha</xsl:text>
                </codigo>
                <valor>
                  <xsl:value-of select="fecha"/>
                </valor>
              </datoAdicional>
              <datoAdicional>
                <codigo>
                  <xsl:text disable-output-escaping="no">codigoProceso</xsl:text>
                </codigo>
                <valor>
                  <xsl:value-of select="codigoProceso"/>
                </valor>
              </datoAdicional>
            </datosAdicionales>
            <fecha>
              <xsl:value-of select="fecha"/>
            </fecha>
            <formaPago>
              <xsl:value-of select="formaPago"/>
            </formaPago>
            <identificador>
              <xsl:value-of select="identificador"/>
            </identificador>
            <impuesto>
              <xsl:value-of select="impuesto"/>
            </impuesto>
            <interes>
              <xsl:value-of select="interes"/>
            </interes>
            <interesesPagados>
              <xsl:value-of select="pagoInteres"/>
            </interesesPagados>
            <interesesPendientes>
              <xsl:value-of select="saldoInteres"/>
            </interesesPendientes>
            <pago>
              <xsl:value-of select="pago"/>
            </pago>
            <referencia>
              <xsl:value-of select="tipoProceso"/>
              <xsl:text disable-output-escaping="no"> </xsl:text>
              <xsl:value-of select="fecha"/>
            </referencia>
            <!--
            <referencia>
              <xsl:value-of select="codigoReferencia"/>
            </referencia> -->
            <secuencia>
              <xsl:value-of select="codigoProceso"/>
            </secuencia>
            <tipoProceso>
              <xsl:value-of select="tipoProceso"/>
            </tipoProceso>
            <totalAPagar>
              <xsl:value-of select="total"/>
            </totalAPagar>
            <valor>
              <xsl:choose>
                <xsl:when test="/wbcm:MensajeSalidaConsultar/canal = 'CNB'" >
                  <xsl:value-of select="total"/>
                </xsl:when>
                <xsl:otherwise>
                  <xsl:value-of select="valorNormal"/>  
                </xsl:otherwise>
              </xsl:choose>
              
            </valor>
          </ns15:recibo>
        </xsl:for-each>
      </ns15:recibos>
	<ns15:mensajeUsuario>TRANSACCION OK</ns15:mensajeUsuario>
	<ns15:mensajeSistema>TRANSACCION OK</ns15:mensajeSistema>
      <ns15:referencia>
        <xsl:value-of select="/wbcm:MensajeSalidaConsultar/informacionCore/secuencial"/>
      </ns15:referencia>
  </xsl:template>
</xsl:stylesheet>
