<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../otc-nopolicy.wsdl"/>
      <rootElement name="entradaEjecutarPago" namespace="http://www.bolivariano.com/ws/OTCService"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../xsd/BroadnetRecarga.wsdl"/>
      <rootElement name="MensajeEntradaPagarBroadnet" namespace="http://www.bolivariano.com/ws/BroadnetRecarga"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 130301.0647.0008) AT [THU MAY 31 17:23:53 COT 2018]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                xmlns:ns1="http://www.bolivariano.com/dominio/DatoAdicional"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:ns13="http://www.bolivariano.com/CoreBB"
                xmlns:ns15="http://www.bolivariano.com/Cuenta"
                xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:ns3="http://www.bolivariano.com/dominio/Convenio"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns5="http://www.bolivariano.com/dominio/Recibo"
                xmlns:ns19="movr:Movistar/types"
                xmlns:ns11="http://www.bolivariano.com/ws/BroadnetRecarga"
                xmlns:ns10="http://www.bolivariano.com/dominio/RegionalArea"
                xmlns:ns9="http://www.bolivariano.com/dominio/ListaSeleccion"
                xmlns:ns2="http://www.bolivariano.com/dominio/Servicio"
                xmlns:ns12="http://www.bolivariano.com/MensajeBolivariano"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:ns16="http://www.bolivariano.com/Recaudo"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:ns7="http://www.bolivariano.com/dominio/TipoMatriculacion"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:ns8="http://www.bolivariano.com/dominio/FormaPago"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns0="http://www.bolivariano.com/dominio/TipoIdentificador"
                xmlns:tns="http://www.bolivariano.com/ws/OTCService"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:ns14="http://www.bolivariano.com/Producto"
                xmlns:ns17="http://www.bolivariano.com/Cliente"
                xmlns:ns4="http://www.bolivariano.com/dominio/Empresa"
                xmlns:ns18="http://www.bolivariano.com/Broadnet"
                xmlns:ns6="http://www.bolivariano.com/mensaje/MensajeOTC"
                xmlns:wbcm="http://www.bolivariano.com/MensajeBroadnet"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl ns1 soap wsdl ns3 ns5 ns10 ns9 ns2 ns7 ns8 ns0 tns xsd ns4 ns6 soap12 ns13 ns15 mime ns19 ns12 ns16 ns14 ns17 ns18 wbcm bpws xp20 bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap">
  <xsl:template match="/">
    <wbcm:MensajeEntradaPagarBroadnet>
      <canal>
      <xsl:value-of select="/ns6:entradaEjecutarPago/ns6:canal"/>
      </canal>
      <fecha>
        <xsl:value-of select='/ns6:entradaEjecutarPago/ns6:datosAdicionales/ns6:datoAdicional[codigo = "s_date"]/valor'/>
      </fecha>
      <oficina>
        <xsl:value-of select='/ns6:entradaEjecutarPago/ns6:datosAdicionales/ns6:datoAdicional[codigo = "s_ofi"]/valor'/>
      </oficina>
      <terminal>
        <xsl:value-of select='/ns6:entradaEjecutarPago/ns6:datosAdicionales/ns6:datoAdicional[codigo = "s_term"]/valor'/>
      </terminal>
      <transaccion>
        <xsl:text disable-output-escaping="no">62675</xsl:text>
      </transaccion>
      <usuario>
        <xsl:value-of select='/ns6:entradaEjecutarPago/ns6:datosAdicionales/ns6:datoAdicional[codigo = "s_user"]/valor'/>
      </usuario>
      <informacionBroadnet>
        <aplicativoCobis>
          <xsl:text disable-output-escaping="no">N</xsl:text>
        </aplicativoCobis>
        <autorizacion>
          <xsl:text disable-output-escaping="no">S</xsl:text>
        </autorizacion>
        <cantidadCheque>
          <xsl:text disable-output-escaping="no">0</xsl:text>
        </cantidadCheque>
        <xsl:choose>
          <xsl:when test="/ns6:entradaEjecutarPago/ns6:canal = 'CNB' and (/ns6:entradaEjecutarPago/ns6:datosAdicionales/ns6:datoAdicional[codigo = 'p_forma_pago']/valor = 'DEB')">
            <debito>
              <xsl:value-of select="/ns6:entradaEjecutarPago/ns6:valorPago"/>
            </debito>
            <debitoComision>
             <xsl:value-of select="/ns6:entradaEjecutarPago/ns6:valorComision"/>
            </debitoComision>
            <efectivo>
              <xsl:text disable-output-escaping="no">0.00</xsl:text>
            </efectivo>
            <efectivoComision>
              <xsl:text disable-output-escaping="no">0.00</xsl:text>
            </efectivoComision>
          </xsl:when >
          <xsl:when test="/ns6:entradaEjecutarPago/ns6:canal = 'CNB' and (/ns6:entradaEjecutarPago/ns6:datosAdicionales/ns6:datoAdicional[codigo = 'p_forma_pago']/valor = 'EFE')">
            <debito>
              <xsl:text disable-output-escaping="no">0.00</xsl:text>
            </debito>
            <debitoComision>
              <xsl:text disable-output-escaping="no">0.00</xsl:text>
            </debitoComision>
            <efectivo>
              <xsl:value-of select="/ns6:entradaEjecutarPago/ns6:valorPago"/>
            </efectivo>
            <efectivoComision>
              <xsl:value-of select="/ns6:entradaEjecutarPago/ns6:valorComision"/>
            </efectivoComision>
          </xsl:when >
          <xsl:otherwise>
            <debito>
              <xsl:value-of select="/ns6:entradaEjecutarPago/ns6:valorPago"/>
            </debito>
            <debitoComision>
             <xsl:value-of select="/ns6:entradaEjecutarPago/ns6:valorComision"/>
            </debitoComision>
            <efectivo>
              <xsl:text disable-output-escaping="no">0</xsl:text>
            </efectivo>
          </xsl:otherwise>
        </xsl:choose>


          <xsl:choose>
              <xsl:when test="/ns6:entradaEjecutarPago/ns6:canal = 'CNB'">
                  <empresa>
                      <xsl:value-of select="/ns6:entradaEjecutarPago/ns6:servicio/codigoConvenio"/>
                  </empresa>
              </xsl:when>
              <xsl:otherwise>
                  <empresa>
                      <xsl:value-of select="/ns6:entradaEjecutarPago/ns6:servicio/codigoEmpresa"/>
                  </empresa>
              </xsl:otherwise>
          </xsl:choose>


        <fechaContable>
          <xsl:value-of select="substring(/ns6:entradaEjecutarPago/ns6:fechaPago,1,10)"/>
        </fechaContable>
        <fechaEfectiva>
          <xsl:value-of select="/ns6:entradaEjecutarPago/ns6:fecha"/>
        </fechaEfectiva>
        <fechaEmision>
          <xsl:value-of select="/ns6:entradaEjecutarPago/ns6:fecha"/>
        </fechaEmision>
        <nombre>
          <xsl:text disable-output-escaping="no">CONSUMIDOR FINAL</xsl:text>
        </nombre>
        <opcion>
          <xsl:text disable-output-escaping="no">P</xsl:text>
        </opcion>
        <tipoMoneda>
          <xsl:value-of select="/ns6:entradaEjecutarPago/ns6:moneda"/>
        </tipoMoneda>
        <valorCheque>
          <xsl:text disable-output-escaping="no">0</xsl:text>
        </valorCheque>
        <valorTotalCancelar>
          <xsl:value-of select="/ns6:entradaEjecutarPago/ns6:valorPago"/>
        </valorTotalCancelar>
        <cuenta>
          <cuenta>
            <xsl:value-of select="/ns6:entradaEjecutarPago/ns6:cuenta"/>
          </cuenta>
          <tipoCuenta>
            <xsl:value-of select="/ns6:entradaEjecutarPago/ns6:tipoCuenta"/>
          </tipoCuenta>
          <identificaciones>
            <xsl:choose>
              <xsl:when test="/ns6:entradaEjecutarPago/ns6:datosAdicionales/ns6:datoAdicional/codigo = 'C'">
                <identificacion>
                  <xsl:value-of select="/ns6:entradaEjecutarPago/ns6:datosAdicionales/ns6:datoAdicional/valor"/>
                </identificacion>
                <tipoIdentificacion>
                  <xsl:value-of select="/ns6:entradaEjecutarPago/ns6:datosAdicionales/ns6:datoAdicional/codigo"/>
                </tipoIdentificacion>
              </xsl:when>
              <xsl:otherwise>
                <identificacion>0009999999999</identificacion>
                <tipoIdentificacion>C</tipoIdentificacion>
              </xsl:otherwise>
            </xsl:choose>
          </identificaciones>
        </cuenta>
		<codigoProducto>
          <xsl:text disable-output-escaping="no">02</xsl:text>
        </codigoProducto>
        <numeroTelefono>
          <xsl:value-of select="/ns6:entradaEjecutarPago/ns6:servicio/identificador"/>
        </numeroTelefono>
      </informacionBroadnet>
      <informacionCore>
        <modoCorreccion>
          <xsl:text disable-output-escaping="no">N</xsl:text>
        </modoCorreccion>
        <rolBPM>
          <xsl:value-of select='/ns6:entradaEjecutarPago/ns6:datosAdicionales/ns6:datoAdicional[codigo = "s_rol"]/valor'/>
        </rolBPM>
        <secuencial>
          <xsl:value-of select='/ns6:entradaEjecutarPago/ns6:datosAdicionales/ns6:datoAdicional[codigo = "s_ssn"]/valor'/>
        </secuencial>
        <secuencialRemoto>
          <xsl:value-of select="/ns6:entradaEjecutarPago/ns6:secuencial"/>
        </secuencialRemoto>
        <servidor>
          <xsl:value-of select='/ns6:entradaEjecutarPago/ns6:datosAdicionales/ns6:datoAdicional[codigo = "s_srv"]/valor'/>
        </servidor>
		<servidorLocal>
          <xsl:value-of select='/ns6:entradaEjecutarPago/ns6:datosAdicionales/ns6:datoAdicional[codigo = "s_lsrv"]/valor'/>
        </servidorLocal>
      </informacionCore>
      <xsl:choose>
				<xsl:when test="/ns6:entradaEjecutarPago/ns6:canal = 'CNB'">
					<CNB>
						<autorizacion>
							<xsl:value-of select="/ns6:entradaEjecutarPago/ns6:datosAdicionales/ns6:datoAdicional[codigo = 'p_autorizacionCNB']/valor"/>
						</autorizacion>
						<comercio>
							<xsl:value-of select="/ns6:entradaEjecutarPago/ns6:datosAdicionales/ns6:datoAdicional[codigo = 'p_comercio']/valor"/>
						</comercio>
						<terminalID>
							<xsl:value-of select="/ns6:entradaEjecutarPago/ns6:datosAdicionales/ns6:datoAdicional[codigo = 'p_terminalID']/valor"/>
						</terminalID>
						<agencia>
							<xsl:value-of select="/ns6:entradaEjecutarPago/ns6:datosAdicionales/ns6:datoAdicional[codigo = 'p_agencia']/valor"/>
						</agencia>
						<red>
							<xsl:value-of select="/ns6:entradaEjecutarPago/ns6:datosAdicionales/ns6:datoAdicional[codigo = 'p_red']/valor"/>
						</red>
						<secuencial>
							<xsl:value-of select='/ns6:entradaEjecutarPago/ns6:datosAdicionales/ns6:datoAdicional[codigo = "s_ssn"]/valor'/>
						</secuencial>
						<valor>
							<xsl:value-of select="/ns6:entradaEjecutarPago/ns6:valorPago"/>
						</valor>
						<nombreCliente>
							<xsl:value-of select='/ns6:entradaEjecutarPago/ns6:datosAdicionales/ns6:datoAdicional[codigo = "p_nombreCliente"]/valor'/>
						</nombreCliente>
						<identificacionCliente>
							<xsl:value-of select='/ns6:entradaEjecutarPago/ns6:datosAdicionales/ns6:datoAdicional[codigo = "p_identificacionCliente"]/valor'/>
						</identificacionCliente>
						<modoCorreccion>
							<xsl:text disable-output-escaping="no">N</xsl:text>
						</modoCorreccion>
						<tipoTransaccion>P</tipoTransaccion>	
						 <formaPago>
							<xsl:value-of select='/ns6:entradaEjecutarPago/ns6:datosAdicionales/ns6:datoAdicional[codigo = "p_forma_pago"]/valor'/>
						</formaPago>						
					</CNB>
				</xsl:when>
			</xsl:choose>

    </wbcm:MensajeEntradaPagarBroadnet>
  </xsl:template>
</xsl:stylesheet>
