<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../otc-nopolicy.wsdl"/>
      <rootElement name="entradaConsultarDeuda" namespace="http://www.bolivariano.com/ws/OTCService"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../CEP.xsd"/>
      <rootElement name="MensajeEntradaConsultar" namespace="http://www.bolivariano.com/MensajeMunicipio"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.8(build 150622.2350.0222) AT [FRI MAY 25 12:48:54 COT 2018]. -->
?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:mmn="http://www.bolivariano.com/MensajeMunicipio"
                xmlns:ns6="http://www.bolivariano.com/mensaje/MensajeOTC"
                xmlns:java="java" exclude-result-prefixes="xsl mmn ns6">
  <xsl:template match="/">
    <mmn:MensajeEntradaConsultar>
      <canal>
        <xsl:value-of select="/ns6:entradaConsultarDeuda/ns6:canal"/>
      </canal>
      <fecha>
        <xsl:value-of select="/ns6:entradaConsultarDeuda/ns6:fecha"/>
      </fecha>
       <oficina>
        <xsl:value-of select='/ns6:entradaConsultarDeuda/ns6:servicio/datosAdicionales/datoAdicional[codigo = "s_ofi"]/valor'/>
      </oficina>
      <terminal>
        <xsl:value-of select='/ns6:entradaConsultarDeuda/ns6:servicio/datosAdicionales/datoAdicional[codigo = "s_term"]/valor'/>
      </terminal>
      <transaccion>
        <xsl:text disable-output-escaping="no">62073</xsl:text>
      </transaccion>
      <usuario>
        <xsl:value-of select='/ns6:entradaConsultarDeuda/ns6:servicio/datosAdicionales/datoAdicional[codigo = "s_user"]/valor'/>
      </usuario>
      <banred>
        <codigoOperador>
          <xsl:text disable-output-escaping="no">000000998</xsl:text>
        </codigoOperador>
         <fechaCompensacion>
         <xsl:value-of select='java:format(java:text.SimpleDateFormat.new("yyyyMMdd"), java:util.Date.new())'/>
        </fechaCompensacion>
        <fechaHoraBANRED>
          <xsl:value-of select='java:format(java:text.SimpleDateFormat.new("yyyyMMddHHmmss"), java:util.Date.new())'/>
        </fechaHoraBANRED>
        <fechaTransaccionLocal>
          <xsl:value-of select='java:format(java:text.SimpleDateFormat.new("yyyyMMdd"), java:util.Date.new())'/>
        </fechaTransaccionLocal>
        <horaTransaccionLocal>
          <xsl:value-of select='java:format(java:text.SimpleDateFormat.new("HHmmss"), java:util.Date.new())'/>
        </horaTransaccionLocal>
        <institucionAdquirente>
          <xsl:text disable-output-escaping="no">00597777</xsl:text>
        </institucionAdquirente>
        <numeroTerminal>
          <xsl:text disable-output-escaping="no">0233000000OPE998</xsl:text>
        </numeroTerminal>
        <producto>
          <xsl:text disable-output-escaping="no">0010031003</xsl:text>
        </producto>
        <secuencialAdquirente>
          <xsl:value-of select='substring(/ns6:entradaConsultarDeuda/ns6:servicio/datosAdicionales/datoAdicional[codigo = "s_ssn"]/valor,2,6)'/>
          <!--<xsl:text disable-output-escaping="no">935933</xsl:text>-->
        </secuencialAdquirente>
        <secuencialBANRED>
          <xsl:text disable-output-escaping="no">1</xsl:text>
        </secuencialBANRED>
        <xsl:choose>
         <xsl:when test="/ns6:entradaConsultarDeuda/ns6:canal ='CNB'">
						            <tipoMoneda>
          <xsl:text disable-output-escaping="no">1</xsl:text>
        </tipoMoneda>
					    	</xsl:when>
					    	<xsl:otherwise>
						   <tipoMoneda>
          <xsl:text disable-output-escaping="no">840</xsl:text>
        </tipoMoneda>
					    	</xsl:otherwise>
        </xsl:choose>
        <tipoTransaccion>
          <xsl:text disable-output-escaping="no">310000</xsl:text>
        </tipoTransaccion>
      </banred>
      <municipio>
        <opcion>
          <xsl:text disable-output-escaping="no">C</xsl:text>
        </opcion>
        <codigoComercio>
          <xsl:text disable-output-escaping="no">2245</xsl:text>
        </codigoComercio>
        <codigoProveedor>
          <xsl:value-of select="/ns6:entradaConsultarDeuda/ns6:servicio/codigoConvenio"/>
        </codigoProveedor>
        <empresa>
          <xsl:value-of select="/ns6:entradaConsultarDeuda/ns6:servicio/codigoConvenio"/>
        </empresa>
		 <xsl:choose>
          <xsl:when test='/ns6:entradaConsultarDeuda/ns6:servicio/codigoTipoIdentificador  = "01"'>
  
			  <suministro>
             <xsl:value-of select="/ns6:entradaConsultarDeuda/ns6:servicio/identificador"/>
            </suministro>
          </xsl:when>
		   </xsl:choose>
        <ubicacion>
          <xsl:text disable-output-escaping="no">0</xsl:text>
        </ubicacion>
        <cuenta>
          <servicio>
            <xsl:value-of select="/ns6:entradaConsultarDeuda/ns6:servicio/codigoTipoIdentificador"/>
          </servicio>
          <xsl:choose>
           <xsl:when test="/ns6:entradaConsultarDeuda/ns6:canal ='CNB'">
						<rubroPerson>
              <xsl:text disable-output-escaping="no">MCEP</xsl:text>
            </rubroPerson>
            <serviPerson>
              <xsl:text disable-output-escaping="no">IMPM</xsl:text>
            </serviPerson>
					 </xsl:when>
          </xsl:choose>
        </cuenta>
        <anioVigencia>9999</anioVigencia>
        <xsl:choose>
         <xsl:when test='/ns6:entradaConsultarDeuda/ns6:servicio/codigoTipoIdentificador  = "01"'>
            <!-- <suministro>
              <xsl:value-of select='substring(
              concat("0000000000",/mmn:MensajeEntradaConsultar/municipio/suministro),string-length(/mmn:MensajeEntradaConsultar/municipio/suministro) + 1.0,10.0)'/>-->
			  <codigoCanal>4</codigoCanal>
				<institucionAutorizadora>
              <xsl:text disable-output-escaping="no">0233</xsl:text>
            </institucionAutorizadora>
			</xsl:when>
          <xsl:when test='/ns6:entradaConsultarDeuda/ns6:servicio/codigoTipoIdentificador = "02"'>
            <identificacion>
              <xsl:value-of select="/ns6:entradaConsultarDeuda/ns6:servicio/identificador"/>
            </identificacion>
          </xsl:when>
          <xsl:when test='/ns6:entradaConsultarDeuda/ns6:servicio/codigoTipoIdentificador = "03"'>
            <codigoCanal>4</codigoCanal>
            <codigoPHH>
              <xsl:value-of select="substring(/ns6:entradaConsultarDeuda/ns6:servicio/identificador, 29,4)"/>
            </codigoPHH>
            <codigoPHV>
              <xsl:value-of select="substring(/ns6:entradaConsultarDeuda/ns6:servicio/identificador, 24,4)"/>
            </codigoPHV>
            <division>
              <xsl:value-of select="substring(/ns6:entradaConsultarDeuda/ns6:servicio/identificador, 19,4)"/>
            </division>
            <institucionAutorizadora>
              <xsl:text disable-output-escaping="no">0233</xsl:text>
            </institucionAutorizadora>
            <lote>
              <xsl:value-of select="substring(/ns6:entradaConsultarDeuda/ns6:servicio/identificador,14,3)"/>
            </lote>
            <manzana>
              <xsl:value-of select="substring(/ns6:entradaConsultarDeuda/ns6:servicio/identificador, 7,4)"/>
            </manzana>
            <numeroCatastral>
              <xsl:value-of select="substring(/ns6:entradaConsultarDeuda/ns6:servicio/identificador,36,1)"/>
            </numeroCatastral>
            <sector>
              <xsl:value-of select="substring(/ns6:entradaConsultarDeuda/ns6:servicio/identificador, 2,3)"/> 
            </sector>
          </xsl:when>
          <xsl:when test='/ns6:entradaConsultarDeuda/ns6:servicio/codigoTipoIdentificador = "04"'>
            <identificacion>
              <xsl:value-of select="/ns6:entradaConsultarDeuda/ns6:servicio/identificador"/>
            </identificacion>
          </xsl:when>
        </xsl:choose>
        <semestre>
          <xsl:text disable-output-escaping="no">3</xsl:text>
        </semestre>
      </municipio>
      <informacionCore>
        <rolBPM>
          <xsl:value-of select='/ns6:entradaConsultarDeuda/ns6:servicio/datosAdicionales/datoAdicional[codigo = "s_rol"]/valor'/>
        </rolBPM>
        <sec>
          <xsl:value-of select='/ns6:entradaConsultarDeuda/ns6:servicio/datosAdicionales/datoAdicional[codigo = "s_ssn"]/valor'/>
        </sec>
        <secuencial>
          <xsl:value-of select='/ns6:entradaConsultarDeuda/ns6:servicio/datosAdicionales/datoAdicional[codigo = "s_ssn"]/valor'/>
        </secuencial>
        <servidor>
          <xsl:value-of select='/ns6:entradaConsultarDeuda/ns6:servicio/datosAdicionales/datoAdicional[codigo = "s_srv"]/valor'/>
        </servidor>
      </informacionCore>
    </mmn:MensajeEntradaConsultar>
  </xsl:template>
</xsl:stylesheet>
