<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
<mapSources>
	<source type="WSDL">
		<schema location="../CEP_1.wsdl"/>
		<rootElement name="MensajeSalidaConsultar" namespace="http://www.bolivariano.com/MensajeMunicipio"/>
	</source>
</mapSources>
<mapTargets>
<target type="WSDL">
	<schema location="../otc-nopolicy.wsdl"/>
	<rootElement name="MensajeSalidaConsultarDeuda" namespace="http://www.bolivariano.com/mensaje/MensajeOTC"/>
</target>
</mapTargets>
		<!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.8(build 150622.2350.0222) AT [FRI MAY 25 16:18:59 COT 2018]. -->
		?>
<xsl:stylesheet version="1.0"
				xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
				xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
				xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
				xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
				xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
				xmlns:ns8="http://www.bolivariano.com/dominio/DatoAdicional"
				xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
				xmlns:ns1="http://www.bolivariano.com/CoreBB"
				xmlns:ns3="http://www.bolivariano.com/Cuenta"
				xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
				xmlns:ora="http://schemas.oracle.com/xpath/extension"
				xmlns:ns12="http://www.bolivariano.com/dominio/Convenio"
				xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
				xmlns:ns14="http://www.bolivariano.com/dominio/Recibo"
				xmlns:ns19="http://www.bolivariano.com/dominio/RegionalArea"
				xmlns:ns18="http://www.bolivariano.com/dominio/ListaSeleccion"
				xmlns:ns11="http://www.bolivariano.com/dominio/Servicio"
				xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
				xmlns:xsd1="http://www.bolivariano.com/MensajeMunicipio"
				xmlns:ns0="http://www.bolivariano.com/MensajeBolivariano"
				xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
				xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
				xmlns:ns4="http://www.bolivariano.com/Banred"
				xmlns:ns5="http://www.bolivariano.com/Recaudo"
				xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
				xmlns:ns16="http://www.bolivariano.com/dominio/TipoMatriculacion"
				xmlns:med="http://schemas.oracle.com/mediator/xpath"
				xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
				xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
				xmlns:ns17="http://www.bolivariano.com/dominio/FormaPago"
				xmlns:ns7="http://www.bolivariano.com/Municipio"
				xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
				xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
				xmlns:tns="http://www.bolivariano.com/ws/CEP/"
				xmlns:ns10="http://www.bolivariano.com/dominio/TipoIdentificador"
				xmlns:ns9="http://www.bolivariano.com/ws/OTCService"
				xmlns:xsd="http://www.w3.org/2001/XMLSchema"
				xmlns:ns2="http://www.bolivariano.com/Producto"
				xmlns:bpmn="http://schemas.oracle.com/bpm/xpath"
				xmlns:ns13="http://www.bolivariano.com/dominio/Empresa"
				xmlns:ns6="http://www.bolivariano.com/Cliente"
				xmlns:ns15="http://www.bolivariano.com/mensaje/MensajeOTC"
				xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
				exclude-result-prefixes="xsi xsl soap ns1 ns3 wsdl xsd1 ns0 ns4 ns5 ns7 tns xsd ns2 ns6 ns8 ns12 ns14 ns19 ns18 ns11 ns16 ns17 ns10 ns9 ns13 ns15 bpws xp20 bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref bpmn ldap">
<xsl:template match="/">
	<xsl:choose>
		<xsl:when test="/xsd1:MensajeSalidaConsultar/codigoError='00'">
			<ns15:salidaConsultarDeuda>
				<ns15:codigoError>0</ns15:codigoError>
				<ns15:mensajeUsuario>Mensaje Procesado</ns15:mensajeUsuario>
				<ns15:formaPago>TOTAL</ns15:formaPago>
				<ns15:formaPagoRecibos>UNICO_CRONOLOGICO</ns15:formaPagoRecibos>
				<ns15:datosAdicionales>
					<ns15:datoAdicional>
						<codigo>valorComision</codigo>
						<valor>
							<xsl:value-of select="format-number(/xsd1:MensajeSalidaConsultar/municipio/valorComision, '0.00')"/>
						</valor>
					</ns15:datoAdicional>
				</ns15:datosAdicionales>
				<xsl:choose>
					<xsl:when test="/xsd1:MensajeSalidaConsultar/municipio/valorTotalCancelar div 100 = '0'">
						<ns15:montoTotal>
							<xsl:value-of select="substring(/xsd1:MensajeSalidaConsultar/municipio/pagos,5,10) div 100"/>
						</ns15:montoTotal>
					</xsl:when>
					<xsl:otherwise>
						<ns15:montoTotal>
							<xsl:value-of select="/xsd1:MensajeSalidaConsultar/municipio/valorTotalCancelar div 100"/>
						</ns15:montoTotal>
					</xsl:otherwise>
				</xsl:choose>

				<ns15:nombreCliente>
					<xsl:value-of select="/xsd1:MensajeSalidaConsultar/municipio/cuenta/nombreCuenta"/>
				</ns15:nombreCliente>

				<ns15:recibos>
					<xsl:call-template name="recibo">
						<xsl:with-param name="subcadena"
										select="/xsd1:MensajeSalidaConsultar/municipio/pagos"/>
						<xsl:with-param name="subcadena2"
										select="/xsd1:MensajeSalidaConsultar/municipio/valorTotalCancelar"/>
					</xsl:call-template>
				</ns15:recibos>
			</ns15:salidaConsultarDeuda>
		</xsl:when>
		<xsl:otherwise>
			<ns15:salidaConsultarDeuda>
				<ns15:codigoError>
					<xsl:value-of select="/xsd1:MensajeSalidaConsultar/codigoError"/>
				</ns15:codigoError>
				<ns15:mensajeUsuario>
					<xsl:value-of select="/xsd1:MensajeSalidaConsultar/mensajeUsuario"/>
				</ns15:mensajeUsuario>
			</ns15:salidaConsultarDeuda>
		</xsl:otherwise>
	</xsl:choose>
</xsl:template>
<xsl:template name="recibo">
	<xsl:param name="subcadena"/>
	<xsl:param name="subcadena2"/>
	<xsl:choose>
		<xsl:when test="/xsd1:MensajeSalidaConsultar/municipio/tipoCanal!='CNB'">

			<xsl:if test="$subcadena2 div 100 = '0'">
				<ns15:recibo>
					<fecha>
						<xsl:value-of select="substring($subcadena,1,4)"/>
					</fecha>
					<totalAPagar>
						<xsl:value-of select="substring($subcadena,5,10) div 100"/>
					</totalAPagar>
				</ns15:recibo>
				<xsl:call-template name="recibo">
					<xsl:with-param name="subcadena"
									select="substring($subcadena,15,string-length($subcadena)-14)"/>
				</xsl:call-template>
			</xsl:if>
		</xsl:when>
		<xsl:when test="/xsd1:MensajeSalidaConsultar/municipio/cuic!='0' and (/xsd1:MensajeSalidaConsultar/municipio/tipoCanal='CNB')">
			<ns15:recibo>
				<fecha>
					<xsl:value-of select="substring(/xsd1:MensajeSalidaConsultar/municipio/anioVigencia,1,4)"/>
				</fecha>
				<totalAPagar>
					<xsl:value-of select="/xsd1:MensajeSalidaConsultar/municipio/valorTotalCancelar div 100"/>
				</totalAPagar>
			</ns15:recibo>
		</xsl:when>
		<xsl:when test="/xsd1:MensajeSalidaConsultar/municipio/cuic='0' and (/xsd1:MensajeSalidaConsultar/municipio/tipoCanal='CNB')">
			<ns15:recibo>
				<fecha>
					<xsl:value-of select="substring($subcadena,1,4)"/>
				</fecha>
				<totalAPagar>
					<xsl:value-of select="substring($subcadena,5,10) div 100"/>
				</totalAPagar>
			</ns15:recibo>
		</xsl:when>

	</xsl:choose>
</xsl:template>
</xsl:stylesheet>