<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
<!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
<mapSources>
    <source type="WSDL">
        <schema location="../otc-nopolicy.wsdl"/>
        <rootElement name="entradaEjecutarReverso" namespace="http://www.bolivariano.com/ws/OTCService"/>
    </source>
</mapSources>
<mapTargets>
<target type="WSDL">
    <schema location="../CEP.xsd"/>
    <rootElement name="MensajeEntradaReverso" namespace="http://www.bolivariano.com/MensajeMunicipio"/>
</target>
</mapTargets>
        <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.8(build 150622.2350.0222) AT [FRI MAY 25 16:33:28 COT 2018]. -->
        ?>
<xsl:stylesheet version="1.0"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:tns="http://www.bolivariano.com/ws/OTCService"
                xmlns:mmn="http://www.bolivariano.com/MensajeMunicipio"
                xmlns:ns6="http://www.bolivariano.com/mensaje/MensajeOTC"
                xmlns:java="java"
                exclude-result-prefixes="java ns6 tns xsl">
	<xsl:template match="/">
		<mmn:MensajeEntradaReverso>
			<canal>
				<xsl:value-of select="/ns6:entradaEjecutarReverso/ns6:canal"/>
			</canal>
			<fecha>
				<xsl:value-of select='/ns6:entradaEjecutarReverso/ns6:fecha'/>
			</fecha>
			<oficina>
				<xsl:value-of select='/ns6:entradaEjecutarReverso/ns6:oficina'/>
			</oficina>
			<terminal>
				<xsl:value-of select='/ns6:entradaEjecutarReverso/ns6:datosAdicionales/ns6:datoAdicional[codigo = "s_term"]/valor'/>
			</terminal>
			<transaccion>
				<xsl:text disable-output-escaping="no">62074</xsl:text>
			</transaccion>
			<usuario>
				<xsl:value-of select='/ns6:entradaEjecutarReverso/ns6:usuario'/>
			</usuario>
			<banred>
				<codigoOperador>
					<xsl:text disable-output-escaping="no">000005390</xsl:text>
				</codigoOperador>
				<fechaCompensacion>
					<xsl:value-of select='java:format(java:text.SimpleDateFormat.new("yyyyMMdd"), java:util.Date.new())'/>
				</fechaCompensacion>
				<fechaHoraBANRED>
					<xsl:value-of select='java:format(java:text.SimpleDateFormat.new("yyyyMMddHHmmss"), java:util.Date.new())'/>
				</fechaHoraBANRED>
				<fechaTransaccionLocal>
					<xsl:value-of select='java:format(java:text.SimpleDateFormat.new("yyyyMMdd"), java:util.Date.new())'/>
				</fechaTransaccionLocal>
				<horaTransaccionLocal>
					<xsl:value-of select='java:format(java:text.SimpleDateFormat.new("HHmmss"), java:util.Date.new())'/>
				</horaTransaccionLocal>
				<indicadorReverso>
					<xsl:text disable-output-escaping="no">02</xsl:text>
				</indicadorReverso>
				<institucionAdquirente>
					<xsl:text disable-output-escaping="no">00597777</xsl:text>
				</institucionAdquirente>
				<numeroTerminal>
					<xsl:text disable-output-escaping="no">0233000000VIRTUA</xsl:text>
				</numeroTerminal>
				<producto>
					<xsl:text disable-output-escaping="no">0010031003</xsl:text>
				</producto>
				<secuencialAdquirente>
					<xsl:value-of select='substring(/ns6:entradaEjecutarReverso/ns6:datosAdicionales/ns6:datoAdicional[codigo = "s_ssn"]/valor,2,6)'/>
				</secuencialAdquirente>
				<secuencialBANRED>
					<xsl:value-of select='substring(/ns6:entradaEjecutarReverso/ns6:datosAdicionales/ns6:datoAdicional[codigo = "s_ssn"]/valor,2,6)'/>
				</secuencialBANRED>
				<tipoMoneda>
					<xsl:text disable-output-escaping="no">840</xsl:text>
				</tipoMoneda>
				<tipoTransaccion>
					<xsl:text disable-output-escaping="no">45109M</xsl:text>
				</tipoTransaccion>
				<transaccionOriginal>
					<xsl:value-of select="/ns6:entradaEjecutarReverso/ns6:datosAdicionales/ns6:datoAdicional[codigo = 'p_codigoProveedor']/valor"/>
				</transaccionOriginal>
			</banred>
			<municipio>
				<autorizacion>
					<xsl:text disable-output-escaping="no">N</xsl:text>
				</autorizacion>
				<cantidadCheque>
					<xsl:text disable-output-escaping="no">0</xsl:text>
				</cantidadCheque>
				<chequeComision>
					<xsl:text disable-output-escaping="no">0.00</xsl:text>
				</chequeComision>
				<codigoComercio>
					<xsl:text disable-output-escaping="no">2245</xsl:text>
				</codigoComercio>
				<codigoProveedor>
					<xsl:value-of select="/ns6:entradaEjecutarReverso/ns6:servicio/codigoEmpresa"/>
				</codigoProveedor>
				<xsl:choose>
					<xsl:when test="/ns6:entradaEjecutarReverso/ns6:canal = 'CNB' and (/ns6:entradaEjecutarReverso/ns6:datosAdicionales/ns6:datoAdicional[codigo = 'p_forma_pago']/valor = 'EFE')">
						<debito>
							<xsl:text disable-output-escaping="no">0.00</xsl:text>
						</debito>
					</xsl:when>
					<xsl:when test="/ns6:entradaEjecutarReverso/ns6:canal = 'CNB' and (/ns6:entradaEjecutarReverso/ns6:datosAdicionales/ns6:datoAdicional[codigo = 'p_forma_pago']/valor = 'DEB')">
						<debito>
							<xsl:value-of select="/ns6:entradaEjecutarReverso/ns6:valorPago"/>
						</debito>
					</xsl:when>
					<xsl:otherwise>
						<debito>
							<xsl:value-of select="/ns6:entradaEjecutarReverso/ns6:valorPago"/>
						</debito>
					</xsl:otherwise>
				</xsl:choose>
				<xsl:choose>
					<xsl:when test="/ns6:entradaEjecutarReverso/ns6:canal = 'CNB' and (/ns6:entradaEjecutarReverso/ns6:datosAdicionales/ns6:datoAdicional[codigo = 'p_forma_pago']/valor = 'EFE')">
						<debitoComision>
							<xsl:text disable-output-escaping="no">0.00</xsl:text>
						</debitoComision>
					</xsl:when>
					<xsl:when test="/ns6:entradaEjecutarReverso/ns6:canal = 'CNB' and (/ns6:entradaEjecutarReverso/ns6:datosAdicionales/ns6:datoAdicional[codigo = 'p_forma_pago']/valor = 'DEB')">
						<debitoComision>
							<xsl:value-of select="/ns6:entradaEjecutarReverso/ns6:valorComision"/>
						</debitoComision>
					</xsl:when>
					<xsl:otherwise>
						<debitoComision>
							<xsl:value-of select="/ns6:entradaEjecutarReverso/ns6:valorComision"/>
						</debitoComision>
					</xsl:otherwise>
				</xsl:choose>
				<xsl:choose>
					<xsl:when test="/ns6:entradaEjecutarReverso/ns6:canal = 'CNB' and (/ns6:entradaEjecutarReverso/ns6:datosAdicionales/ns6:datoAdicional[codigo = 'p_forma_pago']/valor = 'EFE')">
						<efectivo>
							<xsl:value-of select="/ns6:entradaEjecutarReverso/ns6:valorPago"/>
						</efectivo>
					</xsl:when>
					<xsl:otherwise>
						<efectivo>
							<xsl:text disable-output-escaping="no">0.00</xsl:text>
						</efectivo>
					</xsl:otherwise>
				</xsl:choose>
				<xsl:choose>
					<xsl:when test="/ns6:entradaEjecutarReverso/ns6:canal = 'CNB' and (/ns6:entradaEjecutarReverso/ns6:datosAdicionales/ns6:datoAdicional[codigo = 'p_forma_pago']/valor = 'EFE')">
						<efectivoComision>
							<xsl:value-of select="/ns6:entradaEjecutarReverso/ns6:valorComision"/>
						</efectivoComision>
					</xsl:when>
					<xsl:otherwise>
						<efectivoComision>
							<xsl:text disable-output-escaping="no">0.00</xsl:text>
						</efectivoComision>
					</xsl:otherwise>
				</xsl:choose>
				<empresa>
					<xsl:value-of select="/ns6:entradaEjecutarReverso/ns6:servicio/codigoConvenio"/>
				</empresa>
				<nombre>
					<xsl:value-of select="/ns6:entradaEjecutarReverso/ns6:nombreCliente"/>
				</nombre>
				<numeroTarjeta>
					<xsl:text disable-output-escaping="no">0.00</xsl:text>
				</numeroTarjeta>
				<opcion>
					<xsl:text disable-output-escaping="no">T</xsl:text>
				</opcion>
				<secuencialRequerimiento>
					<xsl:value-of select='substring(/ns6:entradaEjecutarReverso/ns6:datosAdicionales/ns6:datoAdicional[codigo = "s_ssn"]/valor,2,6)'/>
				</secuencialRequerimiento>
				<xsl:choose>
					<xsl:when test='/ns6:entradaEjecutarReverso/ns6:servicio/codigoTipoIdentificador  = "01"'>

						<suministro>
							<xsl:value-of select="/ns6:entradaEjecutarReverso/ns6:servicio/identificador"/>
						</suministro>
					</xsl:when>
				</xsl:choose>
				<tipoMoneda>
					<xsl:text disable-output-escaping="no">1</xsl:text>
				</tipoMoneda>
				<xsl:choose>
					<xsl:when test='/ns6:entradaEjecutarReverso/ns6:servicio/codigoTipoIdentificador  = "01"'>
						<tipoReferencia>
							<xsl:text disable-output-escaping="no">004</xsl:text>
						</tipoReferencia>
					</xsl:when>
					<xsl:otherwise>
						<tipoReferencia>
							<xsl:text disable-output-escaping="no">001</xsl:text>
						</tipoReferencia>
					</xsl:otherwise>
				</xsl:choose>

				<ubicacion>
					<xsl:text disable-output-escaping="no">0</xsl:text>
				</ubicacion>
				<valorTotalCancelar>
					<xsl:value-of select="format-number(/ns6:entradaEjecutarReverso/ns6:valorPago,'0.00')"/>
				</valorTotalCancelar>
				<cuenta>
					<cuenta>
						<xsl:value-of select='/ns6:entradaEjecutarReverso/ns6:cuenta'/>
					</cuenta>
					<idProducto>
						<xsl:value-of select='/ns6:entradaEjecutarReverso/ns6:tipoCuenta'/>
					</idProducto>
					<tipoCuenta>
						<xsl:value-of select='/ns6:entradaEjecutarReverso/ns6:tipoCuenta'/>
					</tipoCuenta>
					<servicio>
						<xsl:value-of select="/ns6:entradaEjecutarReverso/ns6:servicio/codigoTipoIdentificador"/>
					</servicio>
				</cuenta>
				<anioVigencia>
					<!-- <xsl:text disable-output-escaping="no">9999</xsl:text>-->
					<xsl:value-of select="/ns6:entradaEjecutarReverso/ns6:recibos/ns6:recibo/fecha"/>
				</anioVigencia>
				<xsl:choose>
					<xsl:when test='/ns6:entradaEjecutarReverso/ns6:servicio/codigoTipoIdentificador  = "01"'>
						<!-- <suministro>
                      <xsl:value-of select='substring(
                      concat("0000000000",/mmn:entradaEjecutarPago/municipio/suministro), string-length(/mmn:MensajeEntradaConsultar/municipio/suministro) + 1.0,10.0)'/>
                    </suministro>-->
						<codigoCanal>4</codigoCanal>
						<institucionAutorizadora>
							<xsl:text disable-output-escaping="no">0233</xsl:text>
						</institucionAutorizadora>
					</xsl:when>
					<xsl:when test='/ns6:entradaEjecutarReverso/ns6:servicio/codigoTipoIdentificador = "02"'>
						<identificacion>
							<xsl:value-of select="/ns6:entradaEjecutarReverso/ns6:servicio/identificador"/>
						</identificacion>
					</xsl:when>
					<xsl:when test='/ns6:entradaEjecutarReverso/ns6:servicio/codigoTipoIdentificador = "03"'>
						<codigoCanal>4</codigoCanal>
						<codigoPHH>
							<xsl:value-of select="substring(/ns6:entradaEjecutarReverso/ns6:servicio/identificador, 29,4)"/>
						</codigoPHH>
						<codigoPHV>
							<xsl:value-of select="substring(/ns6:entradaEjecutarReverso/ns6:servicio/identificador, 24,4)"/>
						</codigoPHV>
						<division>
							<xsl:value-of select="substring(/ns6:entradaEjecutarReverso/ns6:servicio/identificador, 18,5)"/>
						</division>
						<institucionAutorizadora>
							<xsl:text disable-output-escaping="no">0233</xsl:text>
						</institucionAutorizadora>
						<lote>
							<xsl:value-of select="substring(/ns6:entradaEjecutarReverso/ns6:servicio/identificador,12,5)"/>
						</lote>
						<manzana>
							<xsl:value-of select="substring(/ns6:entradaEjecutarReverso/ns6:servicio/identificador, 6,5)"/>
						</manzana>
						<numeroCatastral>
							<xsl:value-of select="substring(/ns6:entradaEjecutarReverso/ns6:servicio/identificador,34,3)"/>
						</numeroCatastral>
						<sector>
							<xsl:value-of select="substring(/ns6:entradaEjecutarReverso/ns6:servicio/identificador, 1,4)"/>
						</sector>
					</xsl:when>
					<xsl:when test='/ns6:entradaEjecutarReverso/ns6:servicio/codigoTipoIdentificador = "04"'>
						<identificacion>
							<xsl:value-of select="/ns6:entradaEjecutarReverso/ns6:servicio/identificador"/>
						</identificacion>
					</xsl:when>
				</xsl:choose>
				<semestre>
					<xsl:text disable-output-escaping="no">3</xsl:text>
				</semestre>
				<xsl:if test='/ns6:entradaEjecutarPago/ns6:datosAdicionales/ns6:datoAdicional[codigo = "MPA_TC"]'>
					<formaPago>
						<tarjeta>
							<tarjeta>
								<xsl:value-of select='/ns6:entradaEjecutarReverso/ns6:datosAdicionales/ns6:datoAdicional[codigo = "MPA_TC"]/valor'/>
							</tarjeta>
							<valor>
								<xsl:value-of select="format-number(/ns6:entradaEjecutarReverso/ns6:valorPago,'0.00')"/>
							</valor>
							<valorComision>
								<xsl:value-of select="format-number(/ns6:entradaEjecutarReverso/ns6:valorComision,'0.00')"/>
							</valorComision>
							<mesesDiferido>
								<xsl:value-of select='/ns6:entradaEjecutarReverso/ns6:datosAdicionales/ns6:datoAdicional[codigo = "FPA_TC"]/valor'/>
							</mesesDiferido>
						</tarjeta>
					</formaPago>
				</xsl:if>
			</municipio>
			<informacionCore>
				<xsl:choose>
					<xsl:when test="/ns6:entradaEjecutarReverso/ns6:canal = 'CNB'">
						<modoCorreccion>
							<xsl:text disable-output-escaping="no">S</xsl:text>
						</modoCorreccion>
						<reversoTransaccion>
							<xsl:value-of select='/ns6:entradaEjecutarReverso/ns6:datosAdicionales/ns6:datoAdicional[codigo = "p_reversoTransaccion"]/valor'/>
						</reversoTransaccion>
					</xsl:when>
					<xsl:otherwise>
						<reversoTransaccion>
							<xsl:value-of select='/ns6:entradaEjecutarReverso/ns6:datosAdicionales/ns6:datoAdicional[codigo = "s_ssn_reverse"]/valor'/>
						</reversoTransaccion>
					</xsl:otherwise>
				</xsl:choose>
				<rolBPM>
					<xsl:value-of select='/ns6:entradaEjecutarReverso/ns6:datosAdicionales/ns6:datoAdicional[codigo = "s_rol"]/valor'/>
				</rolBPM>
				<sec>
					<xsl:value-of select='/ns6:entradaEjecutarReverso/ns6:datosAdicionales/ns6:datoAdicional[codigo = "s_ssn"]/valor'/>
				</sec>
				<secuencial>
					<xsl:value-of select='/ns6:entradaEjecutarReverso/ns6:datosAdicionales/ns6:datoAdicional[codigo = "s_ssn"]/valor'/>
				</secuencial>
				<servidor>
					<xsl:value-of select='/ns6:entradaEjecutarReverso/ns6:datosAdicionales/ns6:datoAdicional[codigo = "s_srv"]/valor'/>
				</servidor>
			</informacionCore>
			<xsl:choose>
				<xsl:when test="/ns6:entradaEjecutarReverso/ns6:canal = 'CNB'">
					<CNB>
						<autorizacion>			  
							<xsl:value-of select="/ns6:entradaEjecutarReverso/ns6:datosAdicionales/ns6:datoAdicional[codigo = 'p_autorizacionCNB']/valor"/>
						</autorizacion>
						<comercio>
							<xsl:value-of select="/ns6:entradaEjecutarReverso/ns6:datosAdicionales/ns6:datoAdicional[codigo = 'p_comercio']/valor"/>
						</comercio>
						<terminalID>
							<xsl:value-of select="/ns6:entradaEjecutarReverso/ns6:datosAdicionales/ns6:datoAdicional[codigo = 'p_terminalID']/valor"/>
						</terminalID>
						<agencia>
							<xsl:value-of select="/ns6:entradaEjecutarReverso/ns6:datosAdicionales/ns6:datoAdicional[codigo = 'p_agencia']/valor"/>
						</agencia>
						<red>
							<xsl:value-of select="/ns6:entradaEjecutarReverso/ns6:datosAdicionales/ns6:datoAdicional[codigo = 'p_red']/valor"/>
						</red>
						<secuencial>
							<xsl:value-of select='/ns6:entradaEjecutarReverso/ns6:datosAdicionales/ns6:datoAdicional[codigo = "s_ssn"]/valor'/>
						</secuencial>
						<valor>
							<xsl:value-of select="/ns6:entradaEjecutarReverso/ns6:valorPago"/>
						</valor>
						<nombreCliente>
							<xsl:value-of select='/ns6:entradaEjecutarReverso/ns6:datosAdicionales/ns6:datoAdicional[codigo = "p_nombreCliente"]/valor'/>
						</nombreCliente>
						<identificacionCliente>
							<xsl:value-of select='/ns6:entradaEjecutarReverso/ns6:datosAdicionales/ns6:datoAdicional[codigo = "p_identificacionCliente"]/valor'/>
						</identificacionCliente>
						<modoCorreccion>
							<xsl:text disable-output-escaping="no">S</xsl:text>
						</modoCorreccion>
						<reversoTransaccion>
               				<xsl:value-of select='/ns6:entradaEjecutarReverso/ns6:datosAdicionales/ns6:datoAdicional[codigo = "p_reversoTransaccion"]/valor'/>
               			</reversoTransaccion>
						<tipoTransaccion>
							<xsl:text disable-output-escaping="no">R</xsl:text>
						</tipoTransaccion>
						<formaPago>
							<xsl:value-of select='/ns6:entradaEjecutarReverso/ns6:datosAdicionales/ns6:datoAdicional[codigo = "p_forma_pago"]/valor'/>
						</formaPago>
					</CNB>
				</xsl:when>
			</xsl:choose>
		</mmn:MensajeEntradaReverso>
	</xsl:template>
</xsl:stylesheet>
