<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../otc-nopolicy.wsdl"/>
      <rootElement name="entradaEjecutarPago" namespace="http://www.bolivariano.com/ws/OTCService"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../CEP.xsd"/>
      <rootElement name="MensajeEntradaPago" namespace="http://www.bolivariano.com/MensajeMunicipio"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.8(build 150622.2350.0222) AT [FRI MAY 25 16:33:28 COT 2018]. -->
?>
<xsl:stylesheet version="1.0"               
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"                
                xmlns:tns="http://www.bolivariano.com/ws/OTCService"
                xmlns:mmn="http://www.bolivariano.com/MensajeMunicipio"
                xmlns:ns6="http://www.bolivariano.com/mensaje/MensajeOTC"
                xmlns:java="java"
                exclude-result-prefixes="java ns6 tns xsl">
  <xsl:template match="/">
    <mmn:MensajeEntradaPago>
      <canal>
        <xsl:value-of select="/ns6:entradaEjecutarPago/ns6:canal"/>
      </canal>
      <fecha>
        <xsl:value-of select='/ns6:entradaEjecutarPago/ns6:datosAdicionales/ns6:datoAdicional[codigo = "s_date"]/valor'/>
      </fecha>
      <oficina>
        <xsl:value-of select='/ns6:entradaEjecutarPago/ns6:datosAdicionales/ns6:datoAdicional[codigo = "s_ofi"]/valor'/>
      </oficina>
      <terminal>
       <xsl:value-of select='/ns6:entradaEjecutarPago/ns6:datosAdicionales/ns6:datoAdicional[codigo = "s_term"]/valor'/>
      </terminal>
      <transaccion>
        <xsl:text disable-output-escaping="no">62074</xsl:text>
      </transaccion>
      <usuario>
        <xsl:value-of select='/ns6:entradaEjecutarPago/ns6:datosAdicionales/ns6:datoAdicional[codigo = "s_user"]/valor'/>
      </usuario>
      <banred>
        <codigoOperador>
          <xsl:text disable-output-escaping="no">000005390</xsl:text>
        </codigoOperador>
        <fechaCompensacion>
        <xsl:value-of select='java:format(java:text.SimpleDateFormat.new("yyyyMMdd"), java:util.Date.new())'/>
        </fechaCompensacion>
        <fechaHoraBANRED>
        <xsl:value-of select='java:format(java:text.SimpleDateFormat.new("yyyyMMddHHmmss"), java:util.Date.new())'/>
        </fechaHoraBANRED>
        <fechaTransaccionLocal>
        <xsl:value-of select='java:format(java:text.SimpleDateFormat.new("yyyyMMdd"), java:util.Date.new())'/>
        </fechaTransaccionLocal>
        <horaTransaccionLocal>
        <xsl:value-of select='java:format(java:text.SimpleDateFormat.new("HHmmss"), java:util.Date.new())'/>
        </horaTransaccionLocal>
        <institucionAdquirente>
          <xsl:text disable-output-escaping="no">00597777</xsl:text>
        </institucionAdquirente>
        <numeroTerminal>
          <xsl:text disable-output-escaping="no">0233000000VIRTUA</xsl:text>
        </numeroTerminal>
        <producto>
          <xsl:text disable-output-escaping="no">0010031003</xsl:text>
        </producto>
        <secuencialAdquirente>
        <xsl:value-of select='substring(/ns6:entradaEjecutarPago/ns6:datosAdicionales/ns6:datoAdicional[codigo = "s_ssn"]/valor,2,6)'/>
        </secuencialAdquirente>
        <secuencialBANRED>
        <xsl:value-of select='substring(/ns6:entradaEjecutarPago/ns6:datosAdicionales/ns6:datoAdicional[codigo = "s_ssn"]/valor,2,6)'/>
        </secuencialBANRED>
        <tipoMoneda>
          <xsl:text disable-output-escaping="no">840</xsl:text>
        </tipoMoneda>
        <tipoTransaccion>
          <xsl:text disable-output-escaping="no">45109M</xsl:text>
        </tipoTransaccion>
      </banred>
      <municipio>
        <autorizacion>
          <xsl:text disable-output-escaping="no">N</xsl:text>
        </autorizacion>
        <cantidadCheque>
          <xsl:text disable-output-escaping="no">0</xsl:text>
        </cantidadCheque>
        <chequeComision>
          <xsl:text disable-output-escaping="no">0.00</xsl:text>
        </chequeComision>
        <codigoComercio>
          <xsl:text disable-output-escaping="no">2245</xsl:text>
        </codigoComercio>
        <codigoProveedor>
        <xsl:value-of select="/ns6:entradaEjecutarPago/ns6:servicio/codigoEmpresa"/>
        </codigoProveedor>
        <debito>
        <xsl:value-of select="format-number(/ns6:entradaEjecutarPago/ns6:valorPago,'0.00')"/>
        </debito>
        <debitoComision>
		<xsl:value-of select="format-number(/ns6:entradaEjecutarPago/ns6:valorComision,'0.00')"/>
        </debitoComision>
        <efectivo>
          <xsl:text disable-output-escaping="no">0.00</xsl:text>
        </efectivo>
        <efectivoCheque>
          <xsl:text disable-output-escaping="no">0.00</xsl:text>
        </efectivoCheque>
        <efectivoComision>
          <xsl:text disable-output-escaping="no">0.00</xsl:text>
        </efectivoComision>
        <empresa>
        <xsl:value-of select="/ns6:entradaEjecutarPago/ns6:servicio/codigoConvenio"/>
        </empresa>
        <nombre>
         <xsl:value-of select="/ns6:entradaEjecutarPago/ns6:nombreCliente"/>
        </nombre>
        <numeroTarjeta>
          <xsl:text disable-output-escaping="no">0.00</xsl:text>
        </numeroTarjeta>
        <opcion>
          <xsl:text disable-output-escaping="no">T</xsl:text>
        </opcion>
        <secuencialRequerimiento>
          <xsl:value-of select='substring(/ns6:entradaEjecutarPago/ns6:datosAdicionales/ns6:datoAdicional[codigo = "s_ssn"]/valor,2,6)'/>
        </secuencialRequerimiento>
        <tipoMoneda>
          <xsl:text disable-output-escaping="no">1</xsl:text>
        </tipoMoneda>
        <tipoReferencia>
          <xsl:text disable-output-escaping="no">001</xsl:text>
        </tipoReferencia>
        <ubicacion>
          <xsl:text disable-output-escaping="no">0</xsl:text>
        </ubicacion>
        <valorTotalCancelar>
     	  <xsl:value-of select="format-number(/ns6:entradaEjecutarPago/ns6:valorPago,'0.00')"/>
        </valorTotalCancelar>
        <cuenta>
          <cuenta>
          <xsl:value-of select='/ns6:entradaEjecutarPago/ns6:cuenta'/>
          </cuenta>
          <idProducto>
           <xsl:value-of select='/ns6:entradaEjecutarPago/ns6:tipoCuenta'/>
          </idProducto>
          <tipoCuenta>
            <xsl:value-of select='/ns6:entradaEjecutarPago/ns6:tipoCuenta'/>
          </tipoCuenta>
          <servicio>
            <xsl:value-of select="/ns6:entradaEjecutarPago/ns6:servicio/codigoTipoIdentificador"/>
          </servicio>
        </cuenta>
        <anioVigencia>
         <!-- <xsl:text disable-output-escaping="no">9999</xsl:text>-->
         <xsl:value-of select="/ns6:entradaEjecutarPago/ns6:recibos/ns6:recibo/fecha"/>
        </anioVigencia>
        <xsl:choose>
          <xsl:when test='/ns6:entradaEjecutarPago/ns6:servicio/codigoTipoIdentificador  = "01"'>
            <suministro>
              <xsl:value-of select='substring(
              concat("0000000000",/mmn:entradaEjecutarPago/municipio/suministro), string-length(/mmn:MensajeEntradaConsultar/municipio/suministro) + 1.0,10.0)'/>
            </suministro>
          </xsl:when>
          <xsl:when test='/ns6:entradaEjecutarPago/ns6:servicio/codigoTipoIdentificador = "02"'>
            <identificacion>
              <xsl:value-of select="/ns6:entradaEjecutarPago/ns6:servicio/identificador"/>
            </identificacion>
          </xsl:when>
          <xsl:when test='/ns6:entradaEjecutarPago/ns6:servicio/codigoTipoIdentificador = "03"'>
            <codigoCanal>9</codigoCanal>
            <codigoPHH>
              <xsl:value-of select="substring(/ns6:entradaEjecutarPago/ns6:servicio/identificador, 29,4)"/>
            </codigoPHH>
            <codigoPHV>
              <xsl:value-of select="substring(/ns6:entradaEjecutarPago/ns6:servicio/identificador, 24,4)"/>
            </codigoPHV>
            <division>
              <xsl:value-of select="substring(/ns6:entradaEjecutarPago/ns6:servicio/identificador, 18,5)"/>
            </division>
            <institucionAutorizadora>
              <xsl:text disable-output-escaping="no">0233</xsl:text>
            </institucionAutorizadora>
            <lote>
              <xsl:value-of select="substring(/ns6:entradaEjecutarPago/ns6:servicio/identificador,12,5)"/>
            </lote>
            <manzana>
              <xsl:value-of select="substring(/ns6:entradaEjecutarPago/ns6:servicio/identificador, 6,5)"/>
            </manzana>
            <numeroCatastral>
              <xsl:value-of select="substring(/ns6:entradaEjecutarPago/ns6:servicio/identificador,34,3)"/>
            </numeroCatastral>
            <sector>
              <xsl:value-of select="substring(/ns6:entradaEjecutarPago/ns6:servicio/identificador, 1,4)"/>
            </sector>
          </xsl:when>
          <xsl:when test='/ns6:entradaEjecutarPago/ns6:servicio/codigoTipoIdentificador = "04"'>
            <identificacion>
              <xsl:value-of select="/ns6:entradaEjecutarPago/ns6:servicio/identificador"/>
            </identificacion>
          </xsl:when>
        </xsl:choose>
        
        <semestre>
          <xsl:text disable-output-escaping="no">3</xsl:text>
        </semestre>
      </municipio>
      <informacionCore>
        <rolBPM>
        <xsl:value-of select='/ns6:entradaEjecutarPago/ns6:datosAdicionales/ns6:datoAdicional[codigo = "s_rol"]/valor'/>
        </rolBPM>
        <sec>
          <xsl:value-of select='/ns6:entradaEjecutarPago/ns6:datosAdicionales/ns6:datoAdicional[codigo = "s_ssn"]/valor'/>
        </sec>
        <secuencial>
        <xsl:value-of select='/ns6:entradaEjecutarPago/ns6:datosAdicionales/ns6:datoAdicional[codigo = "s_ssn"]/valor'/>
        </secuencial>
        <servidor>
          <xsl:value-of select='/ns6:entradaEjecutarPago/ns6:datosAdicionales/ns6:datoAdicional[codigo = "s_srv"]/valor'/>
        </servidor>
      </informacionCore>
    </mmn:MensajeEntradaPago>
  </xsl:template>
</xsl:stylesheet>
