<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../../../../../../../Disco%20D/veinti4online/Proyecto%20Cash/Concentrador%20de%20pagos/DOCUMENTACIONMAPEO/Project4/xsd/ClaroPostPago_1.wsdl"/>
      <rootElement name="MensajeSalidaPagarClaroPostPago" namespace="http://www.bolivariano.com/MensajeClaro"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../../../../../../../Disco%20D/veinti4online/Proyecto%20Cash/Concentrador%20de%20pagos/DOCUMENTACIONMAPEO/Project4/otc-nopolicy.wsdl"/>
      <rootElement name="salidaEjecutarPago" namespace="http://www.bolivariano.com/mensaje/MensajeOTC"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 130301.0647.0008) AT [WED MAY 23 13:35:41 COT 2018]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                xmlns:ns8="http://www.bolivariano.com/dominio/DatoAdicional"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:tns="http://www.bolivariano.com/ws/ClaroPostPago"
                xmlns:ns3="http://www.bolivariano.com/CoreBB"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns5="http://www.bolivariano.com/Cuenta"
                xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:ns14="http://www.bolivariano.com/dominio/Convenio"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns15="http://www.bolivariano.com/dominio/Recibo"
                xmlns:ns18="http://www.bolivariano.com/dominio/RegionalArea"
                xmlns:ns19="http://www.bolivariano.com/dominio/ListaSeleccion"
                xmlns:ns10="http://www.bolivariano.com/dominio/Servicio"
                xmlns:ns0="http://www.bolivariano.com/MensajeBolivariano"
                xmlns:ns2="http://www.bolivariano.com/ws/ClaroPostPago/types"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:ns6="http://www.bolivariano.com/Recaudo"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:ns11="http://www.bolivariano.com/dominio/TipoMatriculacion"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:ns12="http://www.bolivariano.com/dominio/FormaPago"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:mcl="http://www.bolivariano.com/MensajeClaro"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns13="http://www.bolivariano.com/dominio/TipoIdentificador"
                xmlns:ns1="http://www.bolivariano.com/Claro"
                xmlns:ns9="http://www.bolivariano.com/mensaje/MensajeOTC"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:ns4="http://www.bolivariano.com/Producto"
                xmlns:ns7="http://www.bolivariano.com/Cliente"
                xmlns:ns16="http://www.bolivariano.com/dominio/Empresa"
                xmlns:ns17="http://www.bolivariano.com/mensaje/MensajeOTC"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                xmlns:java="java"
                exclude-result-prefixes="xsi xsl soap12 soap tns ns3 wsdl ns5 mime ns0 ns2 ns6 mcl ns1 xsd ns4 ns7 ns8 ns14 ns15 ns18 ns19 ns10 ns11 ns12 ns13 ns9 ns16 ns17 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap">
  <xsl:template match="/">
    <ns9:salidaEjecutarPago>
      <xsl:if test='/mcl:MensajeSalidaPagarClaroPostPago/codigoError = "CL_005"'>
            <ns17:codigoError>
                <xsl:text disable-output-escaping="no">0</xsl:text>
            </ns17:codigoError>      
              <ns17:datosAdicionales>
                    <ns17:datoAdicional>
                      <etiqueta>
                            <xsl:text disable-output-escaping="no">Base imponible</xsl:text>
                      </etiqueta>
                      <valor>
                            <xsl:value-of select="/mcl:MensajeSalidaPagarClaroPostPago/informacionClaro/baseImponible"/>
                      </valor>
                    </ns17:datoAdicional>
                    <!--<ns17:datoAdicional>
                      <codigo>
                            <xsl:text disable-output-escaping="no">horario</xsl:text>
                      </codigo>
                      <valor>
                            <xsl:value-of select="/mcl:MensajeSalidaPagarClaroPostPago/informacionClaro/horario"/>
                      </valor>
                    </ns17:datoAdicional>-->
					<ns17:datoAdicional>
						<etiqueta>
							<xsl:text disable-output-escaping="no">Valor impuesto</xsl:text>
						</etiqueta>
						<valor>
							<xsl:value-of select="/mcl:MensajeSalidaPagarClaroPostPago/informacionClaro/valorImpuesto"/>
						</valor>
					</ns17:datoAdicional>
				</ns17:datosAdicionales>
				<ns17:fechaDebito>
					<xsl:value-of select='java:format(java:text.SimpleDateFormat.new("yyyy-MM-dd&apos;T&apos;HH:mm:ss.SSS"), java:util.Date.new())'/>
				</ns17:fechaDebito>
				<ns17:fechaPago>
					<xsl:value-of select="/mcl:MensajeSalidaPagarClaroPostPago/informacionCore/fechaProcesoKernel"/>
				</ns17:fechaPago>              
				<ns17:referencia>
					<xsl:value-of select="/mcl:MensajeSalidaPagarClaroPostPago/informacionCore/secuencial"/>
				</ns17:referencia>
				<ns17:datosAdicionales>
					<ns17:datoAdicional>
						<codigo>horario</codigo>
						<valor>
							<xsl:value-of select="/mcl:MensajeSalidaPagarClaroPostPago/informacionClaro/horario"/>
						</valor>
					</ns17:datoAdicional>
				</ns17:datosAdicionales>
			</xsl:if>
			<xsl:if test='/mcl:MensajeSalidaPagarClaroPostPago/codigoError != "CL_005"'>
				<ns17:codigoError>
					<xsl:value-of select="/mcl:MensajeSalidaPagarClaroPostPago/codigoError"/>
				</ns17:codigoError>     
			</xsl:if>
			<ns17:mensajeUsuario>
				<xsl:value-of select="/mcl:MensajeSalidaPagarClaroPostPago/mensajeUsuario"/>
			</ns17:mensajeUsuario>      
		</ns9:salidaEjecutarPago>
	</xsl:template>
</xsl:stylesheet>
