<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../otc-nopolicy.wsdl"/>
      <rootElement name="entradaEjecutarPago" namespace="http://www.bolivariano.com/ws/OTCService"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../../../CASH-MANAGEMENT/DOCUMENTOS_CASH/Fuentes/Middleware/ClaroTV/SCA_CLARO/ClaroTVSatelital/xsd/MensajeClaro.xsd"/>
      <rootElement name="MensajeEntradaPagarClaroTV" namespace="http://www.bolivariano.com/MensajeClaro"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.8(build 150622.2350.0222) AT [THU MAY 31 16:38:09 COT 2018]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:ns1="http://www.bolivariano.com/dominio/DatoAdicional"
                xmlns:cbb="http://www.bolivariano.com/CoreBB"
                xmlns:ns12="http://www.bolivariano.com/Cuenta"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:ns3="http://www.bolivariano.com/dominio/Convenio"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns5="http://www.bolivariano.com/dominio/Recibo"
                xmlns:ns9="http://www.bolivariano.com/dominio/ListaSeleccion"
                xmlns:ns10="http://www.bolivariano.com/dominio/RegionalArea"
                xmlns:ns2="http://www.bolivariano.com/dominio/Servicio"
                xmlns:mbl="http://www.bolivariano.com/MensajeBolivariano"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:rcd="http://www.bolivariano.com/Recaudo"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:ns7="http://www.bolivariano.com/dominio/TipoMatriculacion"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:ns8="http://www.bolivariano.com/dominio/FormaPago"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:mcl="http://www.bolivariano.com/MensajeClaro"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns0="http://www.bolivariano.com/dominio/TipoIdentificador"
                xmlns:tns="http://www.bolivariano.com/ws/OTCService"
                xmlns:cla="http://www.bolivariano.com/Claro"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:ns11="http://www.bolivariano.com/Producto"
                xmlns:bpmn="http://schemas.oracle.com/bpm/xpath"
                xmlns:ns4="http://www.bolivariano.com/dominio/Empresa"
                xmlns:ns13="http://www.bolivariano.com/Cliente"
                xmlns:ns6="http://www.bolivariano.com/mensaje/MensajeOTC"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                xmlns:java="java"
                exclude-result-prefixes="xsi xsl soap ns1 wsdl ns3 ns5 ns9 ns10 ns2 ns7 ns8 ns0 tns xsd ns4 ns6 cbb ns12 mbl rcd mcl cla ns11 ns13 bpws xp20 bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref bpmn ldap">
  <xsl:template match="/">
    <mcl:MensajeEntradaPagarClaroTV>
      <canal>
        <xsl:value-of select="/ns6:entradaEjecutarPago/ns6:canal"/>
      </canal>
      <depuracion>
        <xsl:text disable-output-escaping="no">N</xsl:text>
      </depuracion>
      <transaccion>
        <xsl:text disable-output-escaping="no">62328</xsl:text>
      </transaccion>
      <usuario>
        <xsl:value-of select='/ns6:entradaEjecutarPago/ns6:datosAdicionales/ns6:datoAdicional[codigo = "s_user"]/valor'/>
      </usuario>
      <informacionClaro>
        <aplicativoCobis>
          <xsl:text disable-output-escaping="no">N</xsl:text>
        </aplicativoCobis>
        <autorizacion>
          <xsl:text disable-output-escaping="no">N</xsl:text>
        </autorizacion>
        <cantidadCheque>
          <xsl:text disable-output-escaping="no">0</xsl:text>
        </cantidadCheque>
        <debito>
          <xsl:value-of select="/ns6:entradaEjecutarPago/ns6:valorPago"/>
        </debito>
        <debitoComision>
          <xsl:value-of select="/ns6:entradaEjecutarPago/ns6:valorComision"/>
        </debitoComision>
        <efectivo>
          <xsl:text disable-output-escaping="no">0</xsl:text>
        </efectivo>
        <efectivoComision>
          <xsl:text disable-output-escaping="no">0.00</xsl:text>
        </efectivoComision>
        <empresa>
          <xsl:value-of select="/ns6:entradaEjecutarPago/ns6:servicio/codigoEmpresa"/>
        </empresa>
        <fechaContable>
        <xsl:value-of select='/ns6:entradaEjecutarPago/ns6:datosAdicionales/ns6:datoAdicional[codigo = "s_date"]/valor'/>
        </fechaContable>
        <fechaEmision>
        <xsl:value-of select='java:format(java:text.SimpleDateFormat.new("yyyy-MM-dd&apos;T&apos;HH:mm:ss.SSS"), java:util.Date.new())'/>
        </fechaEmision>
        <identificacion>
          <xsl:value-of select="/ns6:entradaEjecutarPago/ns6:servicio/identificador"/>
        </identificacion>
        <nombre>
          <xsl:value-of select="/ns6:entradaEjecutarPago/ns6:nombreCliente"/>
        </nombre>
        <tipoMoneda>
          <xsl:text disable-output-escaping="no">1</xsl:text>
        </tipoMoneda>
        <servicioPersona>
          <xsl:text disable-output-escaping="no">5</xsl:text>
        </servicioPersona>
        <ubicacion>
          <xsl:text disable-output-escaping="no">0</xsl:text>
        </ubicacion>
        <totalComision>
          <xsl:value-of select="/ns6:entradaEjecutarPago/ns6:valorComision"/>
        </totalComision>
        <valorCheque>
          <xsl:text disable-output-escaping="no">0.00</xsl:text>
        </valorCheque>
        <valorTotalCancelar>
          <xsl:value-of select="/ns6:entradaEjecutarPago/ns6:valorPago"/>
        </valorTotalCancelar>
        <cuenta>
          <cuenta>
            <xsl:value-of select="/ns6:entradaEjecutarPago/ns6:cuenta"/>
          </cuenta>
          <tipoCuenta>
            <xsl:value-of select="/ns6:entradaEjecutarPago/ns6:tipoCuenta"/>
          </tipoCuenta>
        </cuenta>
        <codigoInstitucion>
          <xsl:text disable-output-escaping="no">0018</xsl:text>
        </codigoInstitucion>
      </informacionClaro>
      <informacionCore>
        <secuencial>
        <xsl:value-of select='/ns6:entradaEjecutarPago/ns6:datosAdicionales/ns6:datoAdicional[codigo =  "s_ssn"]/valor'/>
        </secuencial>
        <transaccionServLocal>
        <xsl:value-of select='/ns6:entradaEjecutarPago/ns6:datosAdicionales/ns6:datoAdicional[codigo = "s_srv"]/valor'/>
        </transaccionServLocal>
      </informacionCore>
    </mcl:MensajeEntradaPagarClaroTV>
  </xsl:template>
</xsl:stylesheet>
