<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../../../CASH-MANAGEMENT/DOCUMENTOS_CASH/Fuentes/Middleware/ClaroTV/SCA_CLARO/ClaroTVSatelital/xsd/MensajeClaro.xsd"/>
      <rootElement name="MensajeSalidaConsultarClaroTV" namespace="http://www.bolivariano.com/MensajeClaro"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../otc-nopolicy.wsdl"/>
      <rootElement name="salidaConsultarDeuda" namespace="http://www.bolivariano.com/ws/OTCService"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.8(build 150622.2350.0222) AT [WED MAY 30 18:16:35 COT 2018]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:ns3="http://www.bolivariano.com/dominio/DatoAdicional"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:cbb="http://www.bolivariano.com/CoreBB"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns1="http://www.bolivariano.com/Cuenta"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:ns6="http://www.bolivariano.com/dominio/Convenio"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns8="http://www.bolivariano.com/dominio/Recibo"
                xmlns:ns12="http://www.bolivariano.com/dominio/ListaSeleccion"
                xmlns:ns13="http://www.bolivariano.com/dominio/RegionalArea"
                xmlns:ns5="http://www.bolivariano.com/dominio/Servicio"
                xmlns:mbl="http://www.bolivariano.com/MensajeBolivariano"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:rcd="http://www.bolivariano.com/Recaudo"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:ns10="http://www.bolivariano.com/dominio/TipoMatriculacion"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:ns11="http://www.bolivariano.com/dominio/FormaPago"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:mcl="http://www.bolivariano.com/MensajeClaro"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns4="http://www.bolivariano.com/dominio/TipoIdentificador"
                xmlns:cla="http://www.bolivariano.com/Claro"
                xmlns:tns="http://www.bolivariano.com/ws/OTCService"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:ns0="http://www.bolivariano.com/Producto"
                xmlns:bpmn="http://schemas.oracle.com/bpm/xpath"
                xmlns:ns2="http://www.bolivariano.com/Cliente"
                xmlns:ns7="http://www.bolivariano.com/dominio/Empresa"
                xmlns:ns9="http://www.bolivariano.com/mensaje/MensajeOTC"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl cbb ns1 mbl rcd mcl cla xsd ns0 ns2 ns3 soap wsdl ns6 ns8 ns12 ns13 ns5 ns10 ns11 ns4 tns ns7 ns9 bpws xp20 bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref bpmn ldap">
  <xsl:template match="/">
    <xsl:choose>
      <xsl:when test="/mcl:MensajeSalidaConsultarClaroTV/codigoError='CL_001'">
        <ns9:salidaConsultarDeuda>
          <ns9:codigoError>0</ns9:codigoError>
          <ns9:mensajeUsuario>Mensaje Procesado</ns9:mensajeUsuario>
          <ns9:formaPago>ABONO</ns9:formaPago>
          <ns9:fechaVencimiento>
            <xsl:value-of select="/mcl:MensajeSalidaConsultarClaroTV/informacionClaro/fechaVencimiento"/>
          </ns9:fechaVencimiento>
          <ns9:limiteMontoMaximo>
            <xsl:value-of select="/mcl:MensajeSalidaConsultarClaroTV/informacionClaro/valorTotalCancelar * (2.0)"/>
          </ns9:limiteMontoMaximo>
          <ns9:montoTotal>
            <xsl:value-of select="/mcl:MensajeSalidaConsultarClaroTV/informacionClaro/valorTotalCancelar"/>
          </ns9:montoTotal>
          <ns9:nombreCliente>
            <xsl:value-of select="/mcl:MensajeSalidaConsultarClaroTV/informacionClaro/nombre"/>
          </ns9:nombreCliente>
        </ns9:salidaConsultarDeuda>
      </xsl:when>
      <xsl:otherwise>
        <ns9:salidaConsultarDeuda>
          <ns9:codigoError>
            <xsl:value-of select="/mcl:MensajeSalidaConsultarClaroTV/codigoError"/>
          </ns9:codigoError>
          <ns9:mensajeUsuario>
            <xsl:value-of select="/mcl:MensajeSalidaConsultarClaroTV/mensajeUsuario"/>
          </ns9:mensajeUsuario>
        </ns9:salidaConsultarDeuda>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>
</xsl:stylesheet>
