<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../../../../../../../Disco%20D/veinti4online/Proyecto%20Cash/Concentrador%20de%20pagos/DOCUMENTACIONMAPEO/Project4/otc-nopolicy.wsdl"/>
      <rootElement name="entradaEjecutarPago" namespace="http://www.bolivariano.com/mensaje/MensajeOTC"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../../../../../../../Disco%20D/veinti4online/Proyecto%20Cash/Concentrador%20de%20pagos/DOCUMENTACIONMAPEO/Project4/xsd/ClaroTiempoAire_1.wsdl"/>
      <rootElement name="MensajeEntradaComprarTiempoAire" namespace="http://www.bolivariano.com/MensajeClaro"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 130301.0647.0008) AT [MON MAY 28 14:37:51 COT 2018]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:WL5G3N4="http://schemas.xmlsoap.org/wsdl/soap12/"
                xmlns:ns1="http://www.bolivariano.com/dominio/DatoAdicional"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:ns12="http://www.bolivariano.com/CoreBB"
                xmlns:ns14="http://www.bolivariano.com/Cuenta"
                xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:ns5="http://www.bolivariano.com/dominio/Convenio"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns6="http://www.bolivariano.com/dominio/Recibo"
                xmlns:cta="http://www.bolivariano.com/ClaroCompraTiempoAire/"
                xmlns:ns9="http://www.bolivariano.com/dominio/RegionalArea"
                xmlns:ns10="http://www.bolivariano.com/dominio/ListaSeleccion"
                xmlns:ns0="http://www.bolivariano.com/dominio/Servicio"
                xmlns:ns11="http://www.bolivariano.com/MensajeBolivariano"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:ns15="http://www.bolivariano.com/Recaudo"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:ns2="http://www.bolivariano.com/dominio/TipoMatriculacion"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:ns3="http://www.bolivariano.com/dominio/FormaPago"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:mcl="http://www.bolivariano.com/MensajeClaro"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns4="http://www.bolivariano.com/dominio/TipoIdentificador"
                xmlns:tns="http://www.bolivariano.com/mensaje/MensajeOTC"
                xmlns:clr="http://www.bolivariano.com/Claro"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:ns13="http://www.bolivariano.com/Producto"
                xmlns:ns7="http://www.bolivariano.com/dominio/Empresa"
                xmlns:ns16="http://www.bolivariano.com/Cliente"
                xmlns:ns8="http://www.bolivariano.com/mensaje/MensajeOTC"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl ns1 soap wsdl ns5 ns6 ns9 ns10 ns0 ns2 ns3 ns4 tns xsd ns7 ns8 WL5G3N4 ns12 ns14 mime cta ns11 ns15 mcl clr ns13 ns16 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap">
	<xsl:template match="/">
		<mcl:MensajeEntradaComprarTiempoAire>
			<!--<xsl:if test='/tns:entradaEjecutarPago/ns8:canal = "BIB"'>-->
			<canal>
				<xsl:value-of select="/tns:entradaEjecutarPago/ns8:canal"/>
				<!--<xsl:text disable-output-escaping="no">IBK</xsl:text>-->
			</canal>
			<!--</xsl:if>-->
			<fecha>
				<xsl:value-of select="/tns:entradaEjecutarPago/ns8:fecha"/>
			</fecha>
			<oficina>
				<xsl:value-of select='/ns8:entradaEjecutarPago/ns8:datosAdicionales/ns8:datoAdicional[codigo = "s_ofi"]/valor'/>
			</oficina>
			<terminal>
				<xsl:value-of select='/ns8:entradaEjecutarPago/ns8:datosAdicionales/ns8:datoAdicional[codigo = "s_term"]/valor'/>
			</terminal>
			<transaccion>
				<xsl:text disable-output-escaping="no">62263</xsl:text>
			</transaccion>
			<usuario>
				<xsl:value-of select='/ns8:entradaEjecutarPago/ns8:datosAdicionales/ns8:datoAdicional[codigo = "s_user"]/valor'/>
			</usuario>
			<informacionClaro>
				<aplicativoCobis>
					<xsl:text disable-output-escaping="no">N</xsl:text>
				</aplicativoCobis>
				<autorizacion>
					<xsl:text disable-output-escaping="no">N</xsl:text>
				</autorizacion>
				<cantidadCheque>
					<xsl:text disable-output-escaping="no">0</xsl:text>
				</cantidadCheque>

				<xsl:choose>
					<xsl:when test="/ns8:entradaEjecutarPago/ns8:canal = 'CNB' and (/ns8:entradaEjecutarPago/ns8:datosAdicionales/ns8:datoAdicional[codigo = 'p_forma_pago']/valor = 'EFE')">
						<debito>
							<xsl:text disable-output-escaping="no">0.00</xsl:text>
						</debito>
						<debitoComision>
							<xsl:text disable-output-escaping="no">0.00</xsl:text>
						</debitoComision>
						<efectivo>
							<xsl:value-of select="/tns:entradaEjecutarPago/ns8:valorPago"/>
						</efectivo>
						<efectivoComision>
							<xsl:value-of select="/tns:entradaEjecutarPago/ns8:valorComision"/>
						</efectivoComision>
					</xsl:when>
					<xsl:when test="/ns8:entradaEjecutarPago/ns8:canal = 'CNB' and (/ns8:entradaEjecutarPago/ns8:datosAdicionales/ns8:datoAdicional[codigo = 'p_forma_pago']/valor = 'DEB')">
						<debito>
							<xsl:value-of select="/tns:entradaEjecutarPago/ns8:valorPago"/>
						</debito>
						<debitoComision>
							<xsl:value-of select="/tns:entradaEjecutarPago/ns8:valorComision"/>
						</debitoComision>
						<efectivo>
							<xsl:text disable-output-escaping="no">0.00</xsl:text>
						</efectivo>
						<efectivoComision>
							<xsl:text disable-output-escaping="no">0.00</xsl:text>
						</efectivoComision>
					</xsl:when>
					<xsl:otherwise>
						<debito>
							<xsl:value-of select="/tns:entradaEjecutarPago/ns8:valorPago"/>
						</debito>
						<debitoComision>
							<xsl:value-of select="/tns:entradaEjecutarPago/ns8:valorComision"/>
						</debitoComision>
						<efectivo>
							<xsl:text disable-output-escaping="no">0</xsl:text>
						</efectivo>
						<efectivoComision>
							<xsl:text disable-output-escaping="no">0.00</xsl:text>
						</efectivoComision>
					</xsl:otherwise>
				</xsl:choose>
				
				<xsl:choose>
					<xsl:when test="/ns8:entradaEjecutarPago/ns8:canal = 'CNB'">
						<empresa>
							<xsl:value-of select='/ns8:entradaEjecutarPago/ns8:datosAdicionales/ns8:datoAdicional[codigo = "p_codigoEmpresa"]/valor'/>
						</empresa>
					</xsl:when>
					<xsl:otherwise>
						<empresa>
							<xsl:value-of select="/tns:entradaEjecutarPago/ns8:servicio/codigoEmpresa"/>
						</empresa>
					</xsl:otherwise>
				</xsl:choose>
				
				<tipoMoneda>
					<xsl:text disable-output-escaping="no">1</xsl:text>
				</tipoMoneda>
				<ubicacion>
					<xsl:text disable-output-escaping="no">0</xsl:text>
				</ubicacion>
				<valorCheque>
					<xsl:text disable-output-escaping="no">0.00</xsl:text>
				</valorCheque>
				<valorTotalCancelar>
					<xsl:value-of select="/tns:entradaEjecutarPago/ns8:valorPago"/>
				</valorTotalCancelar>
				<cuenta>
					<cuenta>
						<xsl:value-of select="/tns:entradaEjecutarPago/ns8:cuenta"/>
					</cuenta>
					<tipoCuenta>
						<xsl:value-of select="/tns:entradaEjecutarPago/ns8:tipoCuenta"/>
					</tipoCuenta>
					<identificaciones>
						<identificacion>
							<xsl:text disable-output-escaping="no">0000000000000</xsl:text>
						</identificacion>
						<tipoIdentificacion>
							<xsl:text disable-output-escaping="no">0</xsl:text>
						</tipoIdentificacion>
					</identificaciones>
				</cuenta>
				<celular>
					<xsl:value-of select="/tns:entradaEjecutarPago/ns8:servicio/identificador"/>
				</celular>
				<codigoMensaje>
					<xsl:text disable-output-escaping="no">22</xsl:text>
				</codigoMensaje>
			</informacionClaro>
			<informacionCore>
				<rolBPM>
					<xsl:value-of select='/ns8:entradaEjecutarPago/ns8:datosAdicionales/ns8:datoAdicional[codigo = "s_rol"]/valor'/>
				</rolBPM>
				<secuencial>
					<xsl:value-of select='/ns8:entradaEjecutarPago/ns8:datosAdicionales/ns8:datoAdicional[codigo = "s_ssn"]/valor'/>
				</secuencial>
				<servidor>
					<xsl:value-of select='/ns8:entradaEjecutarPago/ns8:datosAdicionales/ns8:datoAdicional[codigo = "s_srv"]/valor'/>
				</servidor>
				<servidorLocal>
					<xsl:value-of select='/ns8:entradaEjecutarPago/ns8:datosAdicionales/ns8:datoAdicional[codigo = "s_lsrv"]/valor'/>
				</servidorLocal>
				<sesion>
					<xsl:text disable-output-escaping="no">0</xsl:text>
				</sesion>
			</informacionCore>
			<xsl:choose>
				<xsl:when test="/ns8:entradaEjecutarPago/ns8:canal = 'CNB'">
					<CNB>
						<autorizacion>
							<xsl:value-of select="/ns8:entradaEjecutarPago/ns8:datosAdicionales/ns8:datoAdicional[codigo = 'p_autorizacionCNB']/valor"/>
						</autorizacion>
						<comercio>
							<xsl:value-of select="/ns8:entradaEjecutarPago/ns8:datosAdicionales/ns8:datoAdicional[codigo = 'p_comercio']/valor"/>
						</comercio>
						<terminalID>
							<xsl:value-of select="/ns8:entradaEjecutarPago/ns8:datosAdicionales/ns8:datoAdicional[codigo = 'p_terminalID']/valor"/>
						</terminalID>
						<agencia>
							<xsl:value-of select="/ns8:entradaEjecutarPago/ns8:datosAdicionales/ns8:datoAdicional[codigo = 'p_agencia']/valor"/>
						</agencia>
						<red>
							<xsl:value-of select="/ns8:entradaEjecutarPago/ns8:datosAdicionales/ns8:datoAdicional[codigo = 'p_red']/valor"/>
						</red>
						<secuencial>
							<xsl:value-of select='/ns8:entradaEjecutarPago/ns8:datosAdicionales/ns8:datoAdicional[codigo = "s_ssn"]/valor'/>
						</secuencial>
						<valor>
							<xsl:value-of select="/ns8:entradaEjecutarPago/ns8:valorPago"/>
						</valor>
						<nombreCliente>
							<xsl:value-of select='/ns8:entradaEjecutarPago/ns8:datosAdicionales/ns8:datoAdicional[codigo = "p_nombreCliente"]/valor'/>
						</nombreCliente>
						<identificacionCliente>
							<xsl:value-of select='/ns8:entradaEjecutarPago/ns8:datosAdicionales/ns8:datoAdicional[codigo = "p_identificacionCliente"]/valor'/>
						</identificacionCliente>
						<modoCorreccion>
							<xsl:text disable-output-escaping="no">N</xsl:text>
						</modoCorreccion>
						<tipoTransaccion>P</tipoTransaccion>	
						<formaPago>
							<xsl:value-of select='/ns8:entradaEjecutarPago/ns8:datosAdicionales/ns8:datoAdicional[codigo = "p_forma_pago"]/valor'/>
						</formaPago>
					</CNB>
				</xsl:when>
			</xsl:choose>

		</mcl:MensajeEntradaComprarTiempoAire>
	</xsl:template>
</xsl:stylesheet>
