<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="MensajeClaro.xsd"/>
      <rootElement name="MensajeSalidaPagarClaroTV" namespace="http://www.bolivariano.com/MensajeClaro"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../otc-nopolicy.wsdl"/>
      <rootElement name="salidaEjecutarPago" namespace="http://www.bolivariano.com/ws/OTCService"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.8(build 150622.2350.0222) AT [THU MAY 31 16:16:01 COT 2018]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ns9="http://www.bolivariano.com/mensaje/MensajeOTC"
                xmlns:mcl="http://www.bolivariano.com/MensajeClaro"
                 xmlns:java="java"
                exclude-result-prefixes="java xsl ns9 mcl">
  <xsl:template match="/">
    <xsl:choose>
      <xsl:when test="/mcl:MensajeSalidaPagarClaroTV/codigoError='CL_005'">
        <ns9:salidaEjecutarPago>
          <ns9:codigoError>0</ns9:codigoError>
          <ns9:fechaDebito>
            <xsl:value-of select='java:format(java:text.SimpleDateFormat.new("yyyy-MM-dd&apos;T&apos;HH:mm:ss"), java:util.Date.new())'/>
          </ns9:fechaDebito>
          <xsl:variable name="fechaC"
                        select="/mcl:MensajeSalidaPagarClaroTV/informacionClaro/fechaContable"/>
          <ns9:fechaPago>
            <xsl:value-of select="concat(substring($fechaC,1,4),'-',substring($fechaC,5,2),'-',substring($fechaC,7,2) )"/> 
          </ns9:fechaPago>
          <ns9:mensajeUsuario>
            <xsl:value-of select="/mcl:MensajeSalidaPagarClaroTV/mensajeUsuario"/>
          </ns9:mensajeUsuario>
          <ns9:mensajeSistema>
            <xsl:value-of select="/mcl:MensajeSalidaPagarClaroTV/mensajeSistema"/>
          </ns9:mensajeSistema>
          <ns9:referencia>
            <xsl:value-of select="/mcl:MensajeSalidaPagarClaroTV/informacionCore/secuencial"/>
          </ns9:referencia>
        </ns9:salidaEjecutarPago>
      </xsl:when>
      <xsl:otherwise>
        <ns9:salidaEjecutarPago>
          <ns9:codigoError>
            <xsl:value-of select="/mcl:MensajeSalidaPagarClaroTV/codigoError"/>
          </ns9:codigoError>
          <ns9:mensajeUsuario>
            <xsl:value-of select="/mcl:MensajeSalidaPagarClaroTV/mensajeUsuario"/>
          </ns9:mensajeUsuario>
          <ns9:mensajeSistema>
            <xsl:value-of select="/mcl:MensajeSalidaPagarClaroTV/mensajeSistema"/>
          </ns9:mensajeSistema>
          <ns9:referencia>
            <xsl:value-of select="/mcl:MensajeSalidaPagarClaroTV/informacionCore/secuencial"/>
          </ns9:referencia>
        </ns9:salidaEjecutarPago>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>
</xsl:stylesheet>
