<?xml version="1.0" encoding="UTF-8" ?>

<?oracle-xsl-mapper

  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->

  <mapSources>

    <source type="WSDL">

      <schema location="../../../../../../../Disco%20D/veinti4online/Proyecto%20Cash/Concentrador%20de%20pagos/DOCUMENTACIONMAPEO/Project4/xsd/ServicioCodigosClaro.wsdl"/>

      <rootElement name="consultarMontosRecargasResponse" namespace="http://www.claro.com.ec/servicios/ServicioCodigosClaro/"/>

    </source>

  </mapSources>

  <mapTargets>

    <target type="WSDL">

      <schema location="../../../../../../../Disco%20D/veinti4online/Proyecto%20Cash/Concentrador%20de%20pagos/DOCUMENTACIONMAPEO/Project4/otc-nopolicy.wsdl"/>

      <rootElement name="salidaConsultarDeuda" namespace="http://www.bolivariano.com/mensaje/MensajeOTC"/>

    </target>

  </mapTargets>

  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 130301.0647.0008) AT [MON MAY 28 15:35:16 COT 2018]. -->

?>

<xsl:stylesheet version="1.0"

                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"

                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"

                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"

                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"

                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"

                xmlns:clr="http://www.claro.com.ec/servicios/ServicioCodigosClaro/"

                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"

                xmlns:ns1="http://www.bolivariano.com/dominio/DatoAdicional"

                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"

                xmlns:ora="http://schemas.oracle.com/xpath/extension"

                xmlns:ns5="http://www.bolivariano.com/dominio/Convenio"

                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"

                xmlns:ns6="http://www.bolivariano.com/dominio/Recibo"

                xmlns:ns10="http://www.bolivariano.com/dominio/ListaSeleccion"

                xmlns:ns9="http://www.bolivariano.com/dominio/RegionalArea"

                xmlns:ns0="http://www.bolivariano.com/dominio/Servicio"

                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"

                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"

                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"

                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"

                xmlns:med="http://schemas.oracle.com/mediator/xpath"

                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"

                xmlns:ns2="http://www.bolivariano.com/dominio/TipoMatriculacion"

                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"

                xmlns:ns3="http://www.bolivariano.com/dominio/FormaPago"

                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"

                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"

                xmlns:ns4="http://www.bolivariano.com/dominio/TipoIdentificador"

                xmlns:tns="http://www.bolivariano.com/mensaje/MensajeOTC"

                xmlns:xsd="http://www.w3.org/2001/XMLSchema"

                xmlns:ns7="http://www.bolivariano.com/dominio/Empresa"

                xmlns:ns8="http://www.bolivariano.com/mensaje/MensajeOTC"

                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"

                exclude-result-prefixes="xsi xsl clr soap wsdl xsd ns1 ns5 ns6 ns10 ns9 ns0 ns2 ns3 ns4 tns ns7 ns8 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap">
  <xsl:template match="/">
    <tns:salidaConsultarDeuda>
      <ns8:codigoError>
        <xsl:text disable-output-escaping="no">0</xsl:text>
      </ns8:codigoError>
      <ns8:formaPago>
        <xsl:text disable-output-escaping="no">COMBO</xsl:text>
      </ns8:formaPago>
      <ns8:mensajeUsuario>
        <xsl:text disable-output-escaping="no">OK</xsl:text>
     </ns8:mensajeUsuario>
      <ns8:recibos>
        <xsl:for-each select="/clr:consultarMontosRecargasResponse/valoresRecarga/valor">
          <ns8:recibo>
            <totalAPagar>
              <xsl:value-of select="."/>
            </totalAPagar>
          </ns8:recibo>  
		</xsl:for-each>		  
      </ns8:recibos>
    </tns:salidaConsultarDeuda>
  </xsl:template>
</xsl:stylesheet>

