<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../otc-nopolicy.wsdl"/>
      <rootElement name="entradaEjecutarPago" namespace="http://www.bolivariano.com/ws/OTCService"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../xsd/CNEL/CNEL_1.wsdl"/>
      <rootElement name="MensajeEntradaPagar" namespace="http://www.bolivariano.com/MensajeCNEL"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 130301.0647.0008) AT [SAT JUN 09 16:26:23 COT 2018]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:ns11="http://www.bolivariano.com/CNEL"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:ns12="http://www.bolivariano.com/EE"
                xmlns:ns1="http://www.bolivariano.com/dominio/DatoAdicional"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:ns14="http://www.bolivariano.com/CoreBB"
                xmlns:ns16="http://www.bolivariano.com/Cuenta"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:ns5="http://www.bolivariano.com/dominio/Convenio"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns6="http://www.bolivariano.com/dominio/Recibo"
                xmlns:ns10="http://www.bolivariano.com/dominio/ListaSeleccion"
                xmlns:ns9="http://www.bolivariano.com/dominio/RegionalArea"
                xmlns:ns0="http://www.bolivariano.com/dominio/Servicio"
                xmlns:ns13="http://www.bolivariano.com/MensajeBolivariano"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:ns17="http://www.bolivariano.com/Recaudo"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ns2="http://www.bolivariano.com/dominio/TipoMatriculacion"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:mcnel="http://www.bolivariano.com/MensajeCNEL"
                xmlns:ns3="http://www.bolivariano.com/dominio/FormaPago"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns4="http://www.bolivariano.com/dominio/TipoIdentificador"
                xmlns:tns="http://www.bolivariano.com/ws/OTCService"
                xmlns:http="http://schemas.xmlsoap.org/wsdl/http/"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:ns15="http://www.bolivariano.com/Producto"
                xmlns:ns18="http://www.bolivariano.com/Cliente"
                xmlns:ns7="http://www.bolivariano.com/dominio/Empresa"
                xmlns:ns19="http://www.bolivariano.com/Comision"
                xmlns:ns8="http://www.bolivariano.com/mensaje/MensajeOTC"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                xmlns:java="java"
                exclude-result-prefixes="xsi xsl ns1 soap wsdl ns5 ns6 ns10 ns9 ns0 ns2 ns3 ns4 tns xsd ns7 ns8 ns11 ns12 ns14 ns16 ns13 ns17 mcnel http ns15 ns18 ns19 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap">
  <xsl:template match="/">
    <mcnel:MensajeEntradaPagar>
      <canal>
        <xsl:value-of select="/ns8:entradaEjecutarPago/ns8:canal"/>
      </canal>
      <depuracion>
        <xsl:text disable-output-escaping="no">0</xsl:text>
      </depuracion>
      <oficina>
        <xsl:value-of select='/ns8:entradaEjecutarPago/ns8:datosAdicionales/ns8:datoAdicional[codigo = "s_ofi"]/valor'/>
      </oficina>
      <terminal>
        <xsl:value-of select='/ns8:entradaEjecutarPago/ns8:datosAdicionales/ns8:datoAdicional[codigo = "s_term"]/valor'/>
      </terminal>
      <transaccion>
        <xsl:text disable-output-escaping="no">62275</xsl:text>
      </transaccion>
      <usuario>
        <xsl:value-of select='/ns8:entradaEjecutarPago/ns8:datosAdicionales/ns8:datoAdicional[codigo = "s_user"]/valor'/>
      </usuario>
      <tipoTransaccionFlujo>
        <xsl:text disable-output-escaping="no">M</xsl:text>
      </tipoTransaccionFlujo>
      <electrica>
        <aplicativoCobis>
          <xsl:text disable-output-escaping="no">N</xsl:text>
        </aplicativoCobis>
        <canalCobranza>
          <xsl:text disable-output-escaping="no">WEB</xsl:text>
        </canalCobranza>
        <chequeComision>
          <xsl:text disable-output-escaping="no">0</xsl:text>
        </chequeComision>
        <codigoAutorizacion>
          <xsl:value-of select='/ns8:entradaEjecutarPago/ns8:datosAdicionales/ns8:datoAdicional[codigo = "s_ssn"]/valor'/>
        </codigoAutorizacion>
				<xsl:choose>
					<xsl:when test="/ns8:entradaEjecutarPago/ns8:canal = 'CNB' and (/ns8:entradaEjecutarPago/ns8:datosAdicionales/ns8:datoAdicional[codigo = 'p_forma_pago']/valor = 'EFE')">
						<debito>
							<xsl:text disable-output-escaping="no">0.00</xsl:text>
						</debito>
					</xsl:when>
					<xsl:when test="/ns8:entradaEjecutarPago/ns8:canal = 'CNB' and (/ns8:entradaEjecutarPago/ns8:datosAdicionales/ns8:datoAdicional[codigo = 'p_forma_pago']/valor = 'DEB')">
						<debito>
							<xsl:value-of select="/ns8:entradaEjecutarPago/ns8:valorPago"/>
						</debito>
					</xsl:when>
					<!--KBastidz TC-->
					<xsl:when test='/ns8:entradaEjecutarPago/ns8:datosAdicionales/ns8:datoAdicional[codigo = "MPA_TC"]'>
                    <debito>
                        <xsl:text disable-output-escaping="no">0.00</xsl:text>
                    </debito>
                    </xsl:when>
					<!--KBastidz TC-->
					<xsl:otherwise>
						<debito>
							<xsl:value-of select="/ns8:entradaEjecutarPago/ns8:valorPago"/>
						</debito>
					</xsl:otherwise>
				</xsl:choose>
				
				<xsl:choose>
					<xsl:when test="/ns8:entradaEjecutarPago/ns8:canal = 'CNB' and (/ns8:entradaEjecutarPago/ns8:datosAdicionales/ns8:datoAdicional[codigo = 'p_forma_pago']/valor = 'EFE')">
						<debitoComision>
							<xsl:text disable-output-escaping="no">0.00</xsl:text>
						</debitoComision>
					</xsl:when>
					<xsl:when test="/ns8:entradaEjecutarPago/ns8:canal = 'CNB' and (/ns8:entradaEjecutarPago/ns8:datosAdicionales/ns8:datoAdicional[codigo = 'p_forma_pago']/valor = 'DEB')">
						<debitoComision>
							<xsl:value-of select="/ns8:entradaEjecutarPago/ns8:valorComision"/>
						</debitoComision>
					</xsl:when>
					<xsl:otherwise>
						<debitoComision>
							<xsl:value-of select="/ns8:entradaEjecutarPago/ns8:valorComision"/>
						</debitoComision>
					</xsl:otherwise>
				</xsl:choose>
				
				<xsl:choose>
					<xsl:when test="/ns8:entradaEjecutarPago/ns8:canal = 'CNB' and (/ns8:entradaEjecutarPago/ns8:datosAdicionales/ns8:datoAdicional[codigo = 'p_forma_pago']/valor = 'EFE')">
						<efectivo>
							<xsl:value-of select="/ns8:entradaEjecutarPago/ns8:valorPago"/>
						</efectivo>
					</xsl:when>
					<xsl:otherwise>
						<efectivo>
							<xsl:text disable-output-escaping="no">0.00</xsl:text>
						</efectivo>
					</xsl:otherwise>
				</xsl:choose>
				
				<xsl:choose>
					<xsl:when test="/ns8:entradaEjecutarPago/ns8:canal = 'CNB' and (/ns8:entradaEjecutarPago/ns8:datosAdicionales/ns8:datoAdicional[codigo = 'p_forma_pago']/valor = 'EFE')">
						<efectivoComision>
							<xsl:value-of select="/ns8:entradaEjecutarPago/ns8:valorComision"/>
						</efectivoComision>
					</xsl:when>
					<xsl:otherwise>
						<efectivoComision>
							<xsl:text disable-output-escaping="no">0.00</xsl:text>
						</efectivoComision>
					</xsl:otherwise>
				</xsl:choose>
        <empresa>
          <xsl:value-of select="/ns8:entradaEjecutarPago/ns8:servicio/codigoConvenio"/>
        </empresa>
        <fechaContable>
          <xsl:value-of select='java:format(java:text.SimpleDateFormat.new("yyyy-MM-dd"), java:util.Date.new())'/>
        </fechaContable>
        <fechaEmision>
		  <xsl:value-of select='java:format(java:text.SimpleDateFormat.new("yyyy-MM-dd&apos;T&apos;HH:mm:ss.SSS"), java:util.Date.new())'/>
          <!--<xsl:value-of select="/ns8:entradaEjecutarPago/ns8:fecha"/>-->
        </fechaEmision>
        <identificacion>
          <xsl:text disable-output-escaping="no">0</xsl:text>
        </identificacion>
        <nombre>
          <xsl:value-of select="/ns8:entradaEjecutarPago/ns8:nombreCliente"/>
        </nombre>
        <secuencialRequerimiento>
          <xsl:value-of select='/ns8:entradaEjecutarPago/ns8:datosAdicionales/ns8:datoAdicional[codigo = "s_ssn"]/valor'/>
        </secuencialRequerimiento>
        <tipoMoneda>
          <xsl:text disable-output-escaping="no">1</xsl:text>
        </tipoMoneda>
        <valorCheque>
          <xsl:text disable-output-escaping="no">0</xsl:text>
        </valorCheque>
        <cuenta>
          <cuenta>
            <xsl:value-of select="/ns8:entradaEjecutarPago/ns8:cuenta"/>
          </cuenta>
          <nombreCuenta>
            <xsl:value-of select="/ns8:entradaEjecutarPago/ns8:cuenta"/>
          </nombreCuenta>
          <tipoCuenta>
            <xsl:value-of select="/ns8:entradaEjecutarPago/ns8:tipoCuenta"/>
          </tipoCuenta>
          <factura>
            <xsl:value-of select='/ns8:entradaEjecutarPago/ns8:datosAdicionales/ns8:datoAdicional[codigo = "factura"]/valor'/>
          </factura>
          <valorReten>
            <xsl:text disable-output-escaping="no">0</xsl:text>
          </valorReten>
        </cuenta>
        <codigoAdquiriente>
          <xsl:text disable-output-escaping="no">007</xsl:text>
        </codigoAdquiriente>
        <codigoAutorizacionCNB>
          <xsl:value-of select='/ns8:entradaEjecutarPago/ns8:datosAdicionales/ns8:datoAdicional[codigo = "s_ssn"]/valor'/>
        </codigoAutorizacionCNB>
        <codigoAutorizador>
          <xsl:choose>
            <xsl:when test="/ns8:entradaEjecutarPago/ns8:servicio/codigoConvenio=4977">
              <xsl:text disable-output-escaping="no">201</xsl:text>
            </xsl:when>
            <xsl:when test="/ns8:entradaEjecutarPago/ns8:servicio/codigoConvenio=825">
              <xsl:text disable-output-escaping="no">301</xsl:text>
            </xsl:when>
            <xsl:when test="/ns8:entradaEjecutarPago/ns8:servicio/codigoConvenio=331">
              <xsl:text disable-output-escaping="no">901</xsl:text>
            </xsl:when>
            <xsl:when test="/ns8:entradaEjecutarPago/ns8:servicio/codigoConvenio=1127">
              <xsl:text disable-output-escaping="no">101</xsl:text>
            </xsl:when>
            <xsl:when test="/ns8:entradaEjecutarPago/ns8:servicio/codigoConvenio=1330">
              <xsl:text disable-output-escaping="no">601</xsl:text>
            </xsl:when>
            <xsl:when test="/ns8:entradaEjecutarPago/ns8:servicio/codigoConvenio=1719">
              <xsl:text disable-output-escaping="no">401</xsl:text>
            </xsl:when>
            <xsl:when test="/ns8:entradaEjecutarPago/ns8:servicio/codigoConvenio=4978">
              <xsl:text disable-output-escaping="no">501</xsl:text>
            </xsl:when>
            <xsl:when test="/ns8:entradaEjecutarPago/ns8:servicio/codigoConvenio=4979">
              <xsl:text disable-output-escaping="no">701</xsl:text>
            </xsl:when>
            <xsl:when test="/ns8:entradaEjecutarPago/ns8:servicio/codigoConvenio=4980">
              <xsl:text disable-output-escaping="no">801</xsl:text>
            </xsl:when>
            <xsl:when test="/ns8:entradaEjecutarPago/ns8:servicio/codigoConvenio=4981">
              <xsl:text disable-output-escaping="no">102</xsl:text>
            </xsl:when>
          </xsl:choose>
        </codigoAutorizador>
        <codigoOperador>
          <xsl:text disable-output-escaping="no">000998</xsl:text>
        </codigoOperador>
        <codigoSeguridad>
          <xsl:text disable-output-escaping="no">007224605</xsl:text>
        </codigoSeguridad>
        <codigoSuministro>
          <xsl:value-of select="/ns8:entradaEjecutarPago/ns8:servicio/identificador"/>
        </codigoSuministro>
        <codigoTerminal>
          <xsl:text disable-output-escaping="no">0007000000000998</xsl:text>
        </codigoTerminal>
        <consComision>
          <xsl:text disable-output-escaping="no">0</xsl:text>
        </consComision>
        <digver>
          <xsl:text disable-output-escaping="no">3</xsl:text>
        </digver>
        <fechaCompensacion>
           <xsl:value-of select='java:format(java:text.SimpleDateFormat.new("yyyy-MM-dd&apos;T&apos;HH:mm:ss.SSS"), java:util.Date.new())'/>
        </fechaCompensacion>
        <fechaTransaccionLocal>
		  <xsl:value-of select='java:format(java:text.SimpleDateFormat.new("yyyy-MM-dd&apos;T&apos;HH:mm:ss.SSS"), java:util.Date.new())'/>
        </fechaTransaccionLocal>
        <fechaVencimiento>
		  <xsl:value-of select='java:format(java:text.SimpleDateFormat.new("yyyy-MM-dd&apos;T&apos;HH:mm:ss.SSS"), java:util.Date.new())'/>
        </fechaVencimiento>
        <grupo>
          <xsl:text disable-output-escaping="no">4994</xsl:text>
        </grupo>
        <monedaProveedor>
          <xsl:text disable-output-escaping="no">840</xsl:text>
        </monedaProveedor>
        <secuencialAdquiriente>
          <xsl:value-of select='/ns8:entradaEjecutarPago/ns8:datosAdicionales/ns8:datoAdicional[codigo = "s_ssn"]/valor'/>
        </secuencialAdquiriente>
        <secuencialAutorizador>
          <xsl:text disable-output-escaping="no">102458</xsl:text>
        </secuencialAutorizador>
        <secuencialMT>
          <xsl:text disable-output-escaping="no">000000</xsl:text>
        </secuencialMT>
        <servicio>
          <xsl:text disable-output-escaping="no">3</xsl:text>
        </servicio>
        <servicioProveedor>
          <xsl:text disable-output-escaping="no">001</xsl:text>
        </servicioProveedor>
        <tipoTransaccion>
          <xsl:text disable-output-escaping="no">000101</xsl:text>
        </tipoTransaccion>
        <totalPendienteProv>
          <xsl:value-of select='/ns8:entradaEjecutarPago/ns8:datosAdicionales/ns8:datoAdicional[codigo = "valor"]/valor'/>
        </totalPendienteProv>
        <valorPagado>
          <xsl:value-of select="round(/ns8:entradaEjecutarPago/ns8:valorPago * 100)"/>
        </valorPagado>
        <valorRetenProv>
          <xsl:text disable-output-escaping="no">0</xsl:text>
        </valorRetenProv>
		<!--KBastidz TC-->
		<xsl:if test='/ns8:entradaEjecutarPago/ns8:datosAdicionales/ns8:datoAdicional[codigo = "MPA_TC"]'>
			<formaPago>
				<tarjeta>
					<tarjeta>
						<xsl:value-of select='/ns8:entradaEjecutarPago/ns8:datosAdicionales/ns8:datoAdicional[codigo = "MPA_TC"]/valor'/>
					</tarjeta>
					<valor>
						<xsl:value-of select="format-number(/ns8:entradaEjecutarPago/ns8:valorPago,'0.00')"/>
					</valor>
					<valorComision>
						<xsl:value-of select="format-number(/ns8:entradaEjecutarPago/ns8:valorComision,'0.00')"/>
					</valorComision>
					<mesesDiferido>
						<xsl:value-of select='/ns8:entradaEjecutarPago/ns8:datosAdicionales/ns8:datoAdicional[codigo = "FPA_TC"]/valor'/>
					</mesesDiferido>
				</tarjeta>
			</formaPago>
		</xsl:if>
		<!--KBastidz TC-->
      </electrica>
      <comision>
        <baseImponibleProv>
          <xsl:text disable-output-escaping="no">0</xsl:text>
        </baseImponibleProv>
        <costoComision>
          <xsl:text disable-output-escaping="no">0</xsl:text>
        </costoComision>
      </comision>
      <informacionCore>
        <modoCorreccion>N</modoCorreccion>
        <rolBPM>
          <xsl:value-of select='/ns8:entradaEjecutarPago/ns8:datosAdicionales/ns8:datoAdicional[codigo = "s_rol"]/valor'/>
        </rolBPM>
        <secuencial>
          <xsl:value-of select='/ns8:entradaEjecutarPago/ns8:datosAdicionales/ns8:datoAdicional[codigo = "s_ssn"]/valor'/>
        </secuencial>
        <servidor>
          <xsl:value-of select='/ns8:entradaEjecutarPago/ns8:datosAdicionales/ns8:datoAdicional[codigo = "s_srv"]/valor'/>
        </servidor>
        <servidorLocal>
          <xsl:value-of select='/ns8:entradaEjecutarPago/ns8:datosAdicionales/ns8:datoAdicional[codigo = "s_lsrv"]/valor'/>
        </servidorLocal>
      </informacionCore>
			<xsl:choose>
				<xsl:when test="/ns8:entradaEjecutarPago/ns8:canal = 'CNB'">
					<CNB>
						<autorizacion>
							<xsl:value-of select="/ns8:entradaEjecutarPago/ns8:datosAdicionales/ns8:datoAdicional[codigo = 'p_autorizacionCNB']/valor"/>
						</autorizacion>
						<comercio>
							<xsl:value-of select="/ns8:entradaEjecutarPago/ns8:datosAdicionales/ns8:datoAdicional[codigo = 'p_comercio']/valor"/>
						</comercio>
						<terminalID>
							<xsl:value-of select="/ns8:entradaEjecutarPago/ns8:datosAdicionales/ns8:datoAdicional[codigo = 'p_terminalID']/valor"/>
						</terminalID>
						<agencia>
							<xsl:value-of select="/ns8:entradaEjecutarPago/ns8:datosAdicionales/ns8:datoAdicional[codigo = 'p_agencia']/valor"/>
						</agencia>
						<red>
							<xsl:value-of select="/ns8:entradaEjecutarPago/ns8:datosAdicionales/ns8:datoAdicional[codigo = 'p_red']/valor"/>
						</red>
						<secuencial>
							<xsl:value-of select='/ns8:entradaEjecutarPago/ns8:datosAdicionales/ns8:datoAdicional[codigo = "s_ssn"]/valor'/>
						</secuencial>
						<valor>
							<xsl:value-of select="/ns8:entradaEjecutarPago/ns8:valorPago"/>
						</valor>
						<nombreCliente>
							<xsl:value-of select='/ns8:entradaEjecutarPago/ns8:datosAdicionales/ns8:datoAdicional[codigo = "p_nombreCliente"]/valor'/>
						</nombreCliente>
						<identificacionCliente>
							<xsl:value-of select='/ns8:entradaEjecutarPago/ns8:datosAdicionales/ns8:datoAdicional[codigo = "p_identificacionCliente"]/valor'/>
						</identificacionCliente>
						<tipoTransaccion>P</tipoTransaccion>						
					</CNB>
				</xsl:when>
			</xsl:choose>
    </mcnel:MensajeEntradaPagar>
  </xsl:template>
</xsl:stylesheet>
