<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../xsd/CNEL/CNEL_1.wsdl"/>
      <rootElement name="MensajeSalidaPagar" namespace="http://www.bolivariano.com/MensajeCNEL"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../otc-nopolicy.wsdl"/>
      <rootElement name="salidaEjecutarPago" namespace="http://www.bolivariano.com/ws/OTCService"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 130301.0647.0008) AT [TUE JUN 12 10:30:47 COT 2018]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:tns="http://www.bolivariano.com/CNEL"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:ns0="http://www.bolivariano.com/EE"
                xmlns:ns8="http://www.bolivariano.com/dominio/DatoAdicional"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:ns2="http://www.bolivariano.com/CoreBB"
                xmlns:ns4="http://www.bolivariano.com/Cuenta"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:ns14="http://www.bolivariano.com/dominio/Convenio"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns15="http://www.bolivariano.com/dominio/Recibo"
                xmlns:ns18="http://www.bolivariano.com/dominio/RegionalArea"
                xmlns:ns19="http://www.bolivariano.com/dominio/ListaSeleccion"
                xmlns:ns10="http://www.bolivariano.com/dominio/Servicio"
                xmlns:ns1="http://www.bolivariano.com/MensajeBolivariano"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:ns5="http://www.bolivariano.com/Recaudo"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:ns11="http://www.bolivariano.com/dominio/TipoMatriculacion"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:mcnel="http://www.bolivariano.com/MensajeCNEL"
                xmlns:ns12="http://www.bolivariano.com/dominio/FormaPago"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns13="http://www.bolivariano.com/dominio/TipoIdentificador"
                xmlns:ns9="http://www.bolivariano.com/ws/OTCService"
                xmlns:http="http://schemas.xmlsoap.org/wsdl/http/"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:ns3="http://www.bolivariano.com/Producto"
                xmlns:java="java" xmlns:ns6="http://www.bolivariano.com/Cliente"
                xmlns:ns16="http://www.bolivariano.com/dominio/Empresa"
                xmlns:ns7="http://www.bolivariano.com/Comision"
                xmlns:ns17="http://www.bolivariano.com/mensaje/MensajeOTC"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl tns ns0 soap ns2 ns4 wsdl ns1 ns5 mcnel http xsd ns3 ns6 ns7 ns8 ns14 ns15 ns18 ns19 ns10 ns11 ns12 ns13 ns9 ns16 ns17 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap">
  <xsl:template match="/">
    <ns17:salidaEjecutarPago>
      <ns17:codigoError>
        <xsl:value-of select="/mcnel:MensajeSalidaPagar/codigoError"/>
      </ns17:codigoError>
      <ns17:datosAdicionales>
        <ns17:datoAdicional>
          <codigo>
            <xsl:text disable-output-escaping="no">autorizacion</xsl:text>
          </codigo>
          <etiqueta>
            <xsl:text disable-output-escaping="no">No. autorizacion:</xsl:text>
          </etiqueta>
          <editable>
            <xsl:text disable-output-escaping="no">false</xsl:text>
          </editable>
          <valor>
            <xsl:value-of select="/mcnel:MensajeSalidaPagar/electrica/secuencialAdquiriente"/>
          </valor>
          <visible>
            <xsl:text disable-output-escaping="no">true</xsl:text>
          </visible>
        </ns17:datoAdicional>
                <ns17:datoAdicional>
          <codigo>
            <xsl:text disable-output-escaping="no">horario</xsl:text>
          </codigo>
          <valor>
            <xsl:value-of select="/mcnel:MensajeSalidaPagar/electrica/horario"/>
          </valor>
        </ns17:datoAdicional>
      </ns17:datosAdicionales>
      <ns17:mensajeUsuario>
        <xsl:value-of select="/mcnel:MensajeSalidaPagar/mensajeUsuario"/>
      </ns17:mensajeUsuario>
      <ns17:mensajeSistema>
        <xsl:value-of select="/mcnel:MensajeSalidaPagar/mensajeSistema"/>
      </ns17:mensajeSistema>
      <ns17:fechaPago>
        <xsl:value-of select="/mcnel:MensajeSalidaPagar/electrica/fechaEfectiva"/>
      </ns17:fechaPago>
      <ns17:fechaDebito>
        <xsl:value-of select='java:format(java:text.SimpleDateFormat.new("yyyy-MM-dd&apos;T&apos;HH:mm:ss.SSS"), java:util.Date.new())'/>
      </ns17:fechaDebito>
      <ns17:referencia>
        <xsl:value-of select="/mcnel:MensajeSalidaPagar/electrica/secuencialAutorizador"/>
      </ns17:referencia>
    </ns17:salidaEjecutarPago>
  </xsl:template>
</xsl:stylesheet>
