<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../otc-nopolicy.wsdl"/>
      <rootElement name="entradaEjecutarReverso" namespace="http://www.bolivariano.com/ws/OTCService"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../CNT.wsdl"/>
      <rootElement name="MensajeEntradaConsultar" namespace="http://www.bolivariano.com/MensajeCNT"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 130301.0647.0008) AT [THU MAY 24 19:08:15 COT 2018]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:mcnt="http://www.bolivariano.com/MensajeCNT"
                xmlns:ns1="http://www.bolivariano.com/dominio/DatoAdicional"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:ns13="http://www.bolivariano.com/CoreBB"
                xmlns:ns14="http://www.bolivariano.com/Cuenta"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:ns5="http://www.bolivariano.com/dominio/Convenio"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns6="http://www.bolivariano.com/dominio/Recibo"
                xmlns:ns10="http://www.bolivariano.com/dominio/ListaSeleccion"
                xmlns:ns9="http://www.bolivariano.com/dominio/RegionalArea"
                xmlns:ns0="http://www.bolivariano.com/dominio/Servicio"
                xmlns:ns12="http://www.bolivariano.com/MensajeBolivariano"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:ns16="http://www.bolivariano.com/Recaudo"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ns2="http://www.bolivariano.com/dominio/TipoMatriculacion"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:ns3="http://www.bolivariano.com/dominio/FormaPago"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns4="http://www.bolivariano.com/dominio/TipoIdentificador"
                xmlns:tns="http://www.bolivariano.com/ws/OTCService"
                xmlns:http="http://schemas.xmlsoap.org/wsdl/http/"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:ns15="http://www.bolivariano.com/Producto"
                xmlns:ns17="http://www.bolivariano.com/Cliente"
                xmlns:ns11="http://www.bolivariano.com/CNT"
                xmlns:ns7="http://www.bolivariano.com/dominio/Empresa"
                xmlns:ns18="http://www.bolivariano.com/Comision"
                xmlns:ns8="http://www.bolivariano.com/mensaje/MensajeOTC"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                xmlns:java="java"
                exclude-result-prefixes="xsi xsl ns1 soap wsdl ns5 ns6 ns10 ns9 ns0 ns2 ns3 ns4 tns xsd ns7 ns8 mcnt ns13 ns14 ns12 ns16 http ns15 ns17 ns11 ns18 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap">
  <xsl:template match="/">
    <mcnt:MensajeEntradaReversarPago>
      <canal>
        <xsl:value-of select="/ns8:entradaEjecutarReverso/ns8:canal"/>
      </canal>
      <depuracion>
        <xsl:value-of select="/ns8:entradaEjecutarReverso/ns8:depuracion"/>
      </depuracion>
      <oficina>
        <xsl:value-of select="/ns8:entradaEjecutarReverso/ns8:oficina"/>
      </oficina>
      <terminal>
        <!--   TODO enriquecer  parámetros cobis  s_term-->
        <xsl:text disable-output-escaping="no">VIRTUAL_BB</xsl:text>
      </terminal>
      <transaccion>
        <xsl:value-of select="/ns8:entradaEjecutarReverso/ns8:transaccion"/>
      </transaccion>
      <usuario>
        <xsl:value-of select="/ns8:entradaEjecutarReverso/ns8:usuario"/>
      </usuario>
      <tipoTransaccionFlujo/>
      <cnt>
        <aplicativoCobis>
          <xsl:text disable-output-escaping="no">N</xsl:text>
        </aplicativoCobis>
        <autorizacion>
          <xsl:text disable-output-escaping="no">N</xsl:text>
        </autorizacion>        
        <codigoAutorizacion>
          <xsl:value-of select="/ns8:entradaEjecutarReverso/ns8:secuencial"/>
        </codigoAutorizacion>
        <xsl:choose>
          <xsl:when test="/ns8:entradaEjecutarPago/ns8:servicio/codigoEmpresa = '5482' or (/ns8:entradaEjecutarReverso/ns8:datosAdicionales/ns8:datoAdicional[codigo = 'p_codigoEmpresa']/valor = '5482')">
            <codigoComercio>
              <xsl:text disable-output-escaping="no">002</xsl:text>
            </codigoComercio>
          </xsl:when>
          <xsl:otherwise>
            <codigoComercio>
              <xsl:text disable-output-escaping="no">001</xsl:text>
            </codigoComercio>
          </xsl:otherwise>
        </xsl:choose>
        <xsl:choose>
          <xsl:when test="/ns8:entradaEjecutarPago/ns8:servicio/codigoEmpresa = '5482' or (/ns8:entradaEjecutarReverso/ns8:datosAdicionales/ns8:datoAdicional[codigo = 'p_codigoEmpresa']/valor = '5482')">
            <codigoProveedor>
              <xsl:text disable-output-escaping="no">000003</xsl:text>
            </codigoProveedor>
          </xsl:when>
          <xsl:otherwise>
            <codigoProveedor>
              <xsl:text disable-output-escaping="no">001028</xsl:text>
            </codigoProveedor>
          </xsl:otherwise>
        </xsl:choose>
		<xsl:choose>
			<xsl:when test="/ns8:entradaEjecutarReverso/ns8:canal = 'CNB' and (/ns8:entradaEjecutarReverso/ns8:datosAdicionales/ns8:datoAdicional[codigo = 'p_forma_pago']/valor = 'EFE')">
				<debito>
					<xsl:text disable-output-escaping="no">0.00</xsl:text>
				</debito>
			</xsl:when>
			<xsl:when test="/ns8:entradaEjecutarReverso/ns8:canal = 'CNB' and (/ns8:entradaEjecutarReverso/ns8:datosAdicionales/ns8:datoAdicional[codigo = 'p_forma_pago']/valor = 'DEB')">
				<debito>
					<xsl:value-of select="/ns8:entradaEjecutarReverso/ns8:valorPago"/>
				</debito>
			</xsl:when>
			<xsl:otherwise>
				<debito>
					<xsl:value-of select="/ns8:entradaEjecutarReverso/ns8:valorPago"/>
				</debito>
			</xsl:otherwise>
		</xsl:choose>
			
		<xsl:choose>
			<xsl:when test="/ns8:entradaEjecutarReverso/ns8:canal = 'CNB' and (/ns8:entradaEjecutarReverso/ns8:datosAdicionales/ns8:datoAdicional[codigo = 'p_forma_pago']/valor = 'EFE')">
				<debitoComision>
					<xsl:text disable-output-escaping="no">0.00</xsl:text>
				</debitoComision>
			</xsl:when>
			<xsl:when test="/ns8:entradaEjecutarReverso/ns8:canal = 'CNB' and (/ns8:entradaEjecutarReverso/ns8:datosAdicionales/ns8:datoAdicional[codigo = 'p_forma_pago']/valor = 'DEB')">
				<debitoComision>
					<xsl:value-of select="/ns8:entradaEjecutarReverso/ns8:valorComision"/>
				</debitoComision>
			</xsl:when>
			<xsl:otherwise>
				<debitoComision>
					<xsl:value-of select="/ns8:entradaEjecutarReverso/ns8:valorComision"/>
				</debitoComision>
			</xsl:otherwise>
		</xsl:choose>
		
		<xsl:choose>		
			<xsl:when test="/ns8:entradaEjecutarReverso/ns8:canal = 'CNB' and (/ns8:entradaEjecutarReverso/ns8:datosAdicionales/ns8:datoAdicional[codigo = 'p_forma_pago']/valor = 'EFE')">
				<efectivo>
					<!--xsl:value-of select="/tns:entradaEjecutarReverso/ns8:valorPago"/-->
          	<xsl:value-of select="/ns8:entradaEjecutarReverso/ns8:valorPago"/>
				</efectivo>
			</xsl:when>
			<xsl:otherwise>
				<efectivo>
					<xsl:text disable-output-escaping="no">0.00</xsl:text>
				</efectivo>
			</xsl:otherwise>
		</xsl:choose>
			
		<xsl:choose>
			<xsl:when test="/ns8:entradaEjecutarReverso/ns8:canal  = 'CNB' and (/ns8:entradaEjecutarReverso/ns8:datosAdicionales/ns8:datoAdicional[codigo = 'p_forma_pago']/valor = 'EFE')">
				<efectivoComision>
					<!--xsl:value-of select="/tns:entradaEjecutarReverso/ns8:valorComision"/-->
          <xsl:value-of select="/ns8:entradaEjecutarReverso/ns8:valorComision"/>
				</efectivoComision>
			</xsl:when>
			<xsl:otherwise>
				<efectivoComision>
					<xsl:text disable-output-escaping="no">0.00</xsl:text>
				</efectivoComision>
			</xsl:otherwise>
		</xsl:choose>
		
		<xsl:choose>		
			<xsl:when test="/ns8:entradaEjecutarReverso/ns8:canal = 'CNB'">
				<empresa>
					<xsl:value-of select="/ns8:entradaEjecutarReverso/ns8:datosAdicionales/ns8:datoAdicional[codigo = 'p_codigoEmpresa']/valor"/>
				</empresa>
			</xsl:when>
			<xsl:otherwise>
				<empresa>
					<xsl:value-of select="/ns8:entradaEjecutarReverso/ns8:servicio/codigoEmpresa"/>
				</empresa>
			</xsl:otherwise>
		</xsl:choose>
        <identificacion>
          <xsl:text disable-output-escaping="no">0000000000000000</xsl:text>
        </identificacion>
        <nombre>
          <xsl:value-of select="/ns8:entradaEjecutarReverso/ns8:nombreCliente"/>
        </nombre>
        <!-- posible quemado 0000
        <numeroTarjeta>
          <xsl:text disable-output-escaping="no">o_cod_reverso si outHmolo_serv=15</xsl:text>
        </numeroTarjeta>-->
        <opcion>
          <xsl:text disable-output-escaping="no">T</xsl:text>
        </opcion>
        <secuencialRequerimiento>
          <xsl:value-of select="/ns8:entradaEjecutarReverso/ns8:secuencial"/>
        </secuencialRequerimiento>
        <tipoMoneda>
          <xsl:value-of select="/ns8:entradaEjecutarReverso/ns8:moneda"/>
        </tipoMoneda>
        <cuenta>
          <cuenta>
            <xsl:value-of select="/ns8:entradaEjecutarReverso/ns8:cuenta"/>
          </cuenta>
          <nombreCuenta>
            <xsl:value-of select="/ns8:entradaEjecutarReverso/ns8:nombreCliente"/>
          </nombreCuenta>
          <origen>
            <xsl:text disable-output-escaping="no">02</xsl:text>
          </origen>
          <tipoCuenta>
            <xsl:value-of select="/ns8:entradaEjecutarReverso/ns8:tipoCuenta"/>
          </tipoCuenta>
        </cuenta>
        <codigoTransaccion>
          <xsl:text disable-output-escaping="no">000002</xsl:text>
        </codigoTransaccion>
        <xsl:choose>
					<xsl:when test="/ns8:entradaEjecutarReverso/ns8:canal = 'CNB'">
						<fechaPac>
           <xsl:value-of select='java:format(java:text.SimpleDateFormat.new("yyyy-MM-dd&apos;T&apos;HH:mm:ss.SSS"), java:util.Date.new())'/>
        </fechaPac>
					</xsl:when>		
					<xsl:otherwise>
						 <fechaPac>
         <!--   TODO fecha ahorita get datetime-->
          <xsl:text disable-output-escaping="no">2018-05-24T14:28:57</xsl:text>
        </fechaPac>
					</xsl:otherwise>
				</xsl:choose>
        <numFactura/>
        <secuencialTransaccion>
          <xsl:value-of select="/ns8:entradaEjecutarReverso/ns8:secuencial"/>
        </secuencialTransaccion>
        <xsl:choose>
          <xsl:when test="/ns8:entradaEjecutarPago/ns8:servicio/codigoEmpresa = '5482' or (/ns8:entradaEjecutarReverso/ns8:datosAdicionales/ns8:datoAdicional[codigo = 'p_codigoEmpresa']/valor = '5482')">
            <servicio>
              <xsl:text disable-output-escaping="no">1</xsl:text>
            </servicio>
          </xsl:when>
          <xsl:otherwise>
            <servicio>
              <xsl:text disable-output-escaping="no">2</xsl:text>
            </servicio>
          </xsl:otherwise>
        </xsl:choose>
        <telefono>
          <xsl:value-of select="/ns8:entradaEjecutarReverso/ns8:servicio/identificador"/>
        </telefono>
        <valorTotal>
          <xsl:value-of select="/ns8:entradaEjecutarReverso/ns8:valorPago"/>
        </valorTotal>
        <xsl:choose>
          <xsl:when test='/ns8:entradaEjecutarPago/ns8:servicio/codigoEmpresa = "5482"'>
            <TipoServicio>
              <xsl:text disable-output-escaping="no">002</xsl:text>
            </TipoServicio>
          </xsl:when>
          <xsl:otherwise>
            <TipoServicio>
              <xsl:text disable-output-escaping="no">001</xsl:text>
            </TipoServicio>
          </xsl:otherwise>
        </xsl:choose>
      </cnt>
      <comision>
        <costoComision>
          <xsl:value-of select="/ns8:entradaEjecutarReverso/ns8:valorComision"/>
        </costoComision>
      </comision>
      <informacionCore>
        <xsl:choose>
					<xsl:when test="/ns8:entradaEjecutarReverso/ns8:canal = 'CNB'">
						<fechaProcesoKernel>
           <xsl:value-of select='java:format(java:text.SimpleDateFormat.new("yyyy-MM-dd&apos;T&apos;HH:mm:ss.SSS"), java:util.Date.new())'/>
        </fechaProcesoKernel>
		<reversoTransaccion>
            <xsl:value-of select='/ns8:entradaEjecutarReverso/ns8:datosAdicionales/ns8:datoAdicional[codigo = "p_reversoTransaccion"]/valor'/>
        </reversoTransaccion>
					</xsl:when>		
					<xsl:otherwise>
								<!--   TODO enriquecer  parámetros cobis  s_date-->
        <fechaProcesoKernel>
          <xsl:text disable-output-escaping="no">2018-05-24T14:28:57</xsl:text>
        </fechaProcesoKernel>
		 <!--   TODO enriquecer  parámetros cobis  s_ssn_corr-->
        <reversoTransaccion>
            <xsl:text disable-output-escaping="no">1234567802</xsl:text>
        </reversoTransaccion>
					</xsl:otherwise>
				</xsl:choose>
        <modoCorreccion>
          <xsl:text disable-output-escaping="no">S</xsl:text>
        </modoCorreccion>
       
        <!--   TODO enriquecer  parámetros cobis  s_rol-->
        <rolBPM>
          <xsl:text disable-output-escaping="no">252</xsl:text>
        </rolBPM>

        <secuencial>
          <xsl:value-of select="/ns8:entradaEjecutarReverso/ns8:secuencial"/>
        </secuencial>        
        
        <!--   TODO enriquecer  parámetros cobis  s_srv-->
        <servidor>
          <xsl:text disable-output-escaping="no">SRVDESA2</xsl:text>
        </servidor>
        <!--   TODO enriquecer  parámetros cobis  s_lsrv-->
        <servidorLocal>
          <xsl:text disable-output-escaping="no">SRVDESA2</xsl:text>
        </servidorLocal>
      </informacionCore>
	  <xsl:choose>
			<xsl:when test="/ns8:entradaEjecutarReverso/ns8:canal = 'CNB'">
				<CNB>
					<autorizacion>			  
						<xsl:value-of select="/ns8:entradaEjecutarReverso/ns8:datosAdicionales/ns8:datoAdicional[codigo = 'p_autorizacionCNB']/valor"/>
					</autorizacion>
					<comercio>
						<xsl:value-of select="/ns8:entradaEjecutarReverso/ns8:datosAdicionales/ns8:datoAdicional[codigo = 'p_comercio']/valor"/>
					</comercio>
					<terminalID>
						<xsl:value-of select="/ns8:entradaEjecutarReverso/ns8:datosAdicionales/ns8:datoAdicional[codigo = 'p_terminalID']/valor"/>
					</terminalID>
					<agencia>
						<xsl:value-of select="/ns8:entradaEjecutarReverso/ns8:datosAdicionales/ns8:datoAdicional[codigo = 'p_agencia']/valor"/>
					</agencia>
					<red>
						<xsl:value-of select="/ns8:entradaEjecutarReverso/ns8:datosAdicionales/ns8:datoAdicional[codigo = 'p_red']/valor"/>
					</red>
					<secuencial>
						<xsl:value-of select='/ns8:entradaEjecutarReverso/ns8:datosAdicionales/ns8:datoAdicional[codigo = "s_ssn"]/valor'/>
					</secuencial>
					<valor>
						<xsl:value-of select="/ns8:entradaEjecutarReverso/ns8:valorPago"/>
					</valor>
					<nombreCliente>
						<xsl:value-of select='/ns8:entradaEjecutarReverso/ns8:datosAdicionales/ns8:datoAdicional[codigo = "p_nombreCliente"]/valor'/>
					</nombreCliente>
					<identificacionCliente>
						<xsl:value-of select='/ns8:entradaEjecutarReverso/ns8:datosAdicionales/ns8:datoAdicional[codigo = "p_identificacionCliente"]/valor'/>
					</identificacionCliente>
					<modoCorreccion>
						<xsl:text disable-output-escaping="no">S</xsl:text>
					</modoCorreccion>
					<reversoTransaccion>
               			<xsl:value-of select='/ns8:entradaEjecutarReverso/ns8:datosAdicionales/ns8:datoAdicional[codigo = "p_reversoTransaccion"]/valor'/>
					</reversoTransaccion>
          <tipoTransaccion>R</tipoTransaccion>
           <formaPago>
							<xsl:value-of select='/ns8:entradaEjecutarReverso/ns8:datosAdicionales/ns8:datoAdicional[codigo = "p_forma_pago"]/valor'/>
						</formaPago>	
				</CNB>
			</xsl:when>
		</xsl:choose>
    </mcnt:MensajeEntradaReversarPago>
  </xsl:template>
</xsl:stylesheet>
