<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../CNT.wsdl"/>
      <rootElement name="MensajeSalidaPagar" namespace="http://www.bolivariano.com/MensajeCNT"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../otc-nopolicy.wsdl"/>
      <rootElement name="salidaEjecutarPago" namespace="http://www.bolivariano.com/ws/OTCService"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 130301.0647.0008) AT [THU MAY 24 17:10:02 COT 2018]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:mcnt="http://www.bolivariano.com/MensajeCNT"
                xmlns:ns7="http://www.bolivariano.com/dominio/DatoAdicional"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:ns1="http://www.bolivariano.com/CoreBB"
                xmlns:ns2="http://www.bolivariano.com/Cuenta"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:ns13="http://www.bolivariano.com/dominio/Convenio"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns14="http://www.bolivariano.com/dominio/Recibo"
                xmlns:ns18="http://www.bolivariano.com/dominio/ListaSeleccion"
                xmlns:ns17="http://www.bolivariano.com/dominio/RegionalArea"
                xmlns:ns9="http://www.bolivariano.com/dominio/Servicio"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:ns0="http://www.bolivariano.com/MensajeBolivariano"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:ns4="http://www.bolivariano.com/Recaudo"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:ns10="http://www.bolivariano.com/dominio/TipoMatriculacion"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:ns11="http://www.bolivariano.com/dominio/FormaPago"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns12="http://www.bolivariano.com/dominio/TipoIdentificador"
                xmlns:ns8="http://www.bolivariano.com/ws/OTCService"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:http="http://schemas.xmlsoap.org/wsdl/http/"
                xmlns:ns3="http://www.bolivariano.com/Producto"
                xmlns:ns15="http://www.bolivariano.com/dominio/Empresa"
                xmlns:ns5="http://www.bolivariano.com/Cliente"
                xmlns:tns="http://www.bolivariano.com/CNT"
                xmlns:ns16="http://www.bolivariano.com/mensaje/MensajeOTC"
                xmlns:ns6="http://www.bolivariano.com/Comision"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
				xmlns:java="java"
                exclude-result-prefixes="xsi xsl mcnt soap ns1 ns2 wsdl ns0 ns4 xsd http ns3 ns5 tns ns6 ns7 ns13 ns14 ns18 ns17 ns9 ns10 ns11 ns12 ns8 ns15 ns16 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap">
  <xsl:template match="/">
    <ns16:salidaEjecutarPago>
      <ns16:codigoError>
        <xsl:value-of select="/mcnt:MensajeSalidaPagar/codigoError"/>
      </ns16:codigoError>
      
      
      <xsl:choose>
        <xsl:when test="/mcnt:MensajeSalidaPagar/codigoError !=''">
          <ns16:codigoError>
            <xsl:value-of select="/mcnt:MensajeSalidaPagar/codigoError"/>
          </ns16:codigoError>
        </xsl:when>
        <xsl:otherwise>
          <ns16:codigoError>
            <xsl:text disable-output-escaping="no">0</xsl:text>
          </ns16:codigoError>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="/mcnt:MensajeSalidaPagar/codigoError !=''">
          <ns16:mensajeUsuario>
            <xsl:value-of select="/mcnt:MensajeSalidaPagar/mensajeUsuario"/>
          </ns16:mensajeUsuario>
        </xsl:when>
        <xsl:otherwise>
          <ns16:mensajeUsuario>
            <xsl:text disable-output-escaping="no">Transaccion ok</xsl:text>
          </ns16:mensajeUsuario>
        </xsl:otherwise>
      </xsl:choose>
        <ns16:fechaDebito>
          <xsl:value-of select='java:format(java:text.SimpleDateFormat.new("yyyy-MM-dd&apos;T&apos;HH:mm:ss.SSS"), java:util.Date.new())'/>
        </ns16:fechaDebito>
        <ns16:fechaPago>
               <xsl:value-of select="/mcnt:MensajeSalidaPagar/CNT/fechaContable"/> 
          </ns16:fechaPago>
          
        <ns16:referencia>
          <xsl:value-of select="/mcnt:MensajeSalidaPagar/CNT/secuencialTransaccionReverso"/>
        </ns16:referencia>
      <ns16:datosAdicionales>
				<ns16:datoAdicional>
					<codigo>horario</codigo>
					<valor>
						<xsl:value-of select="/mcnt:MensajeSalidaPagar/CNT/horario"/>
					</valor>
				</ns16:datoAdicional>
			</ns16:datosAdicionales>

    </ns16:salidaEjecutarPago>
  </xsl:template>
</xsl:stylesheet>
