<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../otc-nopolicy.wsdl"/>
      <rootElement name="entradaConsultarDeuda" namespace="http://www.bolivariano.com/ws/OTCService"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../CNT.wsdl"/>
      <rootElement name="MensajeEntradaConsultar" namespace="http://www.bolivariano.com/MensajeCNT"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 130301.0647.0008) AT [THU MAY 24 15:31:09 COT 2018]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:mcnt="http://www.bolivariano.com/MensajeCNT"
                xmlns:ns1="http://www.bolivariano.com/dominio/DatoAdicional"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:ns13="http://www.bolivariano.com/CoreBB"
                xmlns:ns14="http://www.bolivariano.com/Cuenta"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:ns5="http://www.bolivariano.com/dominio/Convenio"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns6="http://www.bolivariano.com/dominio/Recibo"
                xmlns:ns10="http://www.bolivariano.com/dominio/ListaSeleccion"
                xmlns:ns9="http://www.bolivariano.com/dominio/RegionalArea"
                xmlns:ns0="http://www.bolivariano.com/dominio/Servicio"
                xmlns:ns12="http://www.bolivariano.com/MensajeBolivariano"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:ns16="http://www.bolivariano.com/Recaudo"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ns2="http://www.bolivariano.com/dominio/TipoMatriculacion"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:ns3="http://www.bolivariano.com/dominio/FormaPago"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns4="http://www.bolivariano.com/dominio/TipoIdentificador"
                xmlns:tns="http://www.bolivariano.com/ws/OTCService"
                xmlns:http="http://schemas.xmlsoap.org/wsdl/http/"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:ns15="http://www.bolivariano.com/Producto"
                xmlns:ns17="http://www.bolivariano.com/Cliente"
                xmlns:ns11="http://www.bolivariano.com/CNT"
                xmlns:java="java"
                xmlns:ns7="http://www.bolivariano.com/dominio/Empresa"
                xmlns:ns18="http://www.bolivariano.com/Comision"
                xmlns:ns8="http://www.bolivariano.com/mensaje/MensajeOTC"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl ns1 soap wsdl ns5 ns6 ns10 ns9 ns0 ns2 ns3 ns4 tns xsd ns7 ns8 mcnt ns13 ns14 ns12 ns16 http ns15 ns17 ns11 ns18 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap">
  <xsl:template match="/">
    <mcnt:MensajeEntradaConsultar>
      <canal>
        <xsl:value-of select="/ns8:entradaConsultarDeuda/ns8:canal"/>
      </canal>
      <oficina>
        <xsl:value-of select='/ns8:entradaConsultarDeuda/ns8:servicio/datosAdicionales/datoAdicional[codigo = "s_ofi"]/valor'/>
      </oficina>
      <terminal>
        <xsl:value-of select='/ns8:entradaConsultarDeuda/ns8:servicio/datosAdicionales/datoAdicional[codigo = "s_term"]/valor'/>
      </terminal>
      <transaccion>
        <xsl:value-of select="/ns8:entradaConsultarDeuda/ns8:transaccion"/>
      </transaccion>
      <usuario>
        <xsl:value-of select='/ns8:entradaConsultarDeuda/ns8:servicio/datosAdicionales/datoAdicional[codigo = "s_user"]/valor'/>
      </usuario>
      <cnt>
<xsl:if test="/ns8:entradaConsultarDeuda/ns8:canal = 'CNB' ">
        <servicioPersona>
          <xsl:text disable-output-escaping="no">CSBA</xsl:text>
        </servicioPersona>
      </xsl:if>
        <xsl:choose>
          <xsl:when test="/ns8:entradaConsultarDeuda/ns8:servicio/codigoEmpresa = '5482'">
            <codigoComercio>
              <xsl:text disable-output-escaping="no">002</xsl:text>
            </codigoComercio>
          </xsl:when>
          <xsl:otherwise>
            <codigoComercio>
              <xsl:text disable-output-escaping="no">001</xsl:text>
            </codigoComercio>
          </xsl:otherwise>
        </xsl:choose>
        <xsl:choose>
          <xsl:when test="/ns8:entradaConsultarDeuda/ns8:servicio/codigoEmpresa = '5482'">
            <codigoProveedor>
              <xsl:text disable-output-escaping="no">000003</xsl:text>
            </codigoProveedor>
<xsl:if test="/ns8:entradaConsultarDeuda/ns8:canal = 'CNB' ">
        <rubroPersona>CNMP</rubroPersona>
      </xsl:if>
          </xsl:when>
          <xsl:otherwise>
            <codigoProveedor>
              <xsl:text disable-output-escaping="no">001007</xsl:text>
            </codigoProveedor>
          </xsl:otherwise>
        </xsl:choose>
        <empresa>
          <xsl:value-of select="/ns8:entradaConsultarDeuda/ns8:servicio/codigoEmpresa"/>
        </empresa>
        <tipoMoneda>
          <xsl:text disable-output-escaping="no">1</xsl:text>
        </tipoMoneda>
        <codigoTransaccion>
          <xsl:text disable-output-escaping="no">000003</xsl:text>
        </codigoTransaccion>
        <fechaPac>
          <xsl:value-of select='java:format(java:text.SimpleDateFormat.new("yyyy-MM-dd&apos;T&apos;HH:mm:ss.SSS"), java:util.Date.new())'/>
        </fechaPac>
        <secuencialTransaccion>
          <xsl:value-of select='/ns8:entradaConsultarDeuda/ns8:servicio/datosAdicionales/datoAdicional[codigo = "s_ssn"]/valor'/>
        </secuencialTransaccion>
        <telefono>
          <xsl:value-of select="/ns8:entradaConsultarDeuda/ns8:servicio/identificador"/>
        </telefono>
        <xsl:choose>
          <xsl:when test="/ns8:entradaConsultarDeuda/ns8:servicio/codigoEmpresa='3'">
            <TipoServicio>
              <xsl:text disable-output-escaping="no">001</xsl:text>
            </TipoServicio>
  <xsl:if test="/ns8:entradaConsultarDeuda/ns8:canal = 'CNB' ">
        <rubroPersona>PACT</rubroPersona>
      </xsl:if>
          </xsl:when>
          <xsl:otherwise>
            <TipoServicio>
              <xsl:text disable-output-escaping="no">002</xsl:text>
            </TipoServicio>
          </xsl:otherwise>
        </xsl:choose>
      </cnt>
      <informacionCore>
        <fechaProcesoKernel>
          <xsl:value-of select='java:format(java:text.SimpleDateFormat.new("yyyy-MM-dd&apos;T&apos;HH:mm:ss.SSS"), java:util.Date.new())'/>
        </fechaProcesoKernel>
        <rolBPM>
          <xsl:value-of select='/ns8:entradaConsultarDeuda/ns8:servicio/datosAdicionales/datoAdicional[codigo = "s_rol"]/valor'/>
        </rolBPM>
        <secuencial>
          <xsl:value-of select='/ns8:entradaConsultarDeuda/ns8:servicio/datosAdicionales/datoAdicional[codigo = "s_ssn"]/valor'/>
        </secuencial>
        <servidor>
          <xsl:value-of select='/ns8:entradaConsultarDeuda/ns8:servicio/datosAdicionales/datoAdicional[codigo = "s_srv"]/valor'/>
        </servidor>
        <servidorLocal>
          <xsl:value-of select='/ns8:entradaConsultarDeuda/ns8:servicio/datosAdicionales/datoAdicional[codigo = "s_lsrv"]/valor'/>
        </servidorLocal>
      </informacionCore>
      <xsl:if test="/ns8:entradaConsultarDeuda/ns8:canal = 'CNB' ">
        <CNB>
          <tipoTransaccion>C</tipoTransaccion>
          <empresa>
         <xsl:value-of select="/ns8:entradaConsultarDeuda/ns8:servicio/codigoEmpresa"/>
          </empresa>
           <!--empresa>3</empresa-->
        </CNB>  
      </xsl:if>


    </mcnt:MensajeEntradaConsultar>
  </xsl:template>
</xsl:stylesheet>
