<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:tns="http://www.bolivariano.com/mensaje/MensajeOTC" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:ns0="http://www.bolivariano.com/MensajeCuenta" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction"
                xmlns:cbb="http://www.bolivariano.com/CoreBB" xmlns:ns2="http://www.bolivariano.com/Persona"
                xmlns:rcd="http://www.bolivariano.com/Recaudo" xmlns:cs="http://www.bolivariano.com/Comision"
                xmlns:ns5="http://www.bolivariano.com/PosicionGeografica"
                xmlns:res="http://www.bolivariano.com/Restricciones" xmlns:ns1="http://www.bolivariano.com/Funcionario"
                xmlns:mbl="http://www.bolivariano.com/MensajeBolivariano"
                xmlns:ns3="http://www.bolivariano.com/Sucursal" xmlns:s1="http://www.bolivariano.com/Cuenta"
                xmlns:ns4="http://www.bolivariano.com/Producto" xmlns:enum="http://www.bolivariano.com/Enumerados"
                xmlns:cln="http://www.bolivariano.com/Cliente"
                xmlns:ns8="http://www.bolivariano.com/dominio/RegionalArea"
                xmlns:ns11="http://www.bolivariano.com/dominio/Recibo"
                xmlns:ns6="http://www.bolivariano.com/dominio/DatoAdicional"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:ns15="http://www.bolivariano.com/mensaje/MensajeOTC"
                xmlns:ns7="http://www.bolivariano.com/dominio/ListaSeleccion"
                xmlns:ns9="http://www.bolivariano.com/dominio/Servicio"
                xmlns:ns10="http://www.bolivariano.com/dominio/TipoIdentificador"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns12="http://www.bolivariano.com/dominio/Empresa"
                xmlns:ns13="http://www.bolivariano.com/dominio/TipoMatriculacion"
                xmlns:ns14="http://www.bolivariano.com/dominio/Convenio"
                xmlns:ns16="http://www.bolivariano.com/dominio/FormaPago">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../MensajesCanonicos/MensajeCuenta.xsd"/>
            <oracle-xsl-mapper:rootElement name="MensajeSalidaDepositar" namespace="http://www.bolivariano.com/MensajeCuenta"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../../ModeloNegocio/otc.wsdl"/>
            <oracle-xsl-mapper:rootElement name="salidaEjecutarPago" namespace="http://www.bolivariano.com/mensaje/MensajeOTC"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [WED DEC 08 10:39:03 COT 2021].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:salidaEjecutarPago>
         <ns15:codigoError>
            <xsl:value-of select="/ns0:MensajeSalidaDepositar/codigoError"/>
         </ns15:codigoError>
         <ns15:datosAdicionales>
            <ns15:datoAdicional>
			   <codigo>nombre</codigo>
               <valor>
                  <xsl:value-of select="/ns0:MensajeSalidaDepositar/recaudo/nombre"/>
               </valor>
            </ns15:datoAdicional>
			 <ns15:datoAdicional>
			   <codigo>novedad</codigo>
               <valor>
                  <xsl:value-of select="/ns0:MensajeSalidaDepositar/recaudo/cuenta/novedad"/>
               </valor>
            </ns15:datoAdicional>
			<ns15:datoAdicional>
			   <codigo>consComision</codigo>
               <valor>
                  <xsl:value-of select="/ns0:MensajeSalidaDepositar/recaudo/cuenta/consComision"/>
               </valor>
            </ns15:datoAdicional>
			 <ns15:datoAdicional>
			   <codigo>costoComision</codigo>
               <valor>
                  <xsl:value-of select="/ns0:MensajeSalidaDepositar/comision/costoComision"/>
               </valor>
            </ns15:datoAdicional>
			 <ns15:datoAdicional>
			   <codigo>impuesto</codigo>
               <valor>
                  <xsl:value-of select="/ns0:MensajeSalidaDepositar/comision/impuesto"/>
               </valor>
            </ns15:datoAdicional>
		    <ns15:datoAdicional>
			   <codigo>secuencial</codigo>
               <valor>
                  <xsl:value-of select="/ns0:MensajeSalidaDepositar/informacionCore/secuencial"/>
               </valor>
            </ns15:datoAdicional>
            <ns15:datoAdicional>
			      <codigo>fechaContable</codigo>
               <valor>
                  <!-- <xsl:value-of select="/ns0:MensajeSalidaDepositar/recaudo/fechaContable"/> -->
                  <xsl:value-of select="concat(substring(/ns0:MensajeSalidaDepositar/recaudo/fechaContable, 9,2),'/',substring(/ns0:MensajeSalidaDepositar/recaudo/fechaContable, 6, 2),'/',substring(/ns0:MensajeSalidaDepositar/recaudo/fechaContable, 1, 4))"/>
               </valor>
            </ns15:datoAdicional>
         </ns15:datosAdicionales>
         <ns15:fechaDebito/>
         <ns15:fechaPago/>
         <ns15:mensajeUsuario>
            <xsl:value-of select="/ns0:MensajeSalidaDepositar/mensajeUsuario"/>
         </ns15:mensajeUsuario>
         <ns15:referencia>
            <xsl:value-of select="/ns0:MensajeSalidaDepositar/secuenciaTransaccion"/>
         </ns15:referencia>
      </tns:salidaEjecutarPago>
   </xsl:template>
</xsl:stylesheet>
