<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:ns0="http://www.bolivariano.com/mensaje/MensajeOTC" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:tns="http://www.bolivariano.com/MensajeCuenta" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction"
                xmlns:ns3="http://www.bolivariano.com/dominio/RegionalArea"
                xmlns:ns6="http://www.bolivariano.com/dominio/Recibo"
                xmlns:ns1="http://www.bolivariano.com/dominio/DatoAdicional"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:ns10="http://www.bolivariano.com/mensaje/MensajeOTC"
                xmlns:ns2="http://www.bolivariano.com/dominio/ListaSeleccion"
                xmlns:ns4="http://www.bolivariano.com/dominio/Servicio"
                xmlns:ns5="http://www.bolivariano.com/dominio/TipoIdentificador"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns7="http://www.bolivariano.com/dominio/Empresa"
                xmlns:ns8="http://www.bolivariano.com/dominio/TipoMatriculacion"
                xmlns:ns9="http://www.bolivariano.com/dominio/Convenio"
                xmlns:ns11="http://www.bolivariano.com/dominio/FormaPago" xmlns:cbb="http://www.bolivariano.com/CoreBB"
                xmlns:ns13="http://www.bolivariano.com/Persona" xmlns:Q1="http://www.bolivariano.com/CNB"
                xmlns:rcd="http://www.bolivariano.com/Recaudo" xmlns:cs="http://www.bolivariano.com/Comision"
                xmlns:ns16="http://www.bolivariano.com/PosicionGeografica"
                xmlns:res="http://www.bolivariano.com/Restricciones" xmlns:ns12="http://www.bolivariano.com/Funcionario"
                xmlns:mbl="http://www.bolivariano.com/MensajeBolivariano"
                xmlns:ns14="http://www.bolivariano.com/Sucursal" xmlns:s1="http://www.bolivariano.com/Cuenta"
                xmlns:ns15="http://www.bolivariano.com/Producto" xmlns:enum="http://www.bolivariano.com/Enumerados"
                xmlns:cln="http://www.bolivariano.com/Cliente">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../../ModeloNegocio/otc.wsdl"/>
            <oracle-xsl-mapper:rootElement name="entradaEjecutarReverso" namespace="http://www.bolivariano.com/ws/OTCService"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../MensajesCanonicos/MensajeCuenta.xsd"/>
            <oracle-xsl-mapper:rootElement name="MensajeEntradaReversarDeposito" namespace="http://www.bolivariano.com/MensajeCuenta"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [THU JAN 06 04:37:16 COT 2022].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:MensajeEntradaReversarDeposito>
         <canal>
            <xsl:value-of select="/ns0:entradaEjecutarReverso/ns10:canal"/>
         </canal>
         <oficina>
            <xsl:value-of select="/ns0:entradaEjecutarReverso/ns10:oficina"/>
         </oficina>
         <terminal>
            <xsl:value-of select="/ns0:entradaEjecutarReverso/ns10:datosAdicionales/ns10:datoAdicional[codigo = &quot;s_term&quot;]/valor"/>
         </terminal>
         <transaccion>
            <xsl:value-of select="/ns0:entradaEjecutarReverso/ns10:transaccion"/>
         </transaccion>
         <usuario>
            <xsl:value-of select="/ns0:entradaEjecutarReverso/ns10:usuario"/>
         </usuario>
         <tipoTransaccionFlujo>
            <xsl:value-of select="/ns0:entradaEjecutarReverso/ns10:datosAdicionales/ns10:datoAdicional[codigo = &quot;p_tipoTransaccionFlujo&quot;]/valor"/>
         </tipoTransaccionFlujo>
         <recaudo>
            <aplicativoCobis>
               <xsl:value-of select="/ns0:entradaEjecutarReverso/ns10:datosAdicionales/ns10:datoAdicional[codigo = &quot;p_aplicativoCobis&quot;]/valor"/>
            </aplicativoCobis>
            <autorizacion>
               <xsl:value-of select="/ns0:entradaEjecutarReverso/ns10:datosAdicionales/ns10:datoAdicional[codigo = &quot;p_autorizacion&quot;]/valor"/>
            </autorizacion>
            <efectivo>
               <xsl:value-of select="/ns0:entradaEjecutarReverso/ns10:datosAdicionales/ns10:datoAdicional[codigo = &quot;p_efectivo&quot;]/valor"/>
            </efectivo>
            <horario>
               <xsl:value-of select="/ns0:entradaEjecutarReverso/ns10:datosAdicionales/ns10:datoAdicional[codigo = &quot;p_horario&quot;]/valor"/>
            </horario>
            <operacionProceso>
               <xsl:value-of select="/ns0:entradaEjecutarReverso/ns10:datosAdicionales/ns10:datoAdicional[codigo = &quot;p_operacionProceso&quot;]/valor"/>
            </operacionProceso>
            <secuencialRequerimiento>
               <xsl:value-of select="/ns0:entradaEjecutarReverso/ns10:datosAdicionales/ns10:datoAdicional[codigo = &quot;p_secuencialRequerimiento&quot;]/valor"/>
            </secuencialRequerimiento>
            <tipoMoneda>
               <xsl:value-of select="/ns0:entradaEjecutarReverso/ns10:moneda"/>
            </tipoMoneda>
            <tipoOperacion>
               <xsl:value-of select="/ns0:entradaEjecutarReverso/ns10:datosAdicionales/ns10:datoAdicional[codigo = &quot;p_tipoOperacion&quot;]/valor"/>
            </tipoOperacion>
            <cuenta>
               <codigoDepRet>
                  <xsl:value-of select="/ns0:entradaEjecutarReverso/ns10:datosAdicionales/ns10:datoAdicional[codigo = &quot;p_codigoDepRet&quot;]/valor"/>
               </codigoDepRet>
			   <cuenta>
				  <xsl:value-of select="/ns0:entradaEjecutarReverso/ns10:cuenta"/>
			   </cuenta>
			   <idCliente>
                  <xsl:value-of select="/ns0:entradaEjecutarReverso/ns10:datosAdicionales/ns10:datoAdicional[codigo = &quot;p_idCliente&quot;]/valor"/>
               </idCliente>
               <nombreCuenta>
                  <xsl:value-of select="/ns0:entradaEjecutarReverso/ns10:datosAdicionales/ns10:datoAdicional[codigo = &quot;p_nombreCuenta&quot;]/valor"/>
               </nombreCuenta>
               <tipoCuenta>
                  <xsl:value-of select="/ns0:entradaEjecutarReverso/ns10:tipoCuenta"/>
               </tipoCuenta>
               <consComision>
                  <xsl:value-of select="/ns0:entradaEjecutarReverso/ns10:datosAdicionales/ns10:datoAdicional[codigo = &quot;p_consComision&quot;]/valor"/>
               </consComision>
               <fechaTope>
                  <xsl:value-of select="/ns0:entradaEjecutarReverso/ns10:datosAdicionales/ns10:datoAdicional[codigo = &quot;p_fechaTope&quot;]/valor"/>
               </fechaTope>
               <opcion>
                  <xsl:value-of select="/ns0:entradaEjecutarReverso/ns10:datosAdicionales/ns10:datoAdicional[codigo = &quot;p_opcion&quot;]/valor"/>
               </opcion>
               <servicio>
                  <xsl:value-of select="/ns0:entradaEjecutarReverso/ns10:datosAdicionales/ns10:datoAdicional[codigo = &quot;p_servicio&quot;]/valor"/>
               </servicio>
               <valorTotal>
                  <xsl:value-of select="/ns0:entradaEjecutarReverso/ns10:valorPago"/>
               </valorTotal>
		   </cuenta>
         </recaudo>
         <comision>
            <costoComision>
               <xsl:value-of select="/ns0:entradaEjecutarReverso/ns10:datosAdicionales/ns10:datoAdicional[codigo = &quot;p_costoComision&quot;]/valor"/>
            </costoComision>
         </comision>
         <informacionCore>
            <fechaProcesoKernel>
               <xsl:value-of select="/ns0:entradaEjecutarReverso/ns10:datosAdicionales/ns10:datoAdicional[codigo = &quot;p_fechaTope&quot;]/valor"/>
            </fechaProcesoKernel>
            <modoCorreccion>
               <xsl:value-of select="/ns0:entradaEjecutarReverso/ns10:datosAdicionales/ns10:datoAdicional[codigo = &quot;p_modoCorreccion&quot;]/valor"/>
            </modoCorreccion>
            <origenTransaccion>
               <xsl:value-of select="/ns0:entradaEjecutarReverso/ns10:datosAdicionales/ns10:datoAdicional[codigo = &quot;p_origenTransaccion&quot;]/valor"/>
            </origenTransaccion>
			<reversoTransaccion>
			   <xsl:value-of select="/ns0:entradaEjecutarReverso/ns10:datosAdicionales/ns10:datoAdicional[codigo = &quot;p_reversoTransaccion&quot;]/valor"/>
			</reversoTransaccion>
            <rolBPM>
               <xsl:value-of select="/ns0:entradaEjecutarReverso/ns10:datosAdicionales/ns10:datoAdicional[codigo = &quot;p_rolBPM&quot;]/valor"/>
            </rolBPM>
            <sec>
               <xsl:value-of select="/ns0:entradaEjecutarReverso/ns10:datosAdicionales/ns10:datoAdicional[codigo = &quot;p_secuencialRequerimiento&quot;]/valor"/>
            </sec>
            <secuencial>
               <xsl:value-of select="/ns0:entradaEjecutarReverso/ns10:datosAdicionales/ns10:datoAdicional[codigo = &quot;p_secuencialRequerimiento&quot;]/valor"/>
            </secuencial>
            <servidor>
               <xsl:value-of select="/ns0:entradaEjecutarReverso/ns10:datosAdicionales/ns10:datoAdicional[codigo = &quot;s_srv&quot;]/valor"/>
            </servidor>
            <servidorLocal>
               <xsl:value-of select="/ns0:entradaEjecutarReverso/ns10:datosAdicionales/ns10:datoAdicional[codigo = &quot;s_lsrv&quot;]/valor"/>
            </servidorLocal>
            <sesion>
               <xsl:value-of select="/ns0:entradaEjecutarReverso/ns10:datosAdicionales/ns10:datoAdicional[codigo = &quot;p_sesion&quot;]/valor"/>
            </sesion>
            <severidadError>
               <xsl:value-of select="/ns0:entradaEjecutarReverso/ns10:datosAdicionales/ns10:datoAdicional[codigo = &quot;p_severidadError&quot;]/valor"/>
            </severidadError>
         </informacionCore>
         <informacionCNB>
            <autorizacion>
               <xsl:value-of select="/ns0:entradaEjecutarReverso/ns10:datosAdicionales/ns10:datoAdicional[codigo = &quot;p_autorizacionCNB&quot;]/valor"/>
            </autorizacion>
            <comercio>
               <xsl:value-of select="/ns0:entradaEjecutarReverso/ns10:datosAdicionales/ns10:datoAdicional[codigo = &quot;p_comercio&quot;]/valor"/>
            </comercio>
            <terminalID>
				<xsl:value-of select="/ns0:entradaEjecutarReverso/ns10:datosAdicionales/ns10:datoAdicional[codigo = &quot;p_terminalID&quot;]/valor"/>
			</terminalID>
			<agencia>
				<xsl:value-of select="/ns0:entradaEjecutarReverso/ns10:datosAdicionales/ns10:datoAdicional[codigo = &quot;p_agencia&quot;]/valor"/>
			</agencia>
         <red>
				<xsl:value-of select="/ns0:entradaEjecutarReverso/ns10:datosAdicionales/ns10:datoAdicional[codigo = &quot;p_red&quot;]/valor"/>
			</red>
         </informacionCNB>
      </tns:MensajeEntradaReversarDeposito>
   </xsl:template>
</xsl:stylesheet>
