<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:cbb="http://www.bolivariano.com/CoreBB" xmlns:cln="http://www.bolivariano.com/Cliente" xmlns:cs="http://www.bolivariano.com/Comision" xmlns:enum="http://www.bolivariano.com/Enumerados" xmlns:mbl="http://www.bolivariano.com/MensajeBolivariano" xmlns:ns0="http://www.bolivariano.com/MensajeCuenta" xmlns:ns1="http://www.bolivariano.com/Funcionario" xmlns:ns10="http://www.bolivariano.com/dominio/TipoIdentificador" xmlns:ns11="http://www.bolivariano.com/dominio/Recibo" xmlns:ns12="http://www.bolivariano.com/dominio/Empresa" xmlns:ns13="http://www.bolivariano.com/dominio/TipoMatriculacion" xmlns:ns14="http://www.bolivariano.com/dominio/Convenio" xmlns:ns15="http://www.bolivariano.com/mensaje/MensajeOTC" xmlns:ns16="http://www.bolivariano.com/dominio/FormaPago" xmlns:ns2="http://www.bolivariano.com/Persona" xmlns:ns3="http://www.bolivariano.com/Sucursal" xmlns:ns4="http://www.bolivariano.com/Producto" xmlns:ns5="http://www.bolivariano.com/PosicionGeografica" xmlns:ns6="http://www.bolivariano.com/dominio/DatoAdicional" xmlns:ns7="http://www.bolivariano.com/dominio/ListaSeleccion" xmlns:ns8="http://www.bolivariano.com/dominio/RegionalArea" xmlns:ns9="http://www.bolivariano.com/dominio/Servicio" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:rcd="http://www.bolivariano.com/Recaudo" xmlns:res="http://www.bolivariano.com/Restricciones" xmlns:s1="http://www.bolivariano.com/Cuenta" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.bolivariano.com/mensaje/MensajeOTC" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../MensajesCanonicos/MensajeCuenta.xsd" />
            <oracle-xsl-mapper:rootElement name="MensajeSalidaReversarDeposito" namespace="http://www.bolivariano.com/MensajeCuenta" />
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../../ModeloNegocio/otc.wsdl" />
            <oracle-xsl-mapper:rootElement name="salidaEjecutarPago" namespace="http://www.bolivariano.com/mensaje/MensajeOTC" />
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [TUE JAN 25 16:02:04 COT 2022].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:salidaEjecutarPago>
         <ns15:codigoError>
            <xsl:value-of select="/ns0:MensajeSalidaReversarDeposito/codigoError" />
         </ns15:codigoError>
         <ns15:datosAdicionales>
            <ns15:datoAdicional>
               <codigo>nombre</codigo>
               <valor>
                  <xsl:value-of select="/ns0:MensajeSalidaReversarDeposito/recaudo/nombre" />
               </valor>
            </ns15:datoAdicional>
            <ns15:datoAdicional>
               <codigo>secuencialRequerimiento</codigo>
               <valor>
                  <xsl:value-of select="/ns0:MensajeSalidaReversarDeposito/recaudo/cuenta/secuencialRequerimiento" />
               </valor>
            </ns15:datoAdicional>
            <ns15:datoAdicional>
               <codigo>consComision</codigo>
               <valor>
                  <xsl:value-of select="/ns0:MensajeSalidaReversarDeposito/recaudo/cuenta/consComision" />
               </valor>
            </ns15:datoAdicional>
            <ns15:datoAdicional>
               <codigo>costoComision</codigo>
               <valor>
                  <xsl:value-of select="/ns0:MensajeSalidaReversarDeposito/comision/costoComision" />
               </valor>
            </ns15:datoAdicional>
            <ns15:datoAdicional>
               <codigo>impuesto</codigo>
               <valor>
                  <xsl:value-of select="/ns0:MensajeSalidaReversarDeposito/comision/impuesto" />
               </valor>
            </ns15:datoAdicional>
            <ns15:datoAdicional>
               <codigo>secuencial</codigo>
               <valor>
                  <xsl:value-of select="/ns0:MensajeSalidaReversarDeposito/informacionCore/secuencial" />
               </valor>
            </ns15:datoAdicional>
            <ns15:datoAdicional>
               <codigo>fechaContable</codigo>
               <valor>
                  <xsl:value-of select="/ns0:MensajeSalidaReversarDeposito/recaudo/fechaContable" />
               </valor>
            </ns15:datoAdicional>
         </ns15:datosAdicionales>
         <ns15:mensajeUsuario>
            <xsl:value-of select="/ns0:MensajeSalidaReversarDeposito/mensajeUsuario" />
         </ns15:mensajeUsuario>
      </tns:salidaEjecutarPago>
   </xsl:template>
</xsl:stylesheet>