<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:tns="http://www.bolivariano.com/mensaje/MensajeOTC" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:ns0="http://www.bolivariano.com/MensajeCuenta" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:cbb="http://www.bolivariano.com/CoreBB" xmlns:ns2="http://www.bolivariano.com/Persona" xmlns:Q1="http://www.bolivariano.com/CNB" xmlns:rcd="http://www.bolivariano.com/Recaudo" xmlns:cs="http://www.bolivariano.com/Comision" xmlns:ns5="http://www.bolivariano.com/PosicionGeografica" xmlns:res="http://www.bolivariano.com/Restricciones" xmlns:ns1="http://www.bolivariano.com/Funcionario" xmlns:mbl="http://www.bolivariano.com/MensajeBolivariano" xmlns:ns3="http://www.bolivariano.com/Sucursal" xmlns:s1="http://www.bolivariano.com/Cuenta" xmlns:ns4="http://www.bolivariano.com/Producto" xmlns:enum="http://www.bolivariano.com/Enumerados" xmlns:cln="http://www.bolivariano.com/Cliente" xmlns:ns8="http://www.bolivariano.com/dominio/RegionalArea" xmlns:ns11="http://www.bolivariano.com/dominio/Recibo" xmlns:ns6="http://www.bolivariano.com/dominio/DatoAdicional" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns15="http://www.bolivariano.com/mensaje/MensajeOTC" xmlns:ns7="http://www.bolivariano.com/dominio/ListaSeleccion" xmlns:ns9="http://www.bolivariano.com/dominio/Servicio" xmlns:ns10="http://www.bolivariano.com/dominio/TipoIdentificador" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns12="http://www.bolivariano.com/dominio/Empresa" xmlns:ns13="http://www.bolivariano.com/dominio/TipoMatriculacion" xmlns:ns14="http://www.bolivariano.com/dominio/Convenio" xmlns:ns16="http://www.bolivariano.com/dominio/FormaPago">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../MensajesCanonicos/MensajeCuenta.xsd"/>
            <oracle-xsl-mapper:rootElement name="MensajeSalidaConsultaEspecial" namespace="http://www.bolivariano.com/MensajeCuenta"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../../ModeloNegocio/otc.wsdl"/>
            <oracle-xsl-mapper:rootElement name="salidaConsultarDeuda" namespace="http://www.bolivariano.com/mensaje/MensajeOTC"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [THU JAN 20 15:00:24 COT 2022].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:salidaConsultarDeuda>
         <ns15:codigoError>
            <xsl:value-of select="/ns0:MensajeSalidaConsultaEspecial/codigoError"/>
         </ns15:codigoError>
         <ns15:datosAdicionales>
            <ns15:datoAdicional>
               <codigo>empresa</codigo>
               <valor>
                  <xsl:value-of select="/ns0:MensajeSalidaConsultaEspecial/recaudo/empresa"/>
               </valor>
            </ns15:datoAdicional>
            <ns15:datoAdicional>
               <codigo>descripcion</codigo>
               <valor>
                  <xsl:value-of select="/ns0:MensajeSalidaConsultaEspecial/cliente/descripcion"/>
               </valor>
            </ns15:datoAdicional>
            <ns15:datoAdicional>
               <codigo>cobroConOrden</codigo>
               <valor>
                  <xsl:value-of select="/ns0:MensajeSalidaConsultaEspecial/recaudo/cuenta/cobroConOrden"/>
               </valor>
            </ns15:datoAdicional>
            <ns15:datoAdicional>
               <codigo>cobroParcial</codigo>
               <valor>
                  <xsl:value-of select="/ns0:MensajeSalidaConsultaEspecial/recaudo/cuenta/cobroParcial"/>
               </valor>
            </ns15:datoAdicional>
            <ns15:datoAdicional>
               <codigo>creaOrden</codigo>
               <valor>
                  <xsl:value-of select="/ns0:MensajeSalidaConsultaEspecial/recaudo/cuenta/creaOrden"/>
               </valor>
            </ns15:datoAdicional>
            <ns15:datoAdicional>
               <codigo>estadoValida</codigo>
               <valor>
                  <xsl:value-of select="/ns0:MensajeSalidaConsultaEspecial/recaudo/cuenta/estadoValida"/>
               </valor>
            </ns15:datoAdicional>
            <xsl:choose>
               <xsl:when test="/ns0:MensajeSalidaConsultaEspecial/recaudo/valortasa > 0">
                  <ns15:datoAdicional>
                     <codigo>valorMinimo</codigo>
					 <xsl:variable name="nValorTasa" select="string(/ns0:MensajeSalidaConsultaEspecial/recaudo/valortasa)"/>
                     <valor>
					    <xsl:value-of select="substring($nValorTasa, 1, string-length(substring-before($nValorTasa, '.')) + 3)"/>
                        <!--xsl:value-of select="/ns0:MensajeSalidaConsultaEspecial/recaudo/valortasa"-->
                     </valor>
                  </ns15:datoAdicional>
               </xsl:when>
               <xsl:otherwise>
                  <ns15:datoAdicional>
                     <codigo>valorMinimo</codigo>
                     <valor>
                        <xsl:text disable-output-escaping="no">0</xsl:text>
                     </valor>
                  </ns15:datoAdicional>
               </xsl:otherwise>
            </xsl:choose>
            <xsl:choose>
               <xsl:when test="/ns0:MensajeSalidaConsultaEspecial/recaudo/valorTotalCancelar > 0">
                  <ns15:datoAdicional>
                     <codigo>valorSaldo</codigo>
					  <xsl:variable name="nvalorTotalCancelar" select="string(/ns0:MensajeSalidaConsultaEspecial/recaudo/valorTotalCancelar)"/>
                     <valor>
					 	<xsl:value-of select="substring($nvalorTotalCancelar, 1, string-length(substring-before($nvalorTotalCancelar, '.')) + 3)"/>
                        <!--xsl:value-of select="/ns0:MensajeSalidaConsultaEspecial/recaudo/valorTotalCancelar"-->
                     </valor>
                  </ns15:datoAdicional>
               </xsl:when>
               <xsl:otherwise>
                  <ns15:datoAdicional>
                     <codigo>valorSaldo</codigo>
                     <valor>
                        <xsl:text disable-output-escaping="no">0</xsl:text>
                     </valor>
                  </ns15:datoAdicional>
               </xsl:otherwise>
            </xsl:choose>
            <ns15:datoAdicional>
               <codigo>indicadorValMin</codigo>
               <valor>
                  <xsl:value-of select="/ns0:MensajeSalidaConsultaEspecial/recaudo/cuenta/creaOrden"/>
               </valor>
            </ns15:datoAdicional>
            <ns15:datoAdicional>
               <codigo>nombre</codigo>
               <valor>
                  <xsl:value-of select="/ns0:MensajeSalidaConsultaEspecial/recaudo/nombre"/>
               </valor>
            </ns15:datoAdicional>
			<ns15:datoAdicional>
               <codigo>nombreDeudor</codigo>
               <valor>
                  <xsl:value-of select="/ns0:MensajeSalidaConsultaEspecial/cliente/nombre"/>
               </valor>
            </ns15:datoAdicional>
            <ns15:datoAdicional>
               <codigo>valorComision</codigo>
               <!--<valor>
                     <xsl:value-of select="/ns0:MensajeSalidaConsultaEspecial/recaudo/valorComision"/>
                  <valor>-->
               <xsl:choose>
                  <xsl:when test="/ns0:MensajeSalidaConsultaEspecial/recaudo/valorComision > 0">
                     <xsl:variable name="n" select="string(/ns0:MensajeSalidaConsultaEspecial/recaudo/valorComision)"/>
                     <valor>
                        <xsl:value-of select="substring($n, 1, string-length(substring-before($n, '.')) + 3)"/>
                     </valor>
                  </xsl:when>
                  <xsl:otherwise>
                     <valor>
                        <xsl:text disable-output-escaping="no">0</xsl:text>
                     </valor>
                  </xsl:otherwise>
               </xsl:choose>
            </ns15:datoAdicional>
         </ns15:datosAdicionales>
         <ns15:mensajeUsuario>
            <xsl:value-of select="/ns0:MensajeSalidaConsultaEspecial/mensajeUsuario"/>
         </ns15:mensajeUsuario>
      </tns:salidaConsultarDeuda>
   </xsl:template>
</xsl:stylesheet>
