<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../../../../../../../../Tareas%20Elizabeth/SAT-2018/CASH%20-%20CyberBank/06-Pagos%20de%20Servicios/ServiciosRecaudaciones/DOCUMENTACIONMAPEO/Project4/otc-nopolicy.wsdl"/>
      <rootElement name="entradaConsultarDeuda" namespace="http://www.bolivariano.com/ws/OTCService"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../../../../../../../../Tareas%20Elizabeth/SAT-2018/CASH%20-%20CyberBank/06-Pagos%20de%20Servicios/ServiciosRecaudaciones/DOCUMENTACIONMAPEO/Project4/xsd/DepositoTemporal_1.wsdl"/>
      <rootElement name="MensajeEntradaConsultar" namespace="http://www.bolivariano.com/MensajeDepositoTemporal"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 130301.0647.0008) AT [FRI MAY 25 12:07:30 COT 2018]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:sne="http://www.bolivariano.com/DepositoTemporal"
                xmlns:ns1="http://www.bolivariano.com/dominio/DatoAdicional"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:ns12="http://www.bolivariano.com/CoreBB"
                xmlns:ns14="http://www.bolivariano.com/Cuenta"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:msne="http://www.bolivariano.com/MensajeDepositoTemporal"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:ns5="http://www.bolivariano.com/dominio/Convenio"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns6="http://www.bolivariano.com/dominio/Recibo"
                xmlns:ns10="http://www.bolivariano.com/dominio/ListaSeleccion"
                xmlns:ns9="http://www.bolivariano.com/dominio/RegionalArea"
                xmlns:ns0="http://www.bolivariano.com/dominio/Servicio"
                xmlns:ns11="http://www.bolivariano.com/MensajeBolivariano"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:ns15="http://www.bolivariano.com/Recaudo"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ns2="http://www.bolivariano.com/dominio/TipoMatriculacion"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:ns3="http://www.bolivariano.com/dominio/FormaPago"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns4="http://www.bolivariano.com/dominio/TipoIdentificador"
                xmlns:tns="http://www.bolivariano.com/ws/OTCService"
                xmlns:http="http://schemas.xmlsoap.org/wsdl/http/"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:ns13="http://www.bolivariano.com/Producto"
                xmlns:ns16="http://www.bolivariano.com/Cliente"
                xmlns:ns7="http://www.bolivariano.com/dominio/Empresa"
                xmlns:ns8="http://www.bolivariano.com/mensaje/MensajeOTC"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                 xmlns:java="java"
                exclude-result-prefixes="xsi xsl ns1 soap wsdl ns5 ns6 ns10 ns9 ns0 ns2 ns3 ns4 tns xsd ns7 ns8 sne ns12 ns14 msne ns11 ns15 http ns13 ns16 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap">
  <xsl:template match="/">
    <msne:MensajeEntradaConsultar>
      <canal>
        <xsl:value-of select="/ns8:entradaConsultarDeuda/ns8:canal"/>
      </canal>
      <oficina>
        <xsl:value-of select='/ns8:entradaConsultarDeuda/ns8:servicio/datosAdicionales/datoAdicional[codigo = "s_ofi"]/valor'/>
      </oficina>
      <terminal>
        <xsl:text disable-output-escaping="no">0233000000OPE998</xsl:text>
      </terminal>
      <transaccion>
        <xsl:text disable-output-escaping="no">62652</xsl:text>
      </transaccion>
      <usuario>
        <xsl:value-of select='/ns8:entradaConsultarDeuda/ns8:servicio/datosAdicionales/datoAdicional[codigo = "s_user"]/valor'/>
      </usuario>
      <informacionDepositoTemporal>
        <aplicativoCobis>
          <xsl:text disable-output-escaping="no">IBK</xsl:text>
        </aplicativoCobis>
        <empresa>
          <xsl:value-of select="/ns8:entradaConsultarDeuda/ns8:servicio/codigoConvenio"/>
        </empresa>
        <tipoMoneda>
          <xsl:text disable-output-escaping="no">840</xsl:text>
        </tipoMoneda>
        <tipoOperacion>
          <xsl:text disable-output-escaping="no">310001</xsl:text>
        </tipoOperacion>
        <comprobante>
          <xsl:value-of select="/ns8:entradaConsultarDeuda/ns8:servicio/identificador"/>
        </comprobante>
        <declaracion>
          <xsl:value-of select="/ns8:entradaConsultarDeuda/ns8:servicio/identificador"/>
        </declaracion>
        <codigoAdquiriente>
          <xsl:text disable-output-escaping="no">00000597777</xsl:text>
        </codigoAdquiriente>
        <fechaHoraBANRED>
          <xsl:value-of select="/ns8:entradaConsultarDeuda/ns8:fecha"/>
        </fechaHoraBANRED>
        <fechaTransaccionLocal>
          <xsl:value-of select="/ns8:entradaConsultarDeuda/ns8:fecha"/>
        </fechaTransaccionLocal>
        <fechaCompensacion>
          <xsl:value-of select="/ns8:entradaConsultarDeuda/ns8:fecha"/>
        </fechaCompensacion>
        <horaTransaccionLocal>
              <xsl:value-of select='java:format(java:text.SimpleDateFormat.new("HHmmss"), java:util.Date.new())'/>
        </horaTransaccionLocal>
        <secuencialSwitch>
          <xsl:text disable-output-escaping="no">0</xsl:text>
        </secuencialSwitch>
        <secuencialAdquiriente>000000993726</secuencialAdquiriente>
      </informacionDepositoTemporal>
      <informacionCore>
        <codigoTRX>
          <xsl:text disable-output-escaping="no">62652</xsl:text>
        </codigoTRX>
        <secuencial>
          <xsl:value-of select='/ns8:entradaConsultarDeuda/ns8:servicio/datosAdicionales/datoAdicional[codigo = "s_ssn"]/valor'/>
        </secuencial>
        <servidor>
          <xsl:value-of select='/ns8:entradaConsultarDeuda/ns8:servicio/datosAdicionales/datoAdicional[codigo = "s_srv"]/valor'/>
        </servidor>
        <servidorLocal>
          <xsl:value-of select='/ns8:entradaConsultarDeuda/ns8:servicio/datosAdicionales/datoAdicional[codigo = "s_lsrv"]/valor'/>
        </servidorLocal>
      </informacionCore>
    </msne:MensajeEntradaConsultar>
  </xsl:template>
</xsl:stylesheet>
