<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../wsdl/DirectvPostpago.wsdl"/>
      <rootElement name="MensajeSalidaConsultar" namespace="http://www.bolivariano.com/MensajeDirectvPostpago"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../OTCEndpoint_1.wsdl"/>
      <rootElement name="salidaConsultarDeuda" namespace="http://www.bolivariano.com/ws/OTCService"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.8(build 150622.2350.0222) AT [THU JUL 19 23:51:09 COT 2018]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:ns7="http://www.bolivariano.com/dominio/DatoAdicional"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:ns2="http://www.bolivariano.com/CoreBB"
                xmlns:ns4="http://www.bolivariano.com/Cuenta"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns13="http://www.bolivariano.com/dominio/Convenio"
                xmlns:ns14="http://www.bolivariano.com/dominio/Recibo"
                xmlns:tns="http://www.bolivariano.com/ws/DirectvPostpago/"
                xmlns:ns17="http://www.bolivariano.com/dominio/RegionalArea"
                xmlns:ns18="http://www.bolivariano.com/dominio/ListaSeleccion"
                xmlns:ns9="http://www.bolivariano.com/dominio/Servicio"
                xmlns:ns1="http://www.bolivariano.com/MensajeBolivariano"
                xmlns:ns0="http://www.bolivariano.com/DirectvPostpago"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:ns5="http://www.bolivariano.com/Recaudo"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:ns10="http://www.bolivariano.com/dominio/TipoMatriculacion"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:ns11="http://www.bolivariano.com/dominio/FormaPago"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns12="http://www.bolivariano.com/dominio/TipoIdentificador"
                xmlns:ns8="http://www.bolivariano.com/ws/OTCService"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:ns3="http://www.bolivariano.com/Producto"
                xmlns:ns6="http://www.bolivariano.com/Cliente"
                xmlns:ns15="http://www.bolivariano.com/dominio/Empresa"
                xmlns:xsd1="http://www.bolivariano.com/MensajeDirectvPostpago"
                xmlns:ns16="http://www.bolivariano.com/mensaje/MensajeOTC"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl soap ns2 ns4 wsdl tns ns1 ns0 ns5 xsd ns3 ns6 xsd1 ns7 ns13 ns14 ns17 ns18 ns9 ns10 ns11 ns12 ns8 ns15 ns16 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap">
  <xsl:template match="/">
    <ns16:salidaConsultarDeuda>
      <xsl:choose>
        <xsl:when test="/xsd1:MensajeSalidaConsultar/codigoError != 0">
          <ns16:codigoError>
            <xsl:value-of select="/xsd1:MensajeSalidaConsultar/codigoError"/>
          </ns16:codigoError>
          <ns16:mensajeUsuario>
            <xsl:value-of select="/xsd1:MensajeSalidaConsultar/mensajeUsuario"/>
          </ns16:mensajeUsuario>
        </xsl:when>
        <xsl:otherwise>
          <xsl:if test="/xsd1:MensajeSalidaConsultar/Cliente/pasivos/monto &lt;= 0">
            <ns16:codigoError>
              <xsl:text disable-output-escaping="no">-1</xsl:text>
            </ns16:codigoError>
            <ns16:mensajeUsuario>
              <xsl:text disable-output-escaping="no">Cliente no tiene deuda</xsl:text>
            </ns16:mensajeUsuario>
          </xsl:if>
          <xsl:if test="/xsd1:MensajeSalidaConsultar/Cliente/pasivos/monto > 0">
            <ns16:codigoError>
              <xsl:value-of select="/xsd1:MensajeSalidaConsultar/codigoError"/>
            </ns16:codigoError>
            <ns16:mensajeUsuario>
              <xsl:value-of select="/xsd1:MensajeSalidaConsultar/mensajeUsuario"/>
            </ns16:mensajeUsuario>
            <ns16:datosAdicionales>
              <ns16:datoAdicional>
                <codigo>
                  <xsl:text disable-output-escaping="no">direccion</xsl:text>
                </codigo>
                <etiqueta>
                  <xsl:text disable-output-escaping="no">Direccion del Domicilio</xsl:text>
                </etiqueta>
                <editable>
                  <xsl:text disable-output-escaping="no">false</xsl:text>
                </editable>
                <valor>
                  <xsl:value-of select="/xsd1:MensajeSalidaConsultar/Cliente/pasivos/institucionCuenta"/>
                </valor>
                <visible>
                  <xsl:text disable-output-escaping="no">true</xsl:text>
                </visible>
              </ns16:datoAdicional>
              <ns16:datoAdicional>
			  
                <codigo>
                  <xsl:text disable-output-escaping="no">codigo_suministro</xsl:text>
                </codigo>
                <etiqueta>
                  <xsl:text disable-output-escaping="no">codigo_suministro</xsl:text>
                </etiqueta>
                <editable>
                  <xsl:text disable-output-escaping="no">false</xsl:text>
                </editable>
                <valor>
                  <xsl:value-of select="/xsd1:MensajeSalidaConsultar/Cliente/pasivos/cuenta"/>
                </valor>
                <visible>
                  <xsl:text disable-output-escaping="no">false</xsl:text>
                </visible>
              </ns16:datoAdicional>
            
			<ns16:datoAdicional>
                <codigo>
                  <xsl:text disable-output-escaping="no">detalle_rubro</xsl:text>
                </codigo>
                <etiqueta>
                  <xsl:text disable-output-escaping="no">detalle_rubro</xsl:text>
                </etiqueta>
                <editable>
                  <xsl:text disable-output-escaping="no">false</xsl:text>
                </editable>
                <valor>
                  <xsl:value-of select="/xsd1:MensajeSalidaConsultar/Cliente/pasivos/institucionCuenta"/>
                </valor>
                <visible>
                  <xsl:text disable-output-escaping="no">false</xsl:text>
                </visible>
              </ns16:datoAdicional>
              <ns16:datoAdicional>
               <codigo>valorComision</codigo>
                <xsl:choose>
                 <xsl:when test ="/xsd1:MensajeSalidaConsultar/DirectvPostpago/valorComision">
                  <valor>
                   <xsl:value-of select="format-number(/xsd1:MensajeSalidaConsultar/DirectvPostpago/valorComision,'0.00')"/>  
                  </valor>
                 </xsl:when>
                 <xsl:otherwise>
                  <valor>
                   <xsl:text disable-output-escaping="no">0.00</xsl:text>
                  </valor>
                 </xsl:otherwise>
              </xsl:choose>    
            </ns16:datoAdicional>
			</ns16:datosAdicionales>
            <ns16:formaPago>
              <xsl:text disable-output-escaping="no">TOTAL</xsl:text>
            </ns16:formaPago>
            <ns16:mensajeUsuario>
              <xsl:value-of select="/xsd1:MensajeSalidaConsultar/mensajeUsuario"/>
            </ns16:mensajeUsuario>
            <ns16:montoTotal>
              <xsl:value-of select="/xsd1:MensajeSalidaConsultar/Cliente/pasivos/monto"/>
            </ns16:montoTotal>
            <ns16:nombreCliente>
              <xsl:value-of select="/xsd1:MensajeSalidaConsultar/Cliente/pasivos/nombreInstitucion"/>
            </ns16:nombreCliente>
          </xsl:if>
        </xsl:otherwise>
      </xsl:choose>
    </ns16:salidaConsultarDeuda>
  </xsl:template>
</xsl:stylesheet>
