<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../OTCEndpoint_1.wsdl"/>
      <rootElement name="entradaEjecutarReverso" namespace="http://www.bolivariano.com/ws/OTCService"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../wsdl/DirectvPostpago.wsdl"/>
      <rootElement name="MensajeEntradaReverso" namespace="http://www.bolivariano.com/MensajeDirectvPostpago"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.8(build 150622.2350.0222) AT [MON JUL 23 16:47:05 COT 2018]. 
   <xsl:value-of select="/ns8:entradaEjecutarPago/ns8:valorComision"/>

  -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:ns1="http://www.bolivariano.com/dominio/DatoAdicional"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:ns14="http://www.bolivariano.com/CoreBB"
                xmlns:ns16="http://www.bolivariano.com/Cuenta"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns5="http://www.bolivariano.com/dominio/Convenio"
                xmlns:ns6="http://www.bolivariano.com/dominio/Recibo"
                xmlns:ns11="http://www.bolivariano.com/ws/DirectvPostpago/"
                xmlns:ns9="http://www.bolivariano.com/dominio/RegionalArea"
                xmlns:ns10="http://www.bolivariano.com/dominio/ListaSeleccion"
                xmlns:ns0="http://www.bolivariano.com/dominio/Servicio"
                xmlns:ns12="http://www.bolivariano.com/DirectvPostpago"
                xmlns:ns13="http://www.bolivariano.com/MensajeBolivariano"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:ns17="http://www.bolivariano.com/Recaudo"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:ns2="http://www.bolivariano.com/dominio/TipoMatriculacion"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:ns3="http://www.bolivariano.com/dominio/FormaPago"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns4="http://www.bolivariano.com/dominio/TipoIdentificador"
                xmlns:tns="http://www.bolivariano.com/ws/OTCService"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:ns15="http://www.bolivariano.com/Producto"
                xmlns:ns7="http://www.bolivariano.com/dominio/Empresa"
                xmlns:ns18="http://www.bolivariano.com/Cliente"
                xmlns:ns8="http://www.bolivariano.com/mensaje/MensajeOTC"
                xmlns:xsd1="http://www.bolivariano.com/MensajeDirectvPostpago"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl ns1 soap wsdl ns5 ns6 ns9 ns10 ns0 ns2 ns3 ns4 tns xsd ns7 ns8 ns14 ns16 ns11 ns12 ns13 ns17 ns15 ns18 xsd1 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap">
  <xsl:template match="/">
    <xsd1:MensajeEntradaReverso>
      <canal>
        <xsl:value-of select="/ns8:entradaEjecutarReverso/ns8:canal"/>
      </canal>
      <oficina>
        <xsl:value-of select='/ns8:entradaEjecutarReverso/ns8:datosAdicionales/ns8:datoAdicional[codigo = "s_ofi"]/valor'/>
      </oficina>
      <terminal>
        <xsl:value-of select='/ns8:entradaEjecutarReverso/ns8:datosAdicionales/ns8:datoAdicional[codigo = "s_term"]/valor'/>
      </terminal>
      <transaccion>
        <xsl:text disable-output-escaping="no">62649</xsl:text>
      </transaccion>
      <usuario>
        <xsl:value-of select='/ns8:entradaEjecutarReverso/ns8:datosAdicionales/ns8:datoAdicional[codigo = "s_user"]/valor'/>
      </usuario>
      <DirectvPostpago>
        <aplicativoCobis>
          <xsl:text disable-output-escaping="no">S</xsl:text>
        </aplicativoCobis>
        <autorizacion>
          <xsl:text disable-output-escaping="no">N</xsl:text>
        </autorizacion>
          <cantidadCheque>
              <xsl:text disable-output-escaping="no">0</xsl:text>
          </cantidadCheque>
          <chequeComision>
              <xsl:text disable-output-escaping="no">0.00</xsl:text>
          </chequeComision>
          <xsl:choose>
              <xsl:when test="/ns8:entradaEjecutarReverso/ns8:canal = 'CNB' and (/ns8:entradaEjecutarReverso/ns8:datosAdicionales/ns8:datoAdicional[codigo = 'p_forma_pago']/valor = 'DEB')">
                  <debito>
                      <xsl:value-of select="/ns8:entradaEjecutarReverso/ns8:valorPago"/>
                  </debito>
                  <debitoComision>
                      <xsl:value-of select="/ns8:entradaEjecutarReverso/ns8:valorComision"/>
                  </debitoComision>
              </xsl:when>
              <xsl:when test="/ns8:entradaEjecutarReverso/ns8:canal = 'CNB' and (/ns8:entradaEjecutarReverso/ns8:datosAdicionales/ns8:datoAdicional[codigo = 'p_forma_pago']/valor = 'EFE')">
                  <debito>
                      <xsl:text disable-output-escaping="no">0.00</xsl:text>
                  </debito>
                  <debitoComision>
                      <xsl:text disable-output-escaping="no">0.00</xsl:text>
                  </debitoComision>
              </xsl:when>
              <xsl:otherwise>
                  <debito>
                      <xsl:value-of select="/ns8:entradaEjecutarReverso/ns8:valorPago"/>
                  </debito>
                  <debitoComision>
                      <xsl:text disable-output-escaping="no">0.00</xsl:text>
                  </debitoComision>
              </xsl:otherwise>
          </xsl:choose>
		<detalleRubro>
		    <xsl:value-of select='/ns8:entradaEjecutarReverso/ns8:datosAdicionales/ns8:datoAdicional[codigo = "detalle_rubro"]/valor'/>
        </detalleRubro>
          <xsl:choose>
              <xsl:when test="/ns8:entradaEjecutarReverso/ns8:canal = 'CNB' and (/ns8:entradaEjecutarReverso/ns8:datosAdicionales/ns8:datoAdicional[codigo = 'p_forma_pago']/valor = 'EFE')">
                  <efectivo>
                    <xsl:value-of select="/ns8:entradaEjecutarReverso/ns8:valorPago"/>
                  </efectivo>
                  <efectivoComision>
                    <xsl:value-of select="/ns8:entradaEjecutarReverso/ns8:valorComision"/>
                  </efectivoComision>
              </xsl:when>
              <xsl:otherwise>
                  <efectivo>
                    <xsl:text disable-output-escaping="no">0.00</xsl:text>
                  </efectivo>
                  <efectivoComision>
                    <xsl:text disable-output-escaping="no">0.00</xsl:text>
                  </efectivoComision>
              </xsl:otherwise>
          </xsl:choose>
          <xsl:choose>
              <xsl:when test="/ns8:entradaEjecutarReverso/ns8:canal = 'CNB'">
                  <empresa>
                      <xsl:text disable-output-escaping="no">5488</xsl:text>
                  </empresa>
              </xsl:when>
              <xsl:otherwise>
                  <empresa>
                      <xsl:value-of select="/ns8:entradaEjecutarReverso/ns8:servicio/codigoEmpresa"/>
                  </empresa>
              </xsl:otherwise>
          </xsl:choose>

        <identificacion>
          <xsl:value-of select='/ns8:entradaEjecutarReverso/ns8:datosAdicionales/ns8:datoAdicional[codigo = "codigo_suministro"]/valor'/>
        </identificacion>
	
        <nombre>
          <xsl:value-of select="/ns8:entradaEjecutarReverso/ns8:nombreCliente"/>
        </nombre>
        <tipoMoneda>
          <xsl:value-of select="/ns8:entradaEjecutarReverso/ns8:moneda"/>
        </tipoMoneda>
          <ubicacion>
              <xsl:text disable-output-escaping="no">0</xsl:text>
          </ubicacion>
        <totalComision>
          <xsl:value-of select="/ns8:entradaEjecutarReverso/ns8:valorComision"/>
        </totalComision>
          <valorCheque>
              <xsl:text disable-output-escaping="no">0.00</xsl:text>
          </valorCheque>
        <valorTotalCancelar>
          <xsl:value-of select="/ns8:entradaEjecutarReverso/ns8:valorPago"/>
        </valorTotalCancelar>
        <cuenta>
          <cuenta>
            <xsl:value-of select="/ns8:entradaEjecutarReverso/ns8:cuenta"/>
          </cuenta>
         <xsl:choose>
            <xsl:when test ="/ns8:entradaEjecutarReverso/ns8:canal = 'CNB' and (/ns8:entradaEjecutarReverso/ns8:datosAdicionales/ns8:datoAdicional[codigo = 'p_forma_pago']/valor = 'EFE')">
              <tipoCuenta>
                <xsl:text disable-output-escaping="no">CTE</xsl:text>
              </tipoCuenta>
            </xsl:when>
            <xsl:otherwise>
              <tipoCuenta>
                <xsl:value-of select="/ns8:entradaEjecutarReverso/ns8:tipoCuenta"/>
              </tipoCuenta>
            </xsl:otherwise>
          </xsl:choose>
          <servicio>
            <xsl:text disable-output-escaping="no">7</xsl:text>
          </servicio>
            <subtotal>
                <xsl:text disable-output-escaping="no">0.00</xsl:text>
            </subtotal>
        </cuenta>
        <autoriza>
          <xsl:text disable-output-escaping="no">N</xsl:text>
        </autoriza>
        <codigoPreAutorizacion>
            <xsl:value-of select='/ns8:entradaEjecutarReverso/ns8:datosAdicionales/ns8:datoAdicional[codigo = "codigoProveedor"]/valor'/>
        </codigoPreAutorizacion>
        <nombreSuscriptor>
          <xsl:value-of select="/ns8:entradaEjecutarReverso/ns8:nombreCliente"/>
        </nombreSuscriptor>
      </DirectvPostpago>
      <informacionCore>
        <fechaProcesoKernel>
          <xsl:value-of select='/ns8:entradaEjecutarReverso/ns8:datosAdicionales/ns8:datoAdicional[codigo = "s_date"]/valor'/>
        </fechaProcesoKernel>
        <login>
          <xsl:text disable-output-escaping="no">998</xsl:text>
        </login>
        <modoCorreccion>
          <xsl:text disable-output-escaping="no">S</xsl:text>
        </modoCorreccion>
        <reversoTransaccion>
           <xsl:value-of select='/ns8:entradaEjecutarReverso/ns8:datosAdicionales/ns8:datoAdicional[codigo = "p_reversoTransaccion"]/valor'/>
        </reversoTransaccion>
        <rolBPM>
          <xsl:value-of select='/ns8:entradaEjecutarReverso/ns8:datosAdicionales/ns8:datoAdicional[codigo = "s_rol"]/valor'/>
        </rolBPM>
        <sec>
          <xsl:value-of select='/ns8:entradaEjecutarReverso/ns8:datosAdicionales/ns8:datoAdicional[codigo = "s_ssn"]/valor'/>
        </sec>
        <secuencial>
          <xsl:value-of select='/ns8:entradaEjecutarReverso/ns8:datosAdicionales/ns8:datoAdicional[codigo = "s_ssn"]/valor'/>
        </secuencial>
        <servidor>
          <xsl:value-of select='/ns8:entradaEjecutarReverso/ns8:datosAdicionales/ns8:datoAdicional[codigo = "s_srv"]/valor'/>
        </servidor>
      </informacionCore>
        <xsl:choose>
            <xsl:when test="/ns8:entradaEjecutarReverso/ns8:canal = 'CNB'">
                <CNB>
                    <autorizacion>
                        <xsl:value-of select="/ns8:entradaEjecutarReverso/ns8:datosAdicionales/ns8:datoAdicional[codigo = 'p_autorizacionCNB']/valor"/>
                    </autorizacion>
                    <comercio>
                        <xsl:value-of select="/ns8:entradaEjecutarReverso/ns8:datosAdicionales/ns8:datoAdicional[codigo = 'p_comercio']/valor"/>
                    </comercio>
                    <terminalID>
                        <xsl:value-of select="/ns8:entradaEjecutarReverso/ns8:datosAdicionales/ns8:datoAdicional[codigo = 'p_terminalID']/valor"/>
                    </terminalID>
                    <agencia>
                        <xsl:value-of select="/ns8:entradaEjecutarReverso/ns8:datosAdicionales/ns8:datoAdicional[codigo = 'p_agencia']/valor"/>
                    </agencia>
                    <red>
                        <xsl:value-of select="/ns8:entradaEjecutarReverso/ns8:datosAdicionales/ns8:datoAdicional[codigo = 'p_red']/valor"/>
                    </red>
                    <secuencial>
                        <xsl:value-of select='/ns8:entradaEjecutarReverso/ns8:datosAdicionales/ns8:datoAdicional[codigo = "s_ssn"]/valor'/>
                    </secuencial>
                    <valor>
                        <xsl:value-of select="format-number(/ns8:entradaEjecutarReverso/ns8:valorPago, '0.00')"/>
                    </valor>
                    <nombreCliente>
                        <xsl:value-of select='/ns8:entradaEjecutarReverso/ns8:datosAdicionales/ns8:datoAdicional[codigo = "p_nombreCliente"]/valor'/>
                    </nombreCliente>
                    <identificacionCliente>
                        <xsl:value-of select='/ns8:entradaEjecutarReverso/ns8:datosAdicionales/ns8:datoAdicional[codigo = "p_identificacionCliente"]/valor'/>
                    </identificacionCliente>
                    <modoCorreccion>
                        <xsl:text disable-output-escaping="no">S</xsl:text>
                    </modoCorreccion>
                    <reversoTransaccion>
                        <xsl:value-of select='/ns8:entradaEjecutarReverso/ns8:datosAdicionales/ns8:datoAdicional[codigo = "p_reversoTransaccion"]/valor'/>
                    </reversoTransaccion>
                    <tipoTransaccion>R</tipoTransaccion>
                    <formaPago>
                        <xsl:value-of select='/ns8:entradaEjecutarReverso/ns8:datosAdicionales/ns8:datoAdicional[codigo = "p_forma_pago"]/valor'/>
                    </formaPago>
                </CNB>
            </xsl:when>
        </xsl:choose>
    </xsd1:MensajeEntradaReverso>
  </xsl:template>
</xsl:stylesheet>
