<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../../../../../../../Disco%20D/veinti4online/Proyecto%20Cash/Concentrador%20de%20pagos/DOCUMENTACIONMAPEO/Project4/xsd/DirecTV_1.wsdl"/>
      <rootElement name="MensajeSalidaPago" namespace="http://www.bolivariano.com/MensajeDirecTV"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../../../../../../../Disco%20D/veinti4online/Proyecto%20Cash/Concentrador%20de%20pagos/DOCUMENTACIONMAPEO/Project4/otc-nopolicy.wsdl"/>
      <rootElement name="salidaEjecutarPago" namespace="http://www.bolivariano.com/mensaje/MensajeOTC"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 130301.0647.0008) AT [FRI MAY 25 13:46:21 COT 2018]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:xsd1="http://www.bolivariano.com/MensajeDirecTV"
                xmlns:tns="http://www.bolivariano.com/ws/DirecTV/"
                xmlns:ns7="http://www.bolivariano.com/dominio/DatoAdicional"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:ns1="http://www.bolivariano.com/CoreBB"
                xmlns:ns3="http://www.bolivariano.com/Cuenta"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:ns13="http://www.bolivariano.com/dominio/Convenio"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns14="http://www.bolivariano.com/dominio/Recibo"
                xmlns:ns6="http://www.bolivariano.com/DirecTV"
                xmlns:ns18="http://www.bolivariano.com/dominio/ListaSeleccion"
                xmlns:ns17="http://www.bolivariano.com/dominio/RegionalArea"
                xmlns:ns9="http://www.bolivariano.com/dominio/Servicio"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:ns0="http://www.bolivariano.com/MensajeBolivariano"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:ns4="http://www.bolivariano.com/Recaudo"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:ns10="http://www.bolivariano.com/dominio/TipoMatriculacion"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:ns11="http://www.bolivariano.com/dominio/FormaPago"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns12="http://www.bolivariano.com/dominio/TipoIdentificador"
                xmlns:ns8="http://www.bolivariano.com/mensaje/MensajeOTC"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:ns2="http://www.bolivariano.com/Producto"
                xmlns:ns15="http://www.bolivariano.com/dominio/Empresa"
                xmlns:ns5="http://www.bolivariano.com/Cliente"
                xmlns:ns16="http://www.bolivariano.com/mensaje/MensajeOTC"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                xmlns:java="java"
                exclude-result-prefixes="xsi xsl xsd1 tns soap ns1 ns3 wsdl ns6 ns0 ns4 xsd ns2 ns5 ns7 ns13 ns14 ns18 ns17 ns9 ns10 ns11 ns12 ns8 ns15 ns16 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap">
  <xsl:template match="/">
    <ns8:salidaEjecutarPago>
      <xsl:if test="/xsd1:MensajeSalidaPago/codigoError='0'">
        <ns16:codigoError>
          <xsl:value-of select="/xsd1:MensajeSalidaPago/codigoError"/>
        </ns16:codigoError>   
        <ns16:mensajeUsuario>
            <xsl:value-of select="/xsd1:MensajeSalidaPago/mensajeUsuario"/>
          </ns16:mensajeUsuario>  
          <ns16:datosAdicionales>
            <ns16:datoAdicional>
              <codigo>Suscriptor</codigo>
              <etiqueta>
                <xsl:text disable-output-escaping="no">Suscriptor</xsl:text>
              </etiqueta>
              <editable>
                <xsl:text disable-output-escaping="no">false</xsl:text>
              </editable>
              <valor>
                <xsl:value-of select="/xsd1:MensajeSalidaPago/directv/nombreSuscriptor"/>
              </valor>
            <visible>
                <xsl:text disable-output-escaping="no">true</xsl:text>
              </visible>
            </ns16:datoAdicional>
            <ns16:datoAdicional>
              <codigo>Autorizacion</codigo>
              <etiqueta>            
                <xsl:text disable-output-escaping="no">Autorizacion</xsl:text>
              </etiqueta>
              <editable>
                <xsl:text disable-output-escaping="no">false</xsl:text>
              </editable>
              <valor>
                <xsl:value-of select="/xsd1:MensajeSalidaPago/directv/autorizacion"/>
              </valor>
              <visible>
                <xsl:text disable-output-escaping="no">true</xsl:text>
              </visible>
            </ns16:datoAdicional>
            <ns16:datoAdicional>
					    <codigo>horario</codigo>
					    <valor>
						    <xsl:value-of select="/xsd1:MensajeSalidaPago/directv/horario"/>
					    </valor>
				    </ns16:datoAdicional>
          </ns16:datosAdicionales>    
          <ns17:fechaDebito>
            <xsl:value-of select='java:format(java:text.SimpleDateFormat.new("yyyy-MM-dd&apos;T&apos;HH:mm:ss.SSS"), java:util.Date.new())'/>
          </ns17:fechaDebito>
          <ns17:fechaPago>
            <xsl:value-of select="/xsd1:MensajeSalidaPago/directv/fechaEfectiva"/>
          </ns17:fechaPago>              
        <ns16:referencia>
        <xsl:value-of select="/xsd1:MensajeSalidaPago/informacionCore/secuencial"/>
      </ns16:referencia>
      </xsl:if>
      <xsl:if test="/xsd1:MensajeSalidaPago/codigoError!='0'">
        <ns16:codigoError>
          <xsl:value-of select="/xsd1:MensajeSalidaPago/codigoError"/>
        </ns16:codigoError>      
          <ns16:mensajeUsuario>
            <xsl:value-of select="/xsd1:MensajeSalidaPago/mensajeUsuario"/>
          </ns16:mensajeUsuario>  
        </xsl:if>
    </ns8:salidaEjecutarPago>
  </xsl:template>
</xsl:stylesheet>
