<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../otc-nopolicy.wsdl"/>
      <rootElement name="entradaEjecutarReverso" namespace="http://www.bolivariano.com/ws/OTCService"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../xsd/RecaudacionEducacion_1.wsdl"/>
      <rootElement name="MensajeEntradaReversar" namespace="http://www.bolivariano.com/CashManagement/MensajesRecaudacionEducacion"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 130301.0647.0008) AT [SAT JUN 02 17:26:53 COT 2018]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:ns11="http://www.bolivariano.com/CashManagement/ws/RecaudacionEducacion"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:ns12="http://www.bolivariano.com/FormaPago"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:ns15="http://www.bolivariano.com/Enumerados"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:ns1="http://www.bolivariano.com/dominio/DatoAdicional"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:ns14="http://www.bolivariano.com/CoreBB"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:ns5="http://www.bolivariano.com/dominio/Convenio"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns6="http://www.bolivariano.com/dominio/Recibo"
                xmlns:mc="http://www.bolivariano.com/CashManagement/MensajesRecaudacionEducacion"
                xmlns:ns9="http://www.bolivariano.com/dominio/RegionalArea"
                xmlns:ns10="http://www.bolivariano.com/dominio/ListaSeleccion"
                xmlns:ns0="http://www.bolivariano.com/dominio/Servicio"
                xmlns:ns13="http://www.bolivariano.com/MensajeBolivariano"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:ns2="http://www.bolivariano.com/dominio/TipoMatriculacion"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:ns3="http://www.bolivariano.com/dominio/FormaPago"
                xmlns:ns17="http://www.bolivariano.com/Restricciones"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns4="http://www.bolivariano.com/dominio/TipoIdentificador"
                xmlns:tns="http://www.bolivariano.com/ws/OTCService"
                xmlns:http="http://schemas.xmlsoap.org/wsdl/http/"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:ns7="http://www.bolivariano.com/dominio/Empresa"
                xmlns:ns8="http://www.bolivariano.com/mensaje/MensajeOTC"
                xmlns:ns16="http://www.bolivariano.com/Comision"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl ns1 soap wsdl ns5 ns6 ns9 ns10 ns0 ns2 ns3 ns4 tns xsd ns7 ns8 ns11 ns12 ns15 ns14 mime mc ns13 plnk ns17 http ns16 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap">
  
<xsl:template match="/">
    <mc:MensajeEntradaReversar>
         <canal>
            <xsl:value-of select="/ns8:entradaEjecutarReverso/ns8:canal"/>
         </canal>
         <depuracion>
            <xsl:value-of select="/ns8:entradaEjecutarReverso/ns8:depuracion"/>
         </depuracion>
         <fecha>
            <xsl:value-of select='/ns8:entradaEjecutarReverso/ns8:datosAdicionales/ns8:datoAdicional[codigo = "s_date"]/valor'/>
          </fecha>
         <oficina>
			<xsl:choose>
               <xsl:when test="/ns8:entradaEjecutarReverso/ns8:canal='CNB'">
                  <xsl:value-of select="/ns8:entradaEjecutarReverso/ns8:oficina" />
               </xsl:when>
               <xsl:otherwise>
                  <xsl:value-of select='/ns8:entradaEjecutarReverso/ns8:datosAdicionales/ns8:datoAdicional[codigo = "s_ofi"]/valor'/>
               </xsl:otherwise>
            </xsl:choose>
         </oficina>
	 <terminal>
	 <xsl:choose>
		   <xsl:when test="/ns8:entradaEjecutarReverso/ns8:canal='CNB'">
<xsl:value-of select="/ns8:entradaEjecutarReverso/ns8:s_term"/>
		   </xsl:when>
		   <xsl:otherwise>
			 
             <xsl:text disable-output-escaping="no">PC</xsl:text>
      
		   </xsl:otherwise>
		</xsl:choose> 
        	 </terminal>
         <transaccion>
            <xsl:value-of select="/ns8:entradaEjecutarReverso/ns8:transaccion"/>
         </transaccion>
		 <secuencial>
			<xsl:choose>
               <xsl:when test="/ns8:entradaEjecutarReverso/ns8:canal='CNB'">
                  <xsl:value-of select="/ns8:entradaEjecutarReverso/ns8:secuencial" />
               </xsl:when>
               <xsl:otherwise>
                  <xsl:value-of select='/ns8:entradaEjecutarReverso/ns8:datosAdicionales/ns8:datoAdicional[codigo = "s_ssn"]/valor'/>
               </xsl:otherwise>
            </xsl:choose>
		 </secuencial>
		 <usuario>
			<xsl:choose>
               <xsl:when test="/ns8:entradaEjecutarReverso/ns8:canal='CNB'">
                  <xsl:value-of select="/ns8:entradaEjecutarReverso/ns8:usuario" />
               </xsl:when>
               <xsl:otherwise>
                  <xsl:value-of select='/ns8:entradaEjecutarReverso/ns8:datosAdicionales/ns8:datoAdicional[codigo = "s_user"]/valor'/>
               </xsl:otherwise>
            </xsl:choose>  
		 </usuario>
         <codigoInstitucion>
	   <xsl:choose>	    
		<xsl:when test='/ns8:entradaEjecutarReverso/ns8:datosAdicionales/ns8:datoAdicional[codigo = "s_codInstitucion"]/valor=99900'>          
			<xsl:text disable-output-escaping="no">6</xsl:text>                    
		</xsl:when>
		<xsl:when test='/ns8:entradaEjecutarReverso/ns8:datosAdicionales/ns8:datoAdicional[codigo = "s_codInstitucion"]/valor=99901'>        
			<xsl:text disable-output-escaping="no">204</xsl:text>                      
		</xsl:when>
		<xsl:when test='/ns8:entradaEjecutarReverso/ns8:datosAdicionales/ns8:datoAdicional[codigo = "s_codInstitucion"]/valor=99902'>          
			<xsl:text disable-output-escaping="no">22</xsl:text>                      
		</xsl:when>
		<xsl:when test='/ns8:entradaEjecutarReverso/ns8:datosAdicionales/ns8:datoAdicional[codigo = "s_codInstitucion"]/valor=99903'>        
			<xsl:text disable-output-escaping="no">283</xsl:text>                     
		</xsl:when>
		<xsl:when test='/ns8:entradaEjecutarReverso/ns8:datosAdicionales/ns8:datoAdicional[codigo = "s_codInstitucion"]/valor=99904'>        
			<xsl:text disable-output-escaping="no">3</xsl:text>                      
		</xsl:when>
		<xsl:when test='/ns8:entradaEjecutarReverso/ns8:datosAdicionales/ns8:datoAdicional[codigo = "s_codInstitucion"]/valor=99905'>          
			<xsl:text disable-output-escaping="no">228</xsl:text>                      
		</xsl:when>
		<xsl:when test='/ns8:entradaEjecutarReverso/ns8:datosAdicionales/ns8:datoAdicional[codigo = "s_codInstitucion"]/valor=99906'>          
			<xsl:text disable-output-escaping="no">4</xsl:text>                      
		</xsl:when>
		<xsl:when test='/ns8:entradaEjecutarReverso/ns8:datosAdicionales/ns8:datoAdicional[codigo = "s_codInstitucion"]/valor=99907'>          
			<xsl:text disable-output-escaping="no">276</xsl:text>                      
		</xsl:when>
		<xsl:otherwise>		
			<xsl:value-of select='/ns8:entradaEjecutarReverso/ns8:datosAdicionales/ns8:datoAdicional[codigo = "s_codInstitucion"]/valor'/>          
		</xsl:otherwise>	   
	      </xsl:choose> 
         </codigoInstitucion>
         <codigoAlumno>
            <xsl:value-of select="/ns8:entradaEjecutarReverso/ns8:servicio/identificador"/>
         </codigoAlumno>
         <nombreAlumno>
            <xsl:value-of select="/ns8:entradaEjecutarReverso/ns8:nombreCliente"/>
         </nombreAlumno>
         <moneda>
            <xsl:value-of select="/ns8:entradaEjecutarReverso/ns8:moneda"/>
         </moneda>
         <pago>
            <valorPagoTotal>
	      <xsl:value-of select="/ns8:entradaEjecutarReverso/ns8:valorPago"/>
            </valorPagoTotal>
            <valorComisionTotal>
	      <xsl:value-of select="/ns8:entradaEjecutarReverso/ns8:valorComision"/>
            </valorComisionTotal>
			
			<xsl:choose>
			   <xsl:when test="/ns8:entradaEjecutarReverso/ns8:canal='CNB'">
				  <efectivo>
					<valor>
						<xsl:value-of select="/ns8:entradaEjecutarReverso/ns8:valorPago"/>
					</valor>
					<valorComision>
						<xsl:value-of select="/ns8:entradaEjecutarReverso/ns8:valorComision"/>
					</valorComision>
				  </efectivo>
			   </xsl:when>
			   <xsl:otherwise>
				  <debitoCuenta>
					  <tipoCuenta>
							<xsl:value-of select="/ns8:entradaEjecutarReverso/ns8:tipoCuenta"/>
					  </tipoCuenta>
					  <cuenta>
							<xsl:value-of select="/ns8:entradaEjecutarReverso/ns8:cuenta"/>
					  </cuenta>
					  <valor>
							<xsl:value-of select="/ns8:entradaEjecutarReverso/ns8:valorPago"/>
					  </valor>
					  <valorComision>
							<xsl:value-of select="/ns8:entradaEjecutarReverso/ns8:valorComision"/>
					  </valorComision>
					</debitoCuenta>
			   </xsl:otherwise>
			</xsl:choose> 
            
	 </pago>
	<xsl:choose>
	   <xsl:when test="/ns8:entradaEjecutarReverso/ns8:canal='CNB'">
			<codigoProceso>
				<xsl:text disable-output-escaping="no">V</xsl:text>
			</codigoProceso>
	   </xsl:when>
	   <xsl:otherwise>
		<xsl:for-each select="/ns8:entradaEjecutarReverso/ns8:datosAdicionales/ns8:datoAdicional">
        <xsl:if test='codigo = "CODIGOPROCESO"'>
          <codigoProceso>
            <xsl:value-of select="valor"/>
          </codigoProceso>
        </xsl:if>
      </xsl:for-each>
	   </xsl:otherwise>
	</xsl:choose>  
	  
	  
	  
          <!-- concatenar los adicioles del recibo separados por ; -->
		<xsl:choose>
		   <xsl:when test="/ns8:entradaEjecutarReverso/ns8:canal='CNB'">
			<referencia><xsl:value-of select='/ns8:entradaEjecutarReverso/ns8:datosAdicionales/ns8:datoAdicional[codigo = "codigoReferencia"]/valor'/>;<xsl:value-of select='/ns8:entradaEjecutarReverso/ns8:datosAdicionales/ns8:datoAdicional[codigo = "fecha"]/valor'/>;<xsl:value-of select='/ns8:entradaEjecutarReverso/ns8:datosAdicionales/ns8:datoAdicional[codigo = "codigoProceso"]/valor'/>;</referencia>
		   </xsl:when>
		   <xsl:otherwise>
				<referencia>
					<xsl:for-each select="/ns8:entradaEjecutarReverso/ns8:recibos/ns8:recibo/datosAdicionales/datoAdicional">
					  <xsl:if test="codigo= 'codigoReferencia'"><xsl:value-of select="valor"/>;</xsl:if>
					  <xsl:if test="codigo= 'fecha'"><xsl:value-of select="valor"/>;</xsl:if>
					  <xsl:if test="codigo= 'codigoProceso'"><xsl:value-of select="valor"/>;</xsl:if>
					</xsl:for-each>
				</referencia>
		   </xsl:otherwise>
		</xsl:choose> 
	  
	  
         <origenTransaccion>
			<xsl:choose>
               <xsl:when test="/ns8:entradaEjecutarReverso/ns8:canal='CNB'">
                  <xsl:value-of select='/ns8:entradaEjecutarReverso/ns8:datosAdicionales/ns8:datoAdicional[codigo = "p_reversoTransaccion"]/valor' />
               </xsl:when>
               <xsl:otherwise>
                  <xsl:value-of select='/ns8:entradaEjecutarReverso/ns8:datosAdicionales/ns8:datoAdicional[codigo = "s_ssn_reverse"]/valor'/>
               </xsl:otherwise>
            </xsl:choose>
         </origenTransaccion>
	    <tipoReverso>
			<xsl:choose>
               <xsl:when test="/ns8:entradaEjecutarReverso/ns8:canal='CNB'">
                  <xsl:value-of select='/ns8:entradaEjecutarReverso/ns8:datosAdicionales/ns8:datoAdicional[codigo = "p_modoCorreccion"]/valor' />
               </xsl:when>
               <xsl:otherwise>
                  <xsl:value-of select='/ns8:entradaEjecutarReverso/ns8:datosAdicionales/ns8:datoAdicional[codigo = "p_reverso"]/valor'/>
               </xsl:otherwise>
            </xsl:choose>
         </tipoReverso>
		 
		 <xsl:choose>
		   <xsl:when test="/ns8:entradaEjecutarReverso/ns8:canal='CNB'">
			 <identificacion>
				<xsl:value-of select='/ns8:entradaEjecutarReverso/ns8:datosAdicionales/ns8:datoAdicional[codigo = "p_identificacion"]/valor'/>
			 </identificacion>
			 <nombre>
				<xsl:value-of select='/ns8:entradaEjecutarReverso/ns8:datosAdicionales/ns8:datoAdicional[codigo = "p_nombre"]/valor'/>
			 </nombre>
		   </xsl:when>
		</xsl:choose>

	  <CNB>
		<autorizacion>
			<xsl:value-of select='/ns8:entradaEjecutarReverso/ns8:datosAdicionales/ns8:datoAdicional[codigo = "p_autorizacionCNB"]/valor'/>
		</autorizacion>
		<comercio>
			<xsl:value-of select='/ns8:entradaEjecutarReverso/ns8:datosAdicionales/ns8:datoAdicional[codigo = "p_comercio"]/valor'/>
		</comercio>
		<terminalID>
			<xsl:value-of select='/ns8:entradaEjecutarReverso/ns8:datosAdicionales/ns8:datoAdicional[codigo = "p_terminalID"]/valor'/>
		</terminalID>
		<agencia>
			<xsl:value-of select='/ns8:entradaEjecutarReverso/ns8:datosAdicionales/ns8:datoAdicional[codigo = "p_agencia"]/valor'/>
		</agencia>
		<red>
			<xsl:value-of select='/ns8:entradaEjecutarReverso/ns8:datosAdicionales/ns8:datoAdicional[codigo = "p_red"]/valor'/>
		</red>
	  </CNB>
      </mc:MensajeEntradaReversar>
   </xsl:template>
</xsl:stylesheet>
