<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../xsd/RecaudacionEducacion_1.wsdl"/>
      <rootElement name="MensajeSalidaPagar" namespace="http://www.bolivariano.com/CashManagement/MensajesRecaudacionEducacion"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../otc-nopolicy.wsdl"/>
      <rootElement name="salidaEjecutarPago" namespace="http://www.bolivariano.com/mensaje/MensajeOTC"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 130301.0647.0008) AT [THU MAY 31 18:56:58 COT 2018]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:tns="http://www.bolivariano.com/CashManagement/ws/RecaudacionEducacion"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:ns0="http://www.bolivariano.com/FormaPago"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:ns3="http://www.bolivariano.com/Enumerados"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:ns6="http://www.bolivariano.com/dominio/DatoAdicional"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:ns2="http://www.bolivariano.com/CoreBB"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:ns12="http://www.bolivariano.com/dominio/Convenio"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns13="http://www.bolivariano.com/dominio/Recibo"
                xmlns:mc="http://www.bolivariano.com/CashManagement/MensajesRecaudacionEducacion"
                xmlns:ns16="http://www.bolivariano.com/dominio/RegionalArea"
                xmlns:ns17="http://www.bolivariano.com/dominio/ListaSeleccion"
                xmlns:ns8="http://www.bolivariano.com/dominio/Servicio"
                xmlns:ns1="http://www.bolivariano.com/MensajeBolivariano"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:ns9="http://www.bolivariano.com/dominio/TipoMatriculacion"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:ns10="http://www.bolivariano.com/dominio/FormaPago"
                xmlns:ns5="http://www.bolivariano.com/Restricciones"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns11="http://www.bolivariano.com/dominio/TipoIdentificador"
                xmlns:ns7="http://www.bolivariano.com/mensaje/MensajeOTC"
                xmlns:http="http://schemas.xmlsoap.org/wsdl/http/"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:ns14="http://www.bolivariano.com/dominio/Empresa"
                xmlns:ns4="http://www.bolivariano.com/Comision"
                xmlns:java="java"
                xmlns:ns15="http://www.bolivariano.com/mensaje/MensajeOTC"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl tns ns0 ns3 soap ns2 wsdl mime mc ns1 plnk ns5 http xsd ns4 ns6 ns12 ns13 ns16 ns17 ns8 ns9 ns10 ns11 ns7 ns14 ns15 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap">
  <xsl:template match="/">
    <ns15:salidaEjecutarPago>
	  <ns15:datosAdicionales>
        <ns15:datoAdicional>
          <codigo>
            <xsl:text disable-output-escaping="no">secuencial</xsl:text>
          </codigo>
          <valor>
            <xsl:value-of select="/mc:MensajeSalidaPagar/secuencialReverso"/>
          </valor>
        </ns15:datoAdicional>
		<ns15:datoAdicional>
          <codigo>
            <xsl:text disable-output-escaping="no">valorComision</xsl:text>
          </codigo>
          <valor>
            <xsl:value-of select="/mc:MensajeSalidaPagar/comision/costoComision"/>
          </valor>
        </ns15:datoAdicional>
      </ns15:datosAdicionales>
      <ns15:codigoError>
        <xsl:value-of select="/mc:MensajeSalidaPagar/codigoError"/>
      </ns15:codigoError>
      <ns15:mensajeUsuario>
        <xsl:value-of select="/mc:MensajeSalidaPagar/mensajeSistema"/>
      </ns15:mensajeUsuario>
      <ns15:montoTotal>
        <xsl:value-of select="/mc:MensajeSalidaPagar/valorPago"/>
      </ns15:montoTotal>
      <ns15:referencia>
        <xsl:value-of select="/mc:MensajeSalidaPagar/secuenciaTransaccion"/>;<xsl:value-of select="/mc:MensajeSalidaPagar/secuencialReverso"/>
      </ns15:referencia>        
      <ns15:fechaDebito>
		<xsl:choose>
			<xsl:when test="/mc:MensajeSalidaPagar/canal = 'CNB'">
				<xsl:value-of select='java:format(java:text.SimpleDateFormat.new("yyyy-MM-dd"), java:util.Date.new())'/>
			</xsl:when>
			<xsl:otherwise>
				<xsl:value-of select='java:format(java:text.SimpleDateFormat.new("yyyy-MM-dd&apos;T&apos;HH:mm:ss.SSS"), java:util.Date.new())'/>
			</xsl:otherwise>
		</xsl:choose>
      </ns15:fechaDebito>      
      <ns15:fechaPago>
		<xsl:choose>
			<xsl:when test="/mc:MensajeSalidaPagar/canal = 'CNB'">
				<!--<xsl:value-of select="java:format(java:text.SimpleDateFormat.new('dd/MM/yyyy'), '/mc:MensajeSalidaPagar/fechaProceso')"/>-->
        <xsl:value-of select="concat(substring(/mc:MensajeSalidaPagar/fechaProceso,1,4),'-',substring(/mc:MensajeSalidaPagar/fechaProceso,6,2),'-',substring(/mc:MensajeSalidaPagar/fechaProceso,9,2) )"/> 
			</xsl:when>
			<xsl:otherwise>
				<xsl:value-of select='java:format(java:text.SimpleDateFormat.new("yyyy-MM-dd"), java:util.Date.new())'/>
			</xsl:otherwise>
		</xsl:choose>        
      </ns15:fechaPago>      
    </ns15:salidaEjecutarPago>
  </xsl:template>
</xsl:stylesheet>
